### ISSUE TITLE
Getting Unable to release unknown session errors 

### ISSUE THREAD

**Issue by kriptontr** [googleapis/nodejs-spanner#103]
Hello,

We are using cloud spanner library on our REST endpoint and we do create only one DB instance. When more than 10 users start to make requests to that endpoint it suddenly starts to throw an exception 'Unable to release unknown session.'. I don't know what causes this but is this about something we need to change or is this about something with the library? Do we have to create new instances for every request?

Error stack output:
Error: Unable to release unknown session.
at SessionPool.release (/node_modules/@google-cloud/spanner/src/session-pool.js:284)
at Transaction.transaction.end (session-pool.js:536)
at (/node_modules/@google-cloud/spanner/src/transaction.js:316)
at (/node_modules/@google-cloud/spanner/src/transaction.js:397)
at _combinedTickCallback (internal/process/next_tick.js:138)
at process._tickCallback (next_tick.js:180)

I suspect there is a leak or glitch that removed session already or release session twice.

Using;
@google-cloud/spanner 1.0.2
 with https://github.com/nodejs/docker-node (node:8) and yarn

Its currently running in 1.8.6-gke.0 at Google Cloud and we getting this error via Stack Driver error reporting from rest deployment pods.

We currently don't know what causes it and how to reproduce. Any help to address the issue is appreciated.

Thanks

**Comment by callmehiphop** [comment]
@kriptontr thanks for reporting! Could you share your pooling configurations, if any.

Based on the error stack, I'm assuming the endpoint being described creates `read-only` transactions that you call `end()` on and never `commt()`?

**Comment by kriptontr** [comment]
Hello,

There is no pooling configuration actually, probably using [default](https://github.com/googleapis/nodejs-spanner/blob/master/src/session-pool.js#L30),  how can we have one, should we? I didn't notice any on docs.

Its not read-only, we also have write operations and transactions, and lib throws error on transaction.commit() event
Or should we call end() after commit() ?

**Comment by callmehiphop** [comment]
@kriptontr really its up to you, configurations are useful if you want to pre-initialize a lot of sessions and have transactions waiting and ready to go. The documentation can be found [here](https://cloud.google.com/nodejs/docs/reference/spanner/1.0.x/SessionPoolOptions) and passed into the database method like so

```js
const database = instance.database('my-db', { min: 10 });
```

As far as `end` vs. `commit`,

* `end()` should only be called when you are done with a read-only transaction.
* `commit()` should only be called when you are ready to commit changes on a read/write transaction.

Calling both methods on a single transaction could cause the error you are describing.

**Comment by zubeyiro** [comment]
Thanks, what if we set for example concurrency to 10.000, is that a problem? Or for example if we set it to 100, will it create a new session for 101th request?

**Comment by vkedia** [comment]
@callmehiphop I think calling both methods should throw some other meaningful error.

**Comment by callmehiphop** [comment]
> Thanks, what if we set for example concurrency to 10.000, is that a problem?

@zubeyiro Depends on your application! Setting it too low could create a bottleneck of sorts. I think by default we set it to 10.

> Or for example if we set it to 100, will it create a new session for 101th request?

Initially we create `n` of sessions where `n` is defined by the `min` option, which is `0` by default. We attempt to re-use sessions as much as possible, the only time we'll create a new session is when all pre-existing sessions are allocated and we haven't hit the `max` value, which by default is `100`. If there are already `100` sessions in the pool, then we will instead wait for one to be freed up.

> I think calling both methods should throw some other meaningful error.

@vkedia I agree, that's definitely something we can add. I'm also thinking it might be a good idea to go with a previous suggestion of yours and make separate objects for read only and read/write.

**Comment by zubeyiro** [comment]
Oh got it. So do I have to instantiate new database instances for every 100 sessions? If so, what happens if I set to max count to 10.000 (which is per spanner node session limit), will it work?

If it works that way, I guess I need create multiple REST endpoints (cluster docker images) for every 100 sessions

**Comment by callmehiphop** [comment]
@zubeyiro you can increase the `max` value to a number of your choosing, no need to make multiple `Database` instances.

**Comment by zubeyiro** [comment]
Perfect, thanks a lot

**Comment by callmehiphop** [comment]
@zubeyiro glad to have helped! I think we went off on a bit of a tangent, but does any of the dialogue here help resolve your original issue?

**Comment by zubeyiro** [comment]
Well actually it didnt yet, but I suspect min session allocation parameter could help on that, we are going to try it in couple of hours on our stress test and let you know if it reoccurs. It does not happen in normal conditions, it happens only when we send heavy traffic to endpoint

**Comment by callmehiphop** [comment]
Truthfully, I don't think adjusting the `min` value is going to help you there. If by chance you're calling both `commit` and `end` on a single transaction, refactoring your code to do one or the other would be the correct fix. If that is not the case, then I'll need to investigate further.

**Comment by zubeyiro** [comment]
We dont have any read-only transaction, only read-write transactions which end up with .commit(), in this case I guess there should be another investigation yes.

**Comment by callmehiphop** [comment]
@zubeyiro I've just published a patch release that includes some additional error handling. If you don't mind updating and letting us know how the stress tests go, that would be greatly appreciated!

**Comment by vkedia** [comment]
@callmehiphop since we have discovered couple of issues with this session pool recently, I think we should do some stress testing of this code under heavy concurrent use.

**Comment by zubeyiro** [comment]
@callmehiphop we have just made a stress test, the first error has gone, 'Unable to release unknown session'

But there are couple of things for .Net library and Cloud Spanner itself;
**1.** At .Net library for Cloud Spanner, we are using too many transactions concurrently, at our stress test we have detected transactions start to throw an error

`An invalid argument was sent to Spanner.`
`Row [] in table 'table_name' was already created in this transaction.`

I have looked into it a bit un noticed that its occurring because of interleaved tables, but we dont have any.

**2.** When we send load to cloud spanner concurrenctly and push the limits of it, it didnt auto-scaled node count (May be it didnt reach the limits, idk), I made it 5 manually, then it started to throw an error for every request;

`Too many active sessions in database 'my_database', limit is 10000. Increase the node count to allow more sessions`

Thats already what I was doing, and also total session count was 890.

I got this error even in Cloud Spanner GUI on Google Cloud.

Anyway error with NodeJS library seems to be gone

**Comment by callmehiphop** [comment]
@zubeyiro I can't speak for the .Net library, I would suggest opening an issue on their repo to get to the bottom of that error.

For the session limit, are freeing up your sessions at the end your process? In Node it would look something like this

```js
await database.close();
```
