### ISSUE TITLE
Errors from encodeValue_ are not caught and generate a UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by WaldoJeffers** [googleapis/nodejs-spanner#1078]
#### Environment details

  - OS: MacOSX 10.14.6
  - Node.js version: v10.19.0
  - npm version: 6.13.4
  - `@google-cloud/spanner` version: 5.1.0

#### Bug description
Errors thrown by [common-grpc/service/encodeValue_](https://github.com/googleapis/nodejs-spanner/blob/master/src/common-grpc/service.ts#L285) like [this one](https://github.com/googleapis/nodejs-spanner/blob/master/src/common-grpc/service.ts#L335) (passing `undefined` as value for a named parameter) are never caught by this function's caller, resulting in Unhandled Promise Rejections. **Also, for some reason it seems to crash the underlying Node.js process.**

The error thrown in `encodeValue_` goes all the way to `SessionPool.getReadSession` where it fails to be caught:
- [encodeValue_](https://github.com/googleapis/nodejs-spanner/blob/master/src/common-grpc/service.ts#L285)
- [GrpcService.encodeValue_](https://github.com/googleapis/nodejs-spanner/blob/master/src/common-grpc/service.ts#L786)
- [codec.encode](https://github.com/googleapis/nodejs-spanner/blob/master/src/codec.ts#L346)
- [Snapshot.encodeParams](https://github.com/googleapis/nodejs-spanner/blob/master/src/transaction.ts#L1034)
- [Snapshot.runStream](https://github.com/googleapis/nodejs-spanner/blob/master/src/transaction.ts#L889)
- [Database.runStream](https://github.com/googleapis/nodejs-spanner/blob/master/src/database.ts#L2109)
- [SessionPool.getReadSession](https://github.com/googleapis/nodejs-spanner/blob/master/src/session-pool.ts#L429) <-- Probably where the error should be caught

#### Steps to reproduce
There are probably different ways to reproduce the error; all you have to do is make the `encodeValue_` helper throw. One way to achieve this is to provide an `undefined` value to a named parameter in a query
  1. Run a query using named parameters, but don't pass a value to the parameter
```js
const q = {
  json: true,
  params: { },
  sql: 'SELECT * FROM tableId WHERE namedParameter = @namedParameter',
};
const [rows] = await db.run(q); // This will lead to an Unhandled Promise rejection
  ```

So any attempt to catch the error will fail
```js
const [rows] = await db.run(q).catch(() => console.log('I will never be called'));
  ```

But perhaps more unexpectedly, the code will stop running after this line:
```js
const [rows] = await db.run(q).catch(() => console.log('I will never be called'));
console.log('Unreachable code is never called ???');
  ```

I am preparing a PR which might help fix the issue; but wanted to file the issue separately in case you prefer to fix the issue differently.

Thanks for your help :)

**Comment by AVaksman** [comment]
@WaldoJeffers the below snippet worked for me.
```ts
    const q = {
        json: true,
        sql: 'SELECT * FROM Singers WHERE SingerId=@id',
    }
    try {
        const [rows] = await database.run(q);
        console.log(rows.length);
        rows.forEach(console.log);
    } catch (error) {
        console.log('I will get called.')
        console.log('Error message => ' + error.message);
    }
    console.log('Continue execution here...');
```
```
I will get called.
Error message => 3 INVALID_ARGUMENT: No parameter found for binding: id
Continue execution here...
```

**Comment by WaldoJeffers** [comment]
Hello @AVaksman,

Thanks for your answer. Could try the same thing with 

```
    const q = {
        json: true,
       params : { id: undefined }, // Add this line (assuming both Singers & SingerId really exist)
        sql: 'SELECT * FROM Singers WHERE SingerId=@id',
    }
    try {
        const [rows] = await database.run(q);
        console.log(rows.length);
        rows.forEach(console.log);
    } catch (error) {
        console.log('I will get called.')
        console.log('Error message => ' + error.message);
    }
    console.log('Continue execution here...');
```

This does result in `(node:8165) UnhandledPromiseRejectionWarning: Error: Value of type undefined not recognized.` for me

**Comment by olavloite** [comment]
@WaldoJeffers Would you mind also having a look at #1208?

**Comment by WaldoJeffers** [comment]
Hello @olavloite ,

Thanks for your PR. It's probably a much better fix than my PR, but I'm not familiar enough with the codebase to provide feedback on the changes 😬
