### ISSUE TITLE
samples tests fail

### ISSUE THREAD

**Issue by alexander-fenster** [googleapis/nodejs-spanner#1147]
They fail :)   (#1146 is an example)

**Comment by larkee** [comment]
Thank you for filing this issue!

triage - This issue looks related to the Mocha test issues opened by the build cop, specifically #1120, #1091, and #1089. Those issues have links to build logs which should give more details for debugging.

**Comment by skuruppu** [comment]
For the buildcop issues, I've filed #958 and @AVaksman is working on a fix.

I used Test Fusion to look at the failure history for #1146 and found the following failures:
- [failure 1](https://sponge.corp.google.com/target?id=79db3858-141c-4b3f-b5f0-22c6d68a96b8&target=cloud-devrel%2Fclient-libraries%2Fnodejs%2Fpresubmit%2Fgoogleapis%2Fnodejs-spanner%2Fnode10%2Fsamples-test&searchFor=)
- [failure 2](https://sponge.corp.google.com/target?id=d77782cc-9eb5-42f3-be47-e9baa7a9b2de&target=cloud-devrel%2Fclient-libraries%2Fnodejs%2Fpresubmit%2Fgoogleapis%2Fnodejs-spanner%2Fnode10%2Fsamples-test&searchFor=)

The errors are something like:
```
ERROR: { Error: 5 NOT_FOUND: Row [1,1] in table Albums is missing. Row cannot be updated.
...
ERROR: { Error: 5 NOT_FOUND: Index updates failed because no existing data was found for Albums[2,2]
```

So I think these failures have to do with #1072. I will dig into the test setup.

**Comment by skuruppu** [comment]
Ugh, [another one](https://source.cloud.google.com/results/invocations/556382e4-838a-40f2-9e8f-956bc109c578/targets/cloud-devrel%2Fclient-libraries%2Fnodejs%2Fpresubmit%2Fgoogleapis%2Fnodejs-spanner%2Fnode10%2Fsamples-test/log).

I haven't yet figured out what's going on here. But the failure message from the delete sample test is interesting.

```
AssertionError: expected 'Deleted individual rows in Albums.\n5 records deleted from Singers.\n2 records deleted from Singers.\n0 records deleted from Singers.\n' to include '3 records deleted from Singers.'
```

We are expecting to see `'Deleted individual rows in Albums.\n2 records deleted from Singers.\n3 records deleted from Singers.` in the output.

So we're deleting way more data than is expected in the first request and also executing an extra delete that we expected. It could be that the callback is retried even after it succeeds.
