### ISSUE TITLE
How do I re-use the database connection pool that I already closed?

### ISSUE THREAD

**Issue by voltrue2** [googleapis/nodejs-spanner#117]
Hello,

I have an issue with the following operation, and I cannot seem to find anything related to this issue on online documentation anywhere.
Would you guys mind pointing me to the right direction?

#### Environment details

  - OS: Mac OS high sierra
  - Node.js version: v7.9.0
  - npm version: v4.2.0
  - @google-cloud/spanner version: v0.8.1

#### Steps to reproduce

  1. Execute a select query
  2. Close database by `database.close()`
  3. Create new database by `instance.database('myDatabase')`
  4. Execute another select query with the new database object
  5.  `Error: pool is draining and cannot accept work`

**Comment by callmehiphop** [comment]
@voltrue2 we have since swapped out pooling libraries and refactored a few other items. If possible, could you try upgrading to `1.0.x` to see if that resolves your issue?

**Comment by voltrue2** [comment]
@callmehiphop Any update on this question?

Cheers

**Comment by callmehiphop** [comment]
@voltrue2 I actually haven't been able to reproduce this, even when using your example. I have a hunch why and made a [branch](https://github.com/callmehiphop/nodejs-spanner/blob/dg--117) with a possible fix. Could you test against it to see if it resolves your issue?

**Comment by voltrue2** [comment]
@callmehiphop 
OK I understand. Let me try and see if this makes any difference.

Cheers!

**Comment by voltrue2** [comment]
@callmehiphop I am still in the process of testing the new branch. (My apologies for taking long...)
I have a question, though.
What would be the best practice to manage the connections?

Should I be making the database object per database on starting of the process and re-use them?

```javascript
// we do this ONCE on starting of the process
const spanner = Spanner({ projectId: projectId });
const instance = spanner.instance(instanceId);
const databases = {};
databases.myDb = instance.database('myDb');
databases.hisDb = instance.database('hisDb');
databases.herDb = instance.database('herDb');
// we re-use these and close them on exit of the process...
function onExitProcess() {
  databases.myDb.close();
  databases.hisDb.close();
  databases.herDb.close();
}
```

Or should I be making the database instance every time we need a connection and close it when we are done?

This is much slower for obvious reason of course...

```javascript
function readFromMyDb() {
  var spanner = Spanner({ projectId: projectId });
  var instance = spanner.instance(instanceId);
  var db = instance.database('myDb');
  db.run({ sql: 'xxxx', params: {...} })
  .then(() => {
   // close the connection
    db.close();
   })
  .catch(...);
}
```
Cheers!

**Comment by vkedia** [comment]
You should make the database object just once per database and reuse. That
will be much more peeformant.

**Comment by voltrue2** [comment]
@vkedia 
Thank you! Got it.
By the way, I was able to solve the issue that I initially had with the new branch @callmehiphop gave me.
But now I have this `1 session leak(s) found.` error when I terminate the application process while reading and/or writing rapidly. 
What I do on termination of the process is to call `.close(...)` on all database objects and wait for callbacks, and then terminate the process. 
I was wondering if this is how you terminate all connections to Spanner properly?

Cheers

**Comment by callmehiphop** [comment]
@voltrue2 that error will have a `messages` attribute containing a call stack for each leak found. Usually it means a transaction was started but never finished. I would use the call stack to find the transaction in question to make sure that `end()` is being called for read only transactions and `commit()` is being called for read/write transactions.

**Comment by voltrue2** [comment]
@callmehiphop Great! thank you for the pointer. I will look at my code once again to see where I have missed the end of transaction(s).

Cheers!
