### ISSUE TITLE
ListDatabases unintentionally initializes a session pool for each returned database

### ISSUE THREAD

**Issue by skuruppu** [googleapis/nodejs-spanner#1227]
@larkee pointed out an interesting observation in the Python library if we initialize the session pool with > 0 sessions in the context of `ListDatabses` and I think this might apply in Node.js as well.

1. When we call [`getDatabases`](https://github.com/googleapis/nodejs-spanner/blob/7046d0b22fb1bdf8996887422ec9cf833d38ac37/src/instance.ts#L1135), the [`GetDatabaseResponse`](https://github.com/googleapis/nodejs-spanner/blob/7046d0b22fb1bdf8996887422ec9cf833d38ac37/src/instance.ts#L1153) translates the Database protos into Database objects.
2. Each Database object contains a SessionPool which is initialized in the [constructor](https://github.com/googleapis/nodejs-spanner/blob/7046d0b22fb1bdf8996887422ec9cf833d38ac37/src/database.ts#L366).

Is it an issue that we potentially create lots of sessions unnecessarily for all results of a ListDatabases call?

@olavloite assigning to you since you've looked at the pool implementation more recently.

**Comment by olavloite** [comment]
@skuruppu I can confirm that this problem is also present in the Node.js client library.

**Comment by AVaksman** [comment]
In case the user intends to use the databases for reading/writing data, is it reasonable to add a `min` (or equivalent) parameter to the `getDatabases` function to alleviate the extra latency issue described in #1160?

**Comment by skuruppu** [comment]
@AVaksman, that's good point. But I don't think it's too much of an issue since when the first request is received on a client, the pool will initiate a BatchCreateSessions request to create [25 sessions by default](https://github.com/olavloite/nodejs-spanner/blob/7046d0b22fb1bdf8996887422ec9cf833d38ac37/src/session-pool.ts#L133). So it will delay the first request but not subsequent ones if the user intends to use the databse.
