### ISSUE TITLE
Transaction insert with Spanner.float() failing with 9 FAILED_PRECONDITION: Expected FLOAT64

### ISSUE THREAD

**Issue by gbains8172** [googleapis/nodejs-spanner#1265]
Hello! I get the following error when trying to insert an integer, or any float such as `42.0` or `42.8` into a spanner column of type `FLOAT64` using `Spanner.float()`. Insertion of floats that _do not_ end in `.0` _without_ `Spanner.float()` works.

`9 FAILED_PRECONDITION: Invalid value for column floating in table floatTest: Expected FLOAT64`

I've tested it by creating a table called `floatTest` with one column called `floating` of type `FLOAT64`. The insertion is happening inside a `runTransactionAsync` block.

#### Environment details

  - OS: Mac OS Catalina 10.15.7
  - Node.js version: 10.16.3
  - npm version: 6.14.8
  - `@google-cloud/spanner` version: 5.3.0

#### Steps to reproduce

  1. Insert integer into Spanner table with column type `FLOAT64` using `Spanner.float()`. I've included a script that may provide value:

```
const {Spanner} = require('@google-cloud/spanner');
const spanner = new Spanner();

const instance = spanner.instance('my-instance');
const database = instance.database('my-database');
const tableName = 'floatTest'

await database.runTransactionAsync(async (transaction) => {
  await transaction.insert(tableName, { floating: Spanner.float(42) });
  await transaction.commit();
});
```

**Comment by olavloite** [comment]
@gbains8172 I am not able to reproduce this. Would you mind sharing the entire definition of your `floatTest` table? Does it for example include more columns than just the `floating` column?

**Comment by gbains8172** [comment]
Update: was using a wrapper library that had an older version of spanner that was different from version in my file -> aligning the versions fixed the issue
