### ISSUE TITLE
KeepAlive does not work on SessionPool

### ISSUE THREAD

**Issue by vkedia** [googleapis/nodejs-spanner#13]
cc @lukesneeringer @callmehiphop @stephenplusplus 
I am using the latest version of the node.js client. It seems that KeepAlive logic does not work.
To reproduce I wrote a simple code which set KeepAlive time to 1 minutes and then it makes a single query to ensure that the session is created. After that it just waits for a while on prompt. I would expect that after a few minutes I would see at least some ExecuteSql calls (which is how session is kept alive). I enabled grpc tracing and all I saw was a single CreateSession followed by a single ExecuteStreamingSql (which was due to the query I made) and nothing else.
To reproduce turn on grpc tracing
```
export GRPC_TRACE=http
export GRPC_VERBOSITY=INFO
```

Then run the sample code given below and direct the grpc logs to a file
```
node keepalive.js 2> grpc.log
```

This will make a query and display a prompt. Wait for few minutes and take a look at grpc.log.
This is the code
```

'use strict';
  const Spanner = require('@google-cloud/spanner');
  const spanner = Spanner();
  const instanceId = 'myinstance';
  const databaseId = 'mydb';
  const instance = spanner.instance(instanceId);
  const database = instance.database(databaseId);
  const query = {
    sql: 'SELECT 1 as c'
  };
  database.run(query)
    .then((results) => {
      const rows = results[0];
      rows.forEach((row) => {
        const json = row.toJSON();
        console.log(`${json.c.value}`);
      });
      var prompt = require('prompt');
      prompt.start();
      prompt.get(['done'], function(err, result){
        database.close();
        console.log('Bye');
      });
    });
```

**Comment by vkedia** [comment]
@lukesneeringer Any updates on this? Also an this be treated at a higher priority.

**Comment by callmehiphop** [comment]
@vkedia I'm actively working on changing out our pooling library, which I think will close a number of outstanding bugs.

**Comment by vkedia** [comment]
@callmehiphop  Do you have any ETA for this?

**Comment by callmehiphop** [comment]
@vkedia I should be opening a PR either today or this weekend, hopefully we get it merged in early next week.

**Comment by vkedia** [comment]
That's perfect. Thanks!

**Comment by vkedia** [comment]
Is there a way to fix this with the current pooling library quickly? Because merging the new library would take a while since it is a big change. It will be good to have a fix in the meantime unless it is non trivial.
