### ISSUE TITLE
nodejs-spanner 5.4.0 uses 1.5x (and increasing) memory / call compared to 4.8.0

### ISSUE THREAD

**Issue by hamko** [googleapis/nodejs-spanner#1313]
nodejs-spanner 5.4.0 uses 1.5x memory / call compared to 4.8.0. After 1 hour of 50 QPS write queries in GCF, 4.8.0 used 112 MiB/call but 5.4.0 used 160 MiB/call. Also, for the both versions, the memory / call usage increases gradually within the 1 hour.

I checked memory leak issues, but memory leak bug fix [3] can be found between the versions, and it looks unreasonable to see more memory usage in 5.4.0 than 4.8.0. Our customer is afraid of the memory usage difference and mind upgrading the version to 5.4.0 due to the 1.5x worse memory perfomance.

Questions:

- Why 5.4.0 uses more memory / call than 4.8.0?
- Is it likely to be a memory leak issue, or is it a problem that they don't need to worry about?

[1] memory/call when deployed with nodejs-spanner 4.8.0 ![4.8.0](https://user-images.githubusercontent.com/3013271/109669146-2e3d5300-7bb5-11eb-8bae-ebe9c1ba5998.png)
[2] memory/call when deployed with nodejs-spanner 5.4.0 ![5.4.0](https://user-images.githubusercontent.com/3013271/109669268-4a40f480-7bb5-11eb-8ed8-696fcf3e2727.png)
[3] https://github.com/googleapis/nodejs-spanner/pull/1168

#### Environment details

  - OS: Cloud Function
  - Node.js version: 10
  - npm version:
  - `@google-cloud/spanner` version: 5.4.0

#### Steps to reproduce

  1. `./deploy.sh`
  2. Define the Spanner table TABLE_ID with a string `id` and an int64 `value`.
  3. `./test.sh` for both versions of `package.json`.

deploy.sh
```
#!/bin/bash
set -eu
gcloud beta functions deploy FUNCTION_NAME \
  --project=PROJECT_ID \
  --region=asia-northeast1 \
  --source=. \
  --trigger-http \
  --entry-point=helloWorld \
  --runtime nodejs10
```

test.sh
```
#!/bin/bash

token=$(gcloud auth print-identity-token)
while true; do 
    ab -c 10 -n 50000 -H "Authorization: bearer $token" https://asia-northeast1-PROJECT_ID.cloudfunctions.net/FUNCTION_NAME
done
```

package.json (5.4.0 ver. Replace 5.4.0 for 4.8.0 to test 4.8.0)
```
{
  "name": "aaa",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "dependencies": {
    "@google-cloud/spanner": "^5.4.0",
    "uuid": "^8.0.0"
  },
  "author": "",
  "license": "ISC"
}
```
index.js
```
const projectId = 'PROJECT_ID';
const instanceId = 'INSTANCE_ID';
const databaseId = 'DATABASE_ID';

const {Spanner} = require('@google-cloud/spanner');
const spanner = new Spanner({projectId});
const instance = spanner.instance(instanceId);
const database = instance.database(databaseId);
const table = database.table('TABLE_ID');

const { v4: uuidv4 } = require('uuid');

exports.helloWorld = (async (req, res) => {
  const id = uuidv4();
  await table.insert([{id: id, value: 0}]);
  res.status(200).send(id);
});
```

**Comment by olavloite** [comment]
I've been trying this out with a similar script locally to try to rule out all other external factors, and I cannot reproduce the continuous increase in memory consumption locally. After inserting 25,000 rows the memory consumption remains relatively stable (a total increase of 1MB after 25,000 rows, and the increase is primarily at the beginning).

The results below are with Spanner 5.4.0.

![Memory usage vs Rows](https://user-images.githubusercontent.com/1196707/109844142-22e93680-7c4c-11eb-8340-9cd956bc7c83.png)

My test script:

```typescript
import {Spanner} from "@google-cloud/spanner";

const spanner = new Spanner();
const instance = spanner.instance('my-instance');
const database = instance.database('my-database');
const table = database.table('Singers');

main().then(() => console.log('[INFO] Finished'));

async function main() {
    for (let row = 1; row <= 50000; row++) {
        const newRow = {
            SingerId: getRandomInt(Number.MAX_SAFE_INTEGER),
            FirstName: `FirstName${getRandomInt(Number.MAX_SAFE_INTEGER)}`,
            LastName: `LastName${getRandomInt(Number.MAX_SAFE_INTEGER)}`,
        };
        await table.upsert(newRow);
        if (row % 25 === 0) {
            console.log(`[INFO] Rows updated so far: ${row}`);
            if (global.gc) {
                global.gc();
                const used = process.memoryUsage().heapUsed / 1024 / 1024;
                console.log(`[INFO] Memory usage: ${used} MB`);
            }
        }
    }
}

function getRandomInt(max) {
    return Math.floor(Math.random() * Math.floor(max));
}
```

Output:

```
[INFO] Rows updated so far: 25
[INFO] Memory usage: 16.92938995361328 MB
[INFO] Rows updated so far: 50
[INFO] Memory usage: 16.690399169921875 MB
[INFO] Rows updated so far: 75
[INFO] Memory usage: 16.685577392578125 MB
[INFO] Rows updated so far: 100
[INFO] Memory usage: 16.735137939453125 MB
[INFO] Rows updated so far: 125
[INFO] Memory usage: 16.737327575683594 MB
[INFO] Rows updated so far: 150
[INFO] Memory usage: 16.7418212890625 MB
...
[INFO] Memory usage: 17.87793731689453 MB
[INFO] Rows updated so far: 16150
[INFO] Memory usage: 17.895767211914062 MB
[INFO] Rows updated so far: 16175
[INFO] Memory usage: 17.88404083251953 MB
[INFO] Rows updated so far: 16200
[INFO] Memory usage: 17.877967834472656 MB
[INFO] Rows updated so far: 16225
[INFO] Memory usage: 17.891319274902344 MB
...

[INFO] Rows updated so far: 24875
[INFO] Memory usage: 17.982986450195312 MB
[INFO] Rows updated so far: 24900
[INFO] Memory usage: 17.97265625 MB
[INFO] Rows updated so far: 24925
[INFO] Memory usage: 17.978668212890625 MB
[INFO] Rows updated so far: 24950
[INFO] Memory usage: 17.998985290527344 MB
[INFO] Rows updated so far: 24975
[INFO] Memory usage: 17.992050170898438 MB
[INFO] Rows updated so far: 25000
[INFO] Memory usage: 17.975662231445312 MB
```

**Comment by olavloite** [comment]
I've tried the same script using Cloud Functions as well, but with less concurrency than in the given example. The memory usage seems to be increasing a little bit, but not as much as in your charts.

![Screenshot from 2021-03-03 21-14-27](https://user-images.githubusercontent.com/1196707/109867147-723c6080-7c66-11eb-9881-6547c44ae08f.png)

I could think of one possible explanation for both the increasing memory usage as the script is running, as well as for the increase in base memory usage between 4.8.0 and 5.4.0:
1. The increase in memory usage while running could be that the session pool is still growing. If there happens to be more requests running (partly) in parallel, the pool will need to create additional sessions, which will take up some more memory. This should stabilize after a while.
2. The difference in base memory usage between 4.8.0 and 5.4.0 could be (partly) caused by the default session pool settings that have changed between the two versions. In version 5.2.1 the default minimum number of sessions in the pool was increased from 0 to 25.

You could test if the latter increase indeed was caused by that default setting change by specifying `MinSessions: 0` in the session pool settings like this:

```javascript
const database = instance.database(databaseId, {min: 0});
```

**Comment by skuruppu** [comment]
@hamko do you have any thoughts based on the results that @olavloite mentioned above? Or do you have any more information to help us reproduce what you were seeing?

**Comment by skuruppu** [comment]
Since we haven't heard back in a while, I'll close the issue. But please reopen if and when you have more information so that we can reproduce it.
