### ISSUE TITLE
Read data in parallel is not working

### ISSUE THREAD

**Issue by sudhanshuptl** [googleapis/nodejs-spanner#1316]
Hi,
I was trying to run the example for reading data in parallel: https://cloud.google.com/spanner/docs/reads#read_data_in_parallel

But the nodejs version of code is failing up with an error 
`TypeError: Cannot read property 'request' of undefined
    at new Snapshot (/Users/sudhanshupatel/Documents/Dream11/node_modules/@google-cloud/spanner/build/src/transaction.js:133:32)
    at new BatchTransaction (/Users/sudhanshupatel/Documents/Dream11/node_modules/@google-cloud/spanner/build/src/batch-transaction.js:34:1)
    at Database.batchTransaction (/Users/sudhanshupatel/Documents/Dream11/node_modules/@google-cloud/spanner/build/src/database.js:271:29)`
    
  Failed Statement is : `const transaction = database.batchTransaction(identifier)`

#### Environment details

  - OS: MacOs 11.2.1
  - Node.js : v12.18.4
  - npm version:6.14.6
  - `@google-cloud/spanner` version: 5.5.0

#### Steps to reproduce

  1. Copy the code for creating the partition  https://cloud.google.com/spanner/docs/reads#read_data_in_parallel
  2. execute it.

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by skuruppu** [comment]
Thanks for the report @sudhanshuptl. I think I found the issue which is that we're not actually creating the batched transaction. I need to do a bunch of tests, etc. before I can merge a fix. But in the meantime, this is roughly the code that you can use to create a partition and execute it.

```
  // Gets a reference to a Cloud Spanner instance and database
  const instance = spanner.instance(instanceId);
  const database = instance.database(databaseId);
  const [transaction] = await database.createBatchTransaction();

  const query = 'SELECT * FROM Singers';

  const [partitions] = await transaction.createQueryPartitions(query);
  console.log(`Successfully created ${partitions.length} query partitions.`);

  const [rows] = await transaction.execute(partitions[0]);
  console.log(`Successfully received ${rows.length} from executed partition.`);
```

**Comment by sudhanshuptl** [comment]
This is what worked for me.

```
        let result =  await database.createBatchTransaction()
        identifier = result[0].identifier()
        console.log(identifier)
        
        const transaction = database.batchTransaction(identifier);
    
        const query = 'select * from UserRoundTeamCount';
    
        const [partitions] = await transaction.createQueryPartitions(query);
        console.log(`Successfully created ${partitions.length} query partitions.`);
        ```

**Comment by skuruppu** [comment]
Yup, that also works. Essentially, that's how the [tests](https://github.com/googleapis/nodejs-spanner/blob/master/samples/system-test/spanner.test.js#L425-L437) for that sample were written which is why we never really caught the problem that it wouldn't actually run with a `"{}"` identifier.

**Comment by skuruppu** [comment]
I also missed it in my original code snippet, but it's also a good idea to close the transaction when you're done so that the session can be released back into the pool.
