### ISSUE TITLE
triggers unhandled promise rejection that we cannot prevent

### ISSUE THREAD

**Issue by gsouf** [googleapis/nodejs-spanner#1319]
#### Environment details

  - OS: linux
  - Node.js version: 10
  - npm version: 7
  - `@google-cloud/spanner` version: 5.5.0

#### Steps to reproduce

Create this js file and run it (no need for a spanner instance to be setup).

This sample will try to connect to spanner with an unexisting instance name just because it's simpler to simulate the error this way, but  it seems to occur with any error.. It will result in an error when doing the insert. The error will be caught in the catch statement, but it will also throw an unhandled promise rejection. The promise rejection that cannot be caught without `unhandledRejection` event is not a desired behavior for a 3rd party library.

```
const {Spanner} = require("@google-cloud/spanner");

run();

async function run() {
    try {
        const spanner = new Spanner({
            projectId: 'somebrokenprojectid',
        });

        const instance = spanner.instance("somebrokeninstance");
        const database = instance.database("somedb");

        const table =  database.table("sometable");

        console.log('insert data');

        await table.insert([{somekey: "somevalue"}]);
    } catch (e) {
        console.error('caught exception', e.message)
    }
}
```

Thanks

**Comment by skuruppu** [comment]
@AVaksman would you please be able to take a look?

**Comment by skuruppu** [comment]
@AVaksman friendly ping on this issue.

**Comment by AVaksman** [comment]
@gsouf  We a discussing a couple of ways of solving the reported issue.
Could you please share the unhandled promise rejection error message you are experiencing.

**Comment by gsouf** [comment]
Hi @AVaksman thanks for looking into this issues.

With the code from the example in my initial message I get this error:

```
caught exception 7 PERMISSION_DENIED: Caller is missing IAM permission spanner.sessions.create on resource projects/somebrokenprojectid/instances/somebrokeninstance/databases/somedb.
(node:354) UnhandledPromiseRejectionWarning: Error: 7 PERMISSION_DENIED: Caller is missing IAM permission spanner.sessions.create on resource projects/somebrokenprojectid/instances/somebrokeninstance/databases/somedb.
    at Object.callErrorFromStatus ([...]/node_modules/@grpc/grpc-js/build/src/call.js:31:26)
    at Object.onReceiveStatus ([...]/node_modules/@grpc/grpc-js/build/src/client.js:176:52)
    at listener.onReceiveStatus ([...]/node_modules/@grpc/grpc-js/build/src/call-stream.js:65:35)
    at Object.onReceiveStatus ([...]/node_modules/grpc-gcp/build/src/index.js:73:29)
    at InterceptingListenerImpl.onReceiveStatus ([...]/node_modules/@grpc/grpc-js/build/src/call-stream.js:60:23)
    at Object.onReceiveStatus ([...]/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:336:141)
    at Object.onReceiveStatus ([...]/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:299:181)
    at process.nextTick ([...]/node_modules/@grpc/grpc-js/build/src/call-stream.js:130:78)
    at process._tickCallback (internal/process/next_tick.js:61:11)
(node:354) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:354) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

But maybe I went astray because I cannot reproduce the unhandled rejection in other cases, so maybe this does not occur everytime as I thought at first. I'll provide feedback if I can reproduce it again

**Comment by AVaksman** [comment]
Currently API optimizes the performance for the most commonly used workflow,  which is 
  initialize spanner client -> create instance object -> create database object -> write or read data.

In the workflow above API will try to pre-fill a session-pool at a point of database object initialization to provide maximum performance with the very first data read/write.

`PERMISSION_DENIED` is thrown due to `"somebrokenprojectid"` doesn't exist.

The workaround for the your sample would be not to create any session with database object initialization. It could be done by passing `{min: 0}` as `SessionPoolOptions` argument. This way the error will be caught in the catch statement.

```ts
const {Spanner} = require("@google-cloud/spanner");

run();

async function run() {
    try {
        const spanner = new Spanner({
            projectId: 'somebrokenprojectid',
        });

        const instance = spanner.instance("somebrokeninstance");
        const database = instance.database("somedb", {min: 0});

        const table =  database.table("sometable");

        console.log('insert data');

        await table.insert([{somekey: "somevalue"}]);
    } catch (e) {
        console.error('caught exception', e.message)
    }
}
```

**Comment by skuruppu** [comment]
@gsouf I think it would mean that the first batch of sessions are created when executing the first request so there will be a small increase in latency for the first request. But sessions are created in batches so for subsequent requests, it shouldn't be an issue.

In any case, #1332 will handle the specific case you came across in your first comment so you won't need to use `{min: 0}`.

**Comment by AVaksman** [comment]
> @AVaksman is that going to decrease performances of the connection?

Exactly as @skuruppu explained, now that #1332 is merged, there is no need for workaround anymore. 
The only time the first query will have increase in latency is if at the time of `const database = instance.database("somedb");` is executed the project, instance or database does not exist.
