### ISSUE TITLE
Project ID placeholder in `google_cloud_resource_prefix` header not always replaced

### ISSUE THREAD

**Issue by larkee** [googleapis/nodejs-spanner#1375]
The project ID placeholder used in the `google_cloud_resource_prefix` header is sometimes not being replaced for data client methods leading to `google_cloud_resource_prefix` headers in the following form: 
```
projects/{{projectId}}/instances/<instanceId>/databases/<databaseId>
```

This placeholder should always be replaced with the project ID.

Note: This does not seem to be tied to a particular version of this client, `gax`, `gapic` or `gccl`.

**Comment by skuruppu** [comment]
This is a sample of the header, methods and the client versions for the malformed  header. Note that most of these entries have an actual valid project number associated with the request.

There are also heaps of other entries (not included in this sample) where {{projectId}} is populated correctly.

google_cloud_resource_prefix | Method | Client
-- | -- | --
projects/{{projectId}}/instances/\<redacted\>/databases/\<redacted\> | google.spanner.v1.Spanner.Commit | gax/2.12.0 gapic/5.7.0 gl-node/12.19.0 grpc/ gccl/5.7.0
projects/{{projectId}}/instances/\<redacted\>/databases/\<redacted\> | google.spanner.v1.Spanner.ExecuteStreamingSql | gax/2.13.0 gapic/5.4.0 gl-node/12.22.1 grpc/ gccl/5.4.0
projects/{{projectId}}/instances/\<redacted\>/databases/\<redacted\> | google.spanner.v1.Spanner.BatchCreateSessions | gax/2.15.0 gapic/5.9.0 gl-node/14.15.1 grpc/ gccl/5.9.0
projects/{{projectId}}/instances/\<redacted\>/databases/\<redacted\> | google.spanner.admin.database.v1.DatabaseAdmin.GetDatabase | gax/2.11.2 gapic/5.7.0 gl-node/14.15.4 grpc/ gccl/5.7.0
projects/{{projectId}}/instances/\<redacted\>/databases/\<redacted\> | google.spanner.v1.Spanner.Commit | gax/2.14.1 gapic/5.7.0 gl-node/12.22.1 grpc/ gccl/5.7.0
projects/{{projectId}}/instances/\<redacted\>/databases/\<redacted\> | google.spanner.v1.Spanner.Commit | gax/2.9.2 gapic/5.7.0 gl-node/12.19.0 grpc/ gccl/5.7.0
projects/{{projectId}}/instances/\<redacted\>/databases/\<redacted\> | google.spanner.v1.Spanner.BatchCreateSessions | gax/2.16.0 gapic/5.9.0 gl-node/12.22.1 grpc/ gccl/5.9.0
projects/{{projectId}}/instances/\<redacted\>/databases/\<redacted\> | google.spanner.v1.Spanner.ExecuteStreamingSql | gax/2.14.1 gapic/5.7.0 gl-node/14.17.0 grpc/ gccl/5.7.0
projects/{{projectId}}/instances/\<redacted\>/databases/\<redacted\> | google.spanner.v1.Spanner.Commit | gax/2.11.2 gapic/5.6.1 gl-node/12.22.1 grpc/ gccl/5.6.1
projects/{{projectId}}/instances/\<redacted\>/databases/\<redacted\> | google.spanner.v1.Spanner.Commit | gax/2.16.0 gapic/5.9.0 gl-node/12.22.1 grpc/ gccl/5.9.0
projects/{{projectId}}/instances/\<redacted\>/databases/\<redacted\> | google.spanner.v1.Spanner.ExecuteSql | gax/2.10.0 gapic/5.3.0 gl-node/10.23.1 grpc/ gccl/5.3.0
projects/{{projectId}}/instances/\<redacted\>/databases/\<redacted\> | google.spanner.v1.Spanner.ExecuteSql | gax/2.12.0 gapic/5.7.0 gl-node/14.15.4 grpc/ gccl/5.7.0
projects/{{projectId}}/instances/\<redacted\>/databases/\<redacted\> | google.spanner.v1.Spanner.BeginTransaction | gax/2.14.1 gapic/5.7.0 gl-node/12.22.1 grpc/ gccl/5.7.0
projects/{{projectId}}/instances/\<redacted\>/databases/\<redacted\> | google.spanner.v1.Spanner.BeginTransaction | gax/2.11.2 gapic/5.7.0 gl-node/14.15.4 grpc/ gccl/5.7.0
projects/{{projectId}}/instances/\<redacted\>/databases/\<redacted\> | google.spanner.v1.Spanner.ExecuteSql | gax/2.11.2 gapic/5.7.0 gl-node/14.15.4 grpc/ gccl/5.7.0
projects/{{projectId}}/instances/\<redacted\>/databases/\<redacted\> | google.spanner.v1.Spanner.BatchCreateSessions | gax/2.9.2 gapic/5.4.0 gl-node/10.24.0 grpc/ gccl/5.4.0
projects/{{projectId}}/instances/\<redacted\>/databases/\<redacted\> | google.spanner.v1.Spanner.Commit | gax/2.15.1 gapic/5.9.0 gl-node/12.20.0 grpc/ gccl/5.9.0
projects/{{projectId}}/instances/\<redacted\>/databases/\<redacted\> | google.spanner.admin.database.v1.DatabaseAdmin.GetDatabase | gax/2.10.2 gapic/5.4.0 gl-node/14.8.0 grpc/ gccl/5.4.0
projects/{{projectId}}/instances/\<redacted\>/databases/\<redacted\> | google.spanner.v1.Spanner.ExecuteStreamingSql | gax/2.9.2 gapic/5.3.0 gl-node/12.18.4 grpc/ gccl/5.3.0
projects/{{projectId}}/instances/\<redacted\>/databases/\<redacted\> | google.spanner.v1.Spanner.ExecuteSql | gax/2.8.0 gapic/5.3.0 gl-node/12.15.0 grpc/ gccl/5.3.0

**Comment by skuruppu** [comment]
@olavloite if you have some spare cycles, would you be able to take a quick look at what's going on here. It's not super urgent so I'll downgrade the priority.
