### ISSUE TITLE
YCSB benchmark hangs up with workload b

### ISSUE THREAD

**Issue by vkedia** [googleapis/nodejs-spanner#139]
@haih-g was trying to run the benchmark with workload b (50% read and 50% update) with operation count=50000. But the benchmark did not finish even after 1 hour and CPU usage was 100%.

**Comment by walshie4** [comment]
Has there been any progress on this?  I've seen similar things in our usage (certain larger writes or reads never return), and this sounds concerning for the backing of a production application.
