### ISSUE TITLE
Error: Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential

### ISSUE THREAD

**Issue by hugoluchessi** [googleapis/nodejs-spanner#143]
Hi, this errors has being occurring intermittently on my Cloud Function using Spanner.

The thing is that this error never occured until yesterday (march 5th, 4:09PM -3:00).

Could you please help me to workaround this issue?

#### Environment details

  - OS: Google Cloud Functions
  - Node.js version: -
  - npm version: -
  - @google-cloud/spanner version:  ^1.0.2

#### Steps to reproduce
Not deterministic

**Comment by hugoluchessi** [comment]
I've jsut updated spanner client version to "^1.1.0" to check if it solves the issue.

But as no new releases has been released yesterday regarding spanner or auth, I'm skeptic this will work.

**Comment by stephenplusplus** [comment]
Interesting. We did recently upgrade the auth layer, [`google-auth-library`](https://gitnpm.com/google-auth-library).

Tagging a related issue: https://github.com/google/google-auth-library-nodejs/issues/168

What version were you using before, when the error started?

**Comment by hugoluchessi** [comment]
I was using ^1.0.2 for some weeks already and no errors of this kind were noticed before yesterday.

I didn't change any code yesterday, I have just updated the versions (30 minutes ago).

**Comment by stephenplusplus** [comment]
This is going to be a hard one to attempt to reproduce. Could you work up any more details about the calls you're making that might lead to this error? If we're still stuck with only this error to go by, I'll move this over to the auth repo, to see if that team can come up with anything.

One thing that might help, if you're not already doing it. Instantiate the Spanner client inside of the exported GCF function, itself, i.e.

```diff
const Spanner = require('@google-cloud/spanner')
- const spanner = new Spanner()

module.exports.fn = () => {
+  const spanner = new Spanner()
}
```

**Comment by stephenplusplus** [comment]
Hey @hugoluchessi, just wanted to check in for any updates you might have before I move this over.

**Comment by stephenplusplus** [comment]
This issue was moved to https://github.com/google/google-auth-library-nodejs/issues/334.

**Comment by hugoluchessi** [comment]
Sorry for the late response.

But this issue can remain closed, I've updated all dependencies on my project and this issue didn't happen anymore.

Thanks for the help.
