### ISSUE TITLE
Update to the documentation regarding handling of numbers

### ISSUE THREAD

**Issue by flovouin** [googleapis/nodejs-spanner#1461]
**Is your feature request related to a problem? Please describe.**
I recently got an error while inserting a `FLOAT64` value using a raw `number` with no fractional part into Spanner. It took me a while to realise that it was related to issues that have been raised in the past:
https://github.com/googleapis/nodejs-spanner/issues/764
https://github.com/googleapis/google-cloud-node/issues/2307
https://github.com/googleapis/google-cloud-node/issues/2873
https://github.com/googleapis/nodejs-spanner/issues/388

 **Describe the solution you'd like**
While I understand why this happens and that the NodeJS client can't really do that in any other way, it would be nice to have a bit more documentation around number wrapping with `Int` and `Float`. There has been [another issue in the past](https://github.com/googleapis/nodejs-spanner/issues/22), but I don't think it really addresses this. The entire [sample about datatypes](https://github.com/googleapis/nodejs-spanner/blob/master/samples/datatypes.js) makes no mention of the wrapper classes. [There is even a note](https://github.com/googleapis/nodejs-spanner/blob/master/samples/datatypes.js#L93) that doesn't really describe the client's behaviour (`number`s aren't always treated as `FLOAT64`, which is the reason why I got an error in the first place).
I'd argue that the wrapper classes should be presented in those "getting started" samples, as they quickly become necessary to actually use the package in real use cases.

 **Describe alternatives you've considered**
Not opening this issue. 😄

**Comment by skuruppu** [comment]
Thanks a lot @flovouin for this idea. It totally makes sense that we need to explicitly show that we have the wrapper classes. Especially making sure that the code samples show how to use this where possible (e.g. `MarketingBudget` [here](https://cloud.google.com/spanner/docs/getting-started/nodejs#write_data_to_the_new_column)).

**Comment by asthamohta** [comment]
Hi @flovouin,
thanks for the suggestion. We have added the change in the following PR:
github.com/googleapis/nodejs-spanner/pull/1482
