### ISSUE TITLE
The memory usage seems increasing when the table.insert() error occurs

### ISSUE THREAD

**Issue by junichi-tanaka** [googleapis/nodejs-spanner#1462]
I am the original reporter of issue #1313.
Unfortunately, I'm still facing with the issue.
The cause of the problem seemed to be somewhere else, and I was able to reproduce it, so I'd like you to check it out.

As olavloite mentioned in #1313, the memory usage is stable in his script. https://github.com/googleapis/nodejs-spanner/issues/1313#issuecomment-790019913
However, it seems to be leaking slightly when table.insert() throws an error.
I think this is the root cause of our problem.

The results below are with table.upsert()
![image](https://user-images.githubusercontent.com/678655/131481170-4372f314-87e2-4226-92ba-e94a76586bd6.png)

The results below are with table.insert() causes an error
![image](https://user-images.githubusercontent.com/678655/131481260-682b75a1-ab81-47c2-8020-e9fc5b1dcf46.png)

#### Environment details

  - OS: macOS
  - Node.js version: v14.17.1
  - npm version: 7.20.5
  - `@google-cloud/spanner` version: 5.13.1

#### Steps to reproduce

  1. Causing an error in table.insert()
  2. repeat, repeat and repeat

My test script:

```javascript
const {Spanner} = require('@google-cloud/spanner');

const spanner = new Spanner();
const instance = spanner.instance('my-instance');
const database = instance.database('my-database');
const table = database.table('Singers');

main().then(() => console.log('[INFO] Finished'));

async function main() {
    for (let row = 1; row <= 50000; row++) {
        const newRow = {
            SingerId: 1,
            FirstName: 'firstname',
            LastName: 'lastname',
        };
        //await table.upsert(newRow);
        try {
          await table.insert(newRow);
        } catch(err) {
          if (err.code != 6) {    // ignore grpc AlreadyExists
            throw err;
          }
        }
        if (row % 25 === 0) {
            console.log(`[INFO] Rows updated so far: ${row}`);
            if (global.gc) {
                global.gc();
                const used = process.memoryUsage().heapUsed / 1024 / 1024;
                console.log(`[INFO] Memory usage: ${used} MB`);
            }
        }
    }
}
```

Output(with table.upsert()):
```
[INFO] Rows updated so far: 25
[INFO] Memory usage: 17.850181579589844 MB
[INFO] Rows updated so far: 50
[INFO] Memory usage: 17.832420349121094 MB
[INFO] Rows updated so far: 75
[INFO] Memory usage: 17.85736846923828 MB
[INFO] Rows updated so far: 100
[INFO] Memory usage: 17.891868591308594 MB
[INFO] Rows updated so far: 125
[INFO] Memory usage: 17.89563751220703 MB
[INFO] Rows updated so far: 150
[INFO] Memory usage: 17.9027099609375 MB
...
[INFO] Rows updated so far: 16150
[INFO] Memory usage: 18.864845275878906 MB
[INFO] Rows updated so far: 16175
[INFO] Memory usage: 18.887779235839844 MB
[INFO] Rows updated so far: 16200
[INFO] Memory usage: 18.87274932861328 MB
[INFO] Rows updated so far: 16225
[INFO] Memory usage: 18.86701202392578 MB
...
[INFO] Memory usage: 18.895301818847656 MB
[INFO] Rows updated so far: 49925
[INFO] Memory usage: 18.900909423828125 MB
[INFO] Rows updated so far: 49950
[INFO] Memory usage: 18.90435028076172 MB
[INFO] Rows updated so far: 49975
[INFO] Memory usage: 18.941001892089844 MB
[INFO] Rows updated so far: 50000
[INFO] Memory usage: 18.904075622558594 MB
```

Output(with table.insert() causes an error):
```
[INFO] Rows updated so far: 25
[INFO] Memory usage: 17.84894561767578 MB
[INFO] Rows updated so far: 50
[INFO] Memory usage: 17.83715057373047 MB
[INFO] Rows updated so far: 75
[INFO] Memory usage: 17.863059997558594 MB
[INFO] Rows updated so far: 100
[INFO] Memory usage: 17.921218872070312 MB
[INFO] Rows updated so far: 125
[INFO] Memory usage: 17.93242645263672 MB
[INFO] Rows updated so far: 150
[INFO] Memory usage: 17.938697814941406 MB
...
[INFO] Rows updated so far: 16150
[INFO] Memory usage: 20.609634399414062 MB
[INFO] Rows updated so far: 16175
[INFO] Memory usage: 20.611862182617188 MB
[INFO] Rows updated so far: 16200
[INFO] Memory usage: 20.61297607421875 MB
[INFO] Rows updated so far: 16225
[INFO] Memory usage: 20.616310119628906 MB
[INFO] Rows updated so far: 16250
[INFO] Memory usage: 20.620315551757812 MB
...
[INFO] Memory usage: 23.255882263183594 MB
[INFO] Rows updated so far: 49925
[INFO] Memory usage: 23.259368896484375 MB
[INFO] Rows updated so far: 49950
[INFO] Memory usage: 23.264991760253906 MB
[INFO] Rows updated so far: 49975
[INFO] Memory usage: 23.25994873046875 MB
[INFO] Rows updated so far: 50000
[INFO] Memory usage: 23.261062622070312 MB
```

**Comment by olavloite** [comment]
I've tried a number of things to reproduce this, and it seems that it really needs a very high write rate with errors in order to occur. When executing the test script from my local laptop against a Spanner instance that is physically far away (which means that the QPS is lower, as the latency is slowing the script down), the problem is not really measurable. The additional memory usage after inserting 50,000 rows is less than 2MB.

## Production

### Insert on production (error)

```
[INFO] Rows updated so far: 49850
[INFO] Memory usage: 20.891639709472656 MB
[INFO] Rows updated so far: 49875
[INFO] Memory usage: 20.892547607421875 MB
[INFO] Rows updated so far: 49900
[INFO] Memory usage: 20.891639709472656 MB
[INFO] Rows updated so far: 49925
[INFO] Memory usage: 20.897918701171875 MB
[INFO] Rows updated so far: 49950
[INFO] Memory usage: 20.894447326660156 MB
[INFO] Rows updated so far: 49975
[INFO] Memory usage: 20.892654418945312 MB
[INFO] Rows updated so far: 50000
[INFO] Memory usage: 20.892654418945312 MB
[INFO] Finished
```

### Upsert on production (no error)

```
[INFO] Memory usage: 19.200950622558594 MB
[INFO] Rows updated so far: 49825
[INFO] Memory usage: 19.177757263183594 MB
[INFO] Rows updated so far: 49850
[INFO] Memory usage: 19.200660705566406 MB
[INFO] Rows updated so far: 49875
[INFO] Memory usage: 19.1766357421875 MB
[INFO] Rows updated so far: 49900
[INFO] Memory usage: 19.230911254882812 MB
[INFO] Rows updated so far: 49925
[INFO] Memory usage: 19.196258544921875 MB
[INFO] Rows updated so far: 49950
[INFO] Memory usage: 19.18877410888672 MB
[INFO] Rows updated so far: 49975
[INFO] Memory usage: 19.18383026123047 MB
[INFO] Rows updated so far: 50000
[INFO] Memory usage: 19.174461364746094 MB
[INFO] Finished
```

## Emulator

If I however execute the same test script against a local emulator, the difference is a lot bigger.

### Insert on emulator (error)

The script crashes the emulator after approximately 27.000 rows:

```
[INFO] Rows updated so far: 26825
[INFO] Memory usage: 29.736587524414062 MB
[INFO] Rows updated so far: 26850
[INFO] Memory usage: 29.741195678710938 MB
[INFO] Rows updated so far: 26875
[INFO] Memory usage: 29.751495361328125 MB
[INFO] Rows updated so far: 26900
[INFO] Memory usage: 29.759002685546875 MB
[INFO] Rows updated so far: 26925
[INFO] Memory usage: 29.768943786621094 MB
[INFO] Rows updated so far: 26950
[INFO] Memory usage: 29.77741241455078 MB
[INFO] Rows updated so far: 26975
[INFO] Memory usage: 29.781410217285156 MB
[INFO] Rows updated so far: 27000
[INFO] Memory usage: 29.79412841796875 MB
```

### Upsert on emulator (no error)

```
```

**Comment by junichi-tanaka** [comment]
Thank you for the confirming.

As you said, the test script is for reproducing the problem, so it is slightly different from the actual situation.
I thought it would be easier to identify the problem if the difference was a little.

My actual production case is below
 Environment details

    OS: Cloud Functions(Background Functions)
    Node.js version: v10
    npm version: -
    @google-cloud/spanner version: 5.13.1
          currently using v4.8.0 and want to upgrade to v5.x

- from PubSub
  - (at the first request only) load master data
  - validate and transform the payload
  - insert to Cloud Spanner

It is processing about 50rps - 400rps, and most of the inserts are successful, some already exist, but they are ignored.

Here's the memory util of deploying my Cloud Functions with v5.13.1 last month.
![Per_call_memory__1_](https://user-images.githubusercontent.com/678655/131781680-e1c7d3f2-0fb1-41c1-b972-472295d4c587.png)

And, I've tried the delay.
It seems to be better than before, but compared to upsert, it seems to be a bit large, but it may be necessary to handle the error.
![image](https://user-images.githubusercontent.com/678655/131782101-149e7f2a-486c-405d-8386-84ec36d5d0c5.png)

```
[INFO] Rows updated so far: 25
[INFO] Memory usage: 17.821739196777344 MB
[INFO] Rows updated so far: 50
[INFO] Memory usage: 17.807220458984375 MB
[INFO] Rows updated so far: 75
[INFO] Memory usage: 17.830421447753906 MB
[INFO] Rows updated so far: 100
[INFO] Memory usage: 17.859130859375 MB
[INFO] Rows updated so far: 125
[INFO] Memory usage: 17.904800415039062 MB
...
[INFO] Rows updated so far: 49900
[INFO] Memory usage: 19.44976806640625 MB
[INFO] Rows updated so far: 49925
[INFO] Memory usage: 19.43445587158203 MB
[INFO] Rows updated so far: 49950
[INFO] Memory usage: 19.435562133789062 MB
[INFO] Rows updated so far: 49975
[INFO] Memory usage: 19.43604278564453 MB
[INFO] Rows updated so far: 50000
[INFO] Memory usage: 19.435630798339844 MB
[INFO] Finished
```

I would like to implement the measures you taught us into our real function and try them out!

**Comment by olavloite** [comment]
@junichi-tanaka I've been trying to pinpoint where this behavior is coming from, and I think I have found a possible cause. Disabling the grpc-gcp configuration for the Spanner client seems to solve the additional memory usage at least in the test script that we are using. For me locally, disabling the configuration makes the memory usage of the insert test script equal to that of the upsert test script.

Would it be possible for you to either:
1. Try out a custom build of the Spanner client based on #1463, and then use the `SPANNER_DISABLE_GCP` environment variable to enable/disable the grpc-gcp configuration.
2. Or: Just manually edit the `index.js` file in your local `node_modules/@google-cloud/spanner/build/src/` directory. You can safely disable the grpc-gcp configuration by commenting out the three lines that read:

```javascript
                'grpc.callInvocationTransformer': grpcGcp.gcpCallInvocationTransformer,
                'grpc.channelFactoryOverride': grpcGcp.gcpChannelFactoryOverride,
                'grpc.gcpApiConfig': grpcGcp.createGcpApiConfig(gcpApiConfig),
```

These are the three lines directly following the `// Enable grpc-gcp support` comment at lines 105-107 in my local build. The piece of code would then look like this:

```javascript
        options = Object.assign({
            libName: 'gccl',
            libVersion: require('../../package.json').version,
            scopes,
            // Enable grpc-gcp support
            // 'grpc.callInvocationTransformer': grpcGcp.gcpCallInvocationTransformer,
            // 'grpc.channelFactoryOverride': grpcGcp.gcpChannelFactoryOverride,
            // 'grpc.gcpApiConfig': grpcGcp.createGcpApiConfig(gcpApiConfig),
            grpc: google_gax_1.grpc,
        }, options || {});
```

**Comment by junichi-tanaka** [comment]
I've tried it by changing the package.json as follows.
```javascript
  "dependencies": {
    "@google-cloud/spanner": "https://github.com/googleapis/nodejs-spanner.git#disable-gcp"
  },
```
The result looks good.
```
[INFO] Rows updated so far: 25
[INFO] Memory usage: 18.04267120361328 MB
[INFO] Rows updated so far: 50
[INFO] Memory usage: 18.0262451171875 MB
[INFO] Rows updated so far: 75
[INFO] Memory usage: 18.05048370361328 MB
[INFO] Rows updated so far: 100
[INFO] Memory usage: 18.074417114257812 MB
[INFO] Rows updated so far: 125
[INFO] Memory usage: 18.08667755126953 MB
...
[INFO] Rows updated so far: 29150
[INFO] Memory usage: 19.329788208007812 MB
[INFO] Rows updated so far: 29175
[INFO] Memory usage: 19.331390380859375 MB
[INFO] Rows updated so far: 29200
[INFO] Memory usage: 19.329681396484375 MB
[INFO] Rows updated so far: 29225
[INFO] Memory usage: 19.336868286132812 MB
[INFO] Rows updated so far: 29250
[INFO] Memory usage: 19.338577270507812 MB
...
[INFO] Rows updated so far: 49900
[INFO] Memory usage: 19.340721130371094 MB
[INFO] Rows updated so far: 49925
[INFO] Memory usage: 19.340721130371094 MB
[INFO] Rows updated so far: 49950
[INFO] Memory usage: 19.343482971191406 MB
[INFO] Rows updated so far: 49975
[INFO] Memory usage: 19.340721130371094 MB
[INFO] Rows updated so far: 50000
[INFO] Memory usage: 19.340721130371094 MB
[INFO] Finished
```

Then, I've also tried it on the Cloud Functions.

```javascript
const {Spanner} = require('@google-cloud/spanner');
const spanner = new Spanner();
const instance = spanner.instance('my-instance');
const database = instance.database('my-database');
const table = database.table('Singers');

exports.subscribe = async (data, context) => {
    const newRow = {
        SingerId: 1,
        FirstName: 'firstname',
        LastName: 'lastname',
    };
    try {
        await table.insert(newRow);
    } catch(err) {
    }
    console.log(JSON.stringify(process.memoryUsage()));
};
```

```
gcloud beta functions deploy my-gcf-name \
  --project=my-project \
  --region=asia-northeast1 \
  --source=my-source-directory \
  --trigger-topic=my-topic \
  --entry-point=subscribe \
  --runtime=nodejs14 \
  --memory=512MB \
  --set-env-vars SPANNER_DISABLE_GCP=true
```

It looks good, but I would like to test it for a long time.
![Per call memory](https://user-images.githubusercontent.com/678655/131988110-246940c6-d213-449d-94b3-2d1da6f33559.png)

However, when I set the max instance to 1, the memory util kept increasing, which is a bit worrisome.
![Per call memory](https://user-images.githubusercontent.com/678655/131987112-e2e05846-93b1-4b45-b50d-de667036be75.png)

Next, I'll try it with my actual Cloud Functions.

**Comment by olavloite** [comment]
@junichi-tanaka Thanks for the quick update. 

> ... when I set the max instance to 1 ...

Just to be sure: That means that you configure max 1 Cloud Functions instance (and not 1 Spanner instance, or max 1 session), right?

Could it be that the graph you are seeing in that case is just a question of an instance that is receiving heavy load, and therefore has no time to do incremental garbage collections, until it does a major one?

**Comment by junichi-tanaka** [comment]
> Just to be sure: That means that you configure max 1 Cloud Functions instance (and not 1 Spanner instance, or max 1 session), right?

Yes. It means `gcloud functions deploy ... --max-instances=1`.
 
> Could it be that the graph you are seeing in that case is just a question of an instance that is receiving heavy load, and therefore has no time to do incremental garbage collections, until it does a major one?

There is an error below.
I think it's not garbage collections, but the instance of Cloud Functions restarted due to the error.

```
$ gcloud functions logs read my-function-name --start-time="2021-09-03T03:00:00Z" --min-log-level=error --region=asia-northeast1
LEVEL  NAME                    EXECUTION_ID  TIME_UTC                 LOG
E      my-functions-name       8rx60hamh30j  2021-09-03 03:14:52.651  Function invocation was interrupted. Error: memory limit exceeded.
```

As you said, it seems to work well if there are enough instances, so I will check this with our actual work load.

**Comment by junichi-tanaka** [comment]
@olavloite 

Let me share you our updates.

First.
Unfortunately, that patch did not solve our problem.
I'm sorry you had to go through all this.
<img width="1058" alt="cloudfunctions-memory-util-1" src="https://user-images.githubusercontent.com/678655/133011878-457819a9-c6e2-4078-aede-bb565e159fff.png">

The number of active instances increased or decreased, but the increase in memory utilization did not change.

Next.
I dug into the problem with max-instance=1.
This is because I thought that a situation like max-instance=1, where the PubSub is clogged with messages, would happen quite easily.

I found two workarounds below.

1. Set writes in SessionPoolOptions to non-zero.
2. Query `SELECT 1` after a mutation operation.

Both of these seem to affect the session pool, but I haven't investigated the cause in detail.
I didn't pay attention to this because I thought we were only using one session per instance.

Currently, I am working with workaround-1 to continue verification.

```javascript
const database = instance.database(databaseId, { min: 10, max: 20, incStep: 2, writes: 0.5, concurrency: 1, fail: true });
```
In my case, it seems better to have more than 2 readwrite sessions.

<img width="1060" alt="cloudfunctions-memory-util-2" src="https://user-images.githubusercontent.com/678655/133012069-fafadd34-e02d-402e-b6be-487aa0f4e6fa.png">

On more thing.
There is another small problem.

Database.runTransaction(), but it seems that release() is sometimes executed with a slight delay.
However, this happens even before v5.x, so it doesn't seem to be a big problem.
I think it is not good on serverless environment.
If necessary, I would replace it with runTransactionAsync() like below.

```javascript
//await table.upsert(newRow);
await database.runTransactionAsync(async transaction => {
    await transaction.upsert(tableName, newRow);
    await transaction.commit();
});
```

That is all of the update for now.
I'll continue to verification with that workarounds.

Thanks

**Comment by junichi-tanaka** [comment]
Today, I deployed our functions with `nodejs-spanner` v5.x to our production environment.
The session pool settings are as same as my previous comment.
```javascript
const database = instance.database(databaseId, { min: 10, max: 20, incStep: 2, writes: 0.5, concurrency: 1, fail: true });
```

The results are as shown in the image below, and it looks good, with no trend of increasing memory utilization.
![Per_call_memory20211004](https://user-images.githubusercontent.com/678655/135815100-c03f8e63-146d-4b37-a946-d825d4b1d68b.png)
<img width="1397" alt="Cloud_Functions" src="https://user-images.githubusercontent.com/678655/135816388-650736f8-bfb8-418c-973e-e04856ae79e8.png">

So, I am going to close this issue.

I appreciate your cooperation.
