### ISSUE TITLE
Inserting a string into a BYTES column fails with value exceeds maximum size limit error

### ISSUE THREAD

**Issue by assafY** [googleapis/nodejs-spanner#151]
Env:
  - OS: Debian 4.9.65-3
  - Node.js version: 9.4.0
  - npm version: 5.6.0
  - @google-cloud/spanner version: 1.1.0

I am trying to insert 256bit hex hash strings into spanner tables as bytes - the column being inserted to is of type BYTES(32).

I have attempted to insert the string without modification, then using `Buffer.from({hash})`, and finally using `Buffer.from({hash}, 'hex')`, but all of the above have resulted in the following error:
`Error: New value exceeds the maximum size limit for this column in this database: Table.Hash, size: 48, limit: 32.`

Can you please tell me how I should insert a value into a BYTES column?

**Comment by stephenplusplus** [comment]
Could you show an example of the value of `{hash}` you're attempting?

**Comment by assafY** [comment]
Here is an example:

ccb1cab0e893c94ccb198d72db867657776bd06690005df453aa46d6e068c16a

**Comment by stephenplusplus** [comment]
Thanks. That worked fine for me like this:

```js
/*
CREATE TABLE TypeCheck (
  BytesLimitValue BYTES(32),
) PRIMARY KEY (Key)
*/

var str = 'ccb1cab0e893c94ccb198d72db867657776bd06690005df453aa46d6e068c16a';

table.insert({
  BytesLimitValue: Buffer.from(str, 'hex')
})
```

**Comment by assafY** [comment]
Thanks. It works now.

Not sure what I did wrong, as I did try that, but something must have been wrong in my code.
