### ISSUE TITLE
Generated samples are missing

### ISSUE THREAD

**Issue by fhinkel** [googleapis/nodejs-spanner#1517]
For example there's no sample with this referenced region tag: `spanner_v1_generated_Spanner_BatchCreateSessions_async`

This got merged but it looks somewhat wrong to me: https://github.com/googleapis/nodejs-spanner/pull/1484/files

**Comment by surbhigarg92** [comment]
@sofisl Do we have any update on the autogenerated samples for Node js ?

**Comment by sofisl** [comment]
@surbhigarg92, is this something the spanner team wants? https://github.com/googleapis/nodejs-spanner/blob/f1ae51301d4ea9b0ed1ad4d4762c249fef9f8d08/owlbot.py#L66

**Comment by surbhigarg92** [comment]
@sofisl This was done intentionally to avoid autogenerated samples as we are not using autogenerated client , instead have an handwritten layer for same.

**Comment by sofisl** [comment]
Hi @surbhigarg92, I see what you're saying, but I think there's also an issue with how it renders in cloud.google.com. See here, under [example](https://cloud.google.com/nodejs/docs/reference/spanner/latest/spanner/v1.spannerclient#_google_cloud_spanner_v1_SpannerClient_batchCreateSessions_member_1_)

![Screenshot 2023-02-14 at 12 33 09 PM](https://user-images.githubusercontent.com/55454395/218855714-82099fb9-ac6b-464b-a8b7-1429cd634a01.png)


So, for client libraries with a veneer, we do include these comments:

https://github.com/googleapis/gapic-generator-typescript/blob/fbda4e4065224ed99419f68116538f1d49177ef5/templates/typescript_samples/samples/generated/%24version/%24service.%24method.js.njk#L4

Would it be alright if we included samples here, with that notification?
