### ISSUE TITLE
schema field in CreateDatabaseOptions does not allow string[].

### ISSUE THREAD

**Issue by winor30** [googleapis/nodejs-spanner#1575]
#### Environment details

  - `@google-cloud/spanner` version: 5.16.3

#### Details

The type of the schema field in `CreateDatabaseOptions` is `string`, but reading the [tutorial](https://cloud.google.com/spanner/docs/getting-started/nodejs#look_through_sample_files) and the [internal logic](https://github.com/googleapis/nodejs-spanner/blob/8b950b3af8a66be6c27b5482611e116853d23ecf/src/instance.ts#L842-L845), `string[]` should also be allowed.
So I am wondering if I can define it as string | string[]?
I'm assuming the following modification
https://github.com/googleapis/nodejs-spanner/commit/00f9e7c05c7e474be4d9abadb1e18d244be52877

**Comment by asthamohta** [comment]
Thanks for bringing this up @winor30. Give me a couple of days to look into it and test it and I will get back to you 🙂

**Comment by asthamohta** [comment]
Hi @winor30, did you try passing an array or strings in the schema options? From what I can see it should work fine. As you can see in our sample [here](https://github.com/googleapis/nodejs-spanner/blob/main/samples/schema.js#L39-L54) we pass in an array of strings into the schema and it works.

**Comment by winor30** [comment]
@asthamohta Thank you for confirming.

You are right, in the case of Javascript, I can execute `createDatabase` successfully.

However, in the case of typescript, the `schema` field of `CreateDatabaseOptions` is defined as a `string`, so if the `schema` is an array, a type error will occur. (Although it can be executed successfully with `@ts-ignore`...)

The `schema` field of `CreateDatabaseOptions` is defined as a type that allows `string[]`, so it should be able to execute correctly even in the case of typescript.

**Comment by asthamohta** [comment]
Thanks @winor30 for checking. If you want I can change it to string[]. Is it required for you?

**Comment by winor30** [comment]
@asthamohta 
> If you want I can change it to string[]. Is it required for you?

Thank you!
I would appreciate it if you could fix it.
Alternatively, I have a modified branch that I may be able to submit a PR with.

https://github.com/googleapis/nodejs-spanner/compare/main...winor30:refactor-create-database-options-schema

**Comment by asthamohta** [comment]
Thanks a lot for this @winor30. Looks good to me. I am happy to merge this.
