### ISSUE TITLE
Provide sample code for tuning grpc parameters

### ISSUE THREAD

**Issue by rbrtwng** [googleapis/nodejs-spanner#1596]
Cloud Bigtable allows user to override grpc parameters globally. 

```
const bigtable = new Bigtable({
   'grpc.keepalive_time_ms': 30000,
   'grpc.keepalive_timeout_ms': 10000
});
```

And per offline conversation, for Cloud Spanner, you can't set these values at a global level. Instead these values can be passed with each function call. This is because for different queries number of retry values, timeout, etc make sense differently as per the operation. 

Creating a FR to provide code sample in passing grpc parameters at function level.

**Comment by rahul2393** [comment]
@surbhigarg92 please help triage this ticket

**Comment by surbhigarg92** [comment]
@rbrtwng This is already supported in NodeJs client . I misunderstood few things earlier and this bug skipped my radar. 

```
const spanner = new Spanner({ 
    'grpc.keepalive_time_ms': 30000,
    'grpc.keepalive_timeout_ms': 10000,
  });
```

Would you please check if this works for you ?

**Comment by surbhigarg92** [comment]
Spanner also added these two setting as the default. This can get overridden using the example mentioned in above comment. 

Closing this bug , please feel free to reopen if anything else is required.
