### ISSUE TITLE
[Question] How to use NodeJS Spanner client with Spanner Emulator?

### ISSUE THREAD

**Issue by dzou** [googleapis/nodejs-spanner#1606]
Are there any instructions for how to use the Spanner Emulator through [TestContainers](https://github.com/testcontainers/testcontainers-node) and the NodeJS Spanner Client?

**Comment by asthamohta** [comment]
Hi @dzou.
Here are a few links to help you get started on using Spanner Emulator with NodeJs:
1. [Using the Cloud Spanner Emulator](https://cloud.google.com/spanner/docs/emulator)
2. [Deploying the Cloud Spanner Emulator locally](https://cloud.google.com/blog/topics/developers-practitioners/deploying-cloud-spanner-emulator-locally)
3. [Deployment models for the Cloud Spanner emulator](https://cloud.google.com/blog/topics/developers-practitioners/deployment-models-cloud-spanner-emulator)

Give me some time to look into how to use Spanner Emulator through Test Containers and if we have some information on that. Thanks!
