### ISSUE TITLE
How to use the table.insert() api to insert records with a field that has array type?

### ISSUE THREAD

**Issue by deostroll** [googleapis/nodejs-spanner#1628]
Table defined as follows:

```
CREATE TABLE TestSchema (
somecodes Array<String(MAX)>,
id STRING(36) NOT NULL) PRIMARY KEY (id)
```
Using the nodejs api, I am trying to insert data using the following code:
```
let payload = { someCodes: [], id: randomBytes(16).toString('hex') };
let spanner = new Spanner();
let instance = spanner.instance(instanceId);
let database = instance.database(databaseId);
let table = database.table(tableName);

table.insert(payload, function(err) {
  if(err) {
    return console.error(err);
  }
});
```
The error message displayed in the console is as follows:
```
Could not parse string_value: "[]"
as ARRAY<STRING>
```
What is the correct way to insert for such a table?

PS: As suggested earlier on SO (now deleted), I also tried the promise api pattern of usage and confirm the same error.

**Comment by asthamohta** [comment]
Hi @deostroll I tried running your code and I am not able to recreate your issue as it works for me. Can you try updating to the latest version of the library and try again or provide any other data points which might help me recreate the issue.

**Comment by deostroll** [comment]
Thanks for confirming this. The bug was in the code I had, which stringified arrays. Hence the error.
