### ISSUE TITLE
Keep transaction alive to avoid abortion after transaction been idle for 10 seconds.

### ISSUE THREAD

**Issue by yuanyuan-gl** [googleapis/nodejs-spanner#1652]
Thanks for stopping by to let us know something could be better!

The transaction is aborted after been idle for 10 seconds,  it is not a good practice for the users to run "select 1" to keep the transaction alive. This also makes it hard to troubleshoot transaction related issues. Can client library takes care of this?

**Comment by asthamohta** [comment]
hi @yuanyuan-gl, if you want you can configure the session pool to increase the default time out values, these are the default settings and the values which you can configure: https://github.com/googleapis/nodejs-spanner/blob/main/src/session-pool.ts#L136-L162. Hopefully this will help solve your issue.
