### ISSUE TITLE
Spanner.date generates an invalid Spanner DATE value for dates before 1000AD

### ISSUE THREAD

**Issue by viralpickaxe** [googleapis/nodejs-spanner#1653]
Spanner.date does not generate Spanner compatible ISO dates for years before 1000AD, for example:
`Spanner.date("954-01-01").toJSON()` => `954-01-02` (instead of `0954-01-02`)

This causes an `INVALID_ARGUMENT` query error

**Comment by asthamohta** [comment]
Hi @viralpickaxe, thanks for bringing this to our attention. I feel this code might be a breaking change for someone who is expecting 954-01-02 and has designed their code that way so what I can do is add another new function toIsoStandardJSON() with your code. Would that be okay?

**Comment by asthamohta** [comment]
Okay, that sounds fair @viralpickaxe. I'll merge your PR :)
