### ISSUE TITLE
session pool memory leak

### ISSUE THREAD

**Issue by AAAhs** [googleapis/nodejs-spanner#1655]
#### Environment

  - Node.js version: 12.22.6
  - npm version: 6.14.15
  - `@google-cloud/spanner` version: 6.0.0

#### Detail

I had investigated a memory leak in a project and found that the leak seems to be in the `_getSession` mehod of this client library.
<img width="482" alt="image" src="https://user-images.githubusercontent.com/16396498/175804921-69a94169-f544-45df-bcf4-6b098f5f2e9a.png">

Then I found that calling Promise.race with a long pending promise may lead to a memory leak. Please see here for details: https://github.com/nodejs/node/issues/17469

I have tried to fix and verify this memory leak in the forked repository:
https://github.com/AAAhs/nodejs-spanner/commit/055440815a0e23de2c983bc2ed83bf082a5d0ef5

**Comment by asthamohta** [comment]
Thankyou @AAAhs for bringing this to our attention. Great find! Would it be possible to raise a PR from your fork to the nodejs library. If all the tests pass I am happy to merge this change

**Comment by AAAhs** [comment]
Hi @asthamohta , I've tried to fix it in this PR https://github.com/googleapis/nodejs-spanner/pull/1657, hope it would be helpful to solve this issue, all tests are passed, please review it, thanks for your time.

**Comment by asthamohta** [comment]
Thanks @AAAhs, looks good to me but I would just like the core NodeJs team at google to review it once, that should happen this week. Then we can merge it
