### ISSUE TITLE
`runTransaction` returns a Promise?

### ISSUE THREAD

**Issue by jkoelker** [googleapis/nodejs-spanner#170]
The docstring/docs for [`Database.runTransaction`](https://github.com/googleapis/nodejs-spanner/blob/master/src/database.js#L1196) state that it returns a `Promise`. Alas it does not return anything. Promise returns appear to have been removed in 25ce9bf6f56ad08211be54cccf5bc7146b159093.

**Comment by stephenplusplus** [comment]
Woops! Interested in sending a PR to remove that part of the docs?

**Comment by jkoelker** [comment]
Well it seems to be a bit more endemic rather than an isolated case for example I also ran across [`getTransaction`](https://github.com/googleapis/nodejs-spanner/blob/master/src/database.js#L776). Spot checking most of the `Database` api that claims to be `Promisable` is not.

This makes integrating with cloud funcs a bit interesting, since we can return a promise and have it wait for it to resolve, but getting access to the inner promise is hackey. Currently I'm trying to figure out why https://github.com/google/google-auth-library-nodejs/issues/320 is happening on about 5% of of the calls, and it is suspected that the func it getting terminated before the promises are all resolved.

**Comment by stephenplusplus** [comment]
Have you tried to run that method and verify promises aren’t working? Everything in the Database class should run as promised [except these](https://github.com/googleapis/nodejs-spanner/blob/69b9dcbf8e4292bca28fd289899ee9a004ae4cce/src/database.js#L1527).

**Comment by jkoelker** [comment]
Sorry I should have been more explicit about what I meant when I said `Promisable`, yes most of the class with the exception of the excludes you can chain onto the immediate implicit return of `undefined`, but you cannot chain onto the inner promise that is performing the work.

I suspect specifically in my case from the auth-library issue is that the process is getting canceled when the cloud func's `callback()` is invoked, rejecting all promises hidden internally.

**Comment by stephenplusplus** [comment]
Ah, interesting. Paging @callmehiphop!

**Comment by callmehiphop** [comment]
@jkoelker  hopefully you'll forgive me if I'm not understanding the issue, but are you saying that certain methods that use promises internally are not propagating auth errors correctly?

**Comment by jkoelker** [comment]
I'm not entirely sure what the core of the issue is, my use case is for keeping a bucket inventory in spanner, using a cloud func triggered on `OBJECT_FINALIZE` and `OBJECT_DELETE`. The repro funcs are at [this gist](https://gist.github.com/jkoelker/2954cc37129100012092197ad22ebead).

This works great except when many objects are acted upon at the same time, specifically when I upload 30 files at a time, about 5% (1-2) of the invocations of the function fail with

```
Error: Unexpected error while acquiring application default credentials: Could not load the default credentials. Browse to https://developers.google.com/accounts/docs/application-default-credentials for more information.
at GoogleAuth.<anonymous> (/user_code/node_modules/@google-cloud/spanner/node_modules/google-auth-library/build/src/auth/googleauth.js:229:31)
at step (/user_code/node_modules/@google-cloud/spanner/node_modules/google-auth-library/build/src/auth/googleauth.js:47:23)
at Object.next (/user_code/node_modules/@google-cloud/spanner/node_modules/google-auth-library/build/src/auth/googleauth.js:28:53) 
at fulfilled (/user_code/node_modules/@google-cloud/spanner/node_modules/google-auth-library/build/src/auth/googleauth.js:19:58) 
at process._tickDomainCallback (internal/process/next_tick.js:135:7)
```

This is the `err` that is coming into my callback function passed to `runTransaction`.  What I think is happening is that in the majority of cases, the promises all resolve and everything is fine (spanner gets updated, etc) before the call to `callback()` in the Cloud Func. But something at some point is causing some latency which makes them not to be completed by the time `callback()` is called, which I gather from the other issue and from the docs terminates the process, which then calls `reject` on all the outstanding promises, causing the auth error to be generated.

In an ideal world, I would assume that `runTransaction` would resolve the promises (blocking) or have some way to tie into the promise chain doing the work and/or the promise returned from `getTransaction` would be tied to the promise doing the actual work, so I could chain off it and return that promise in the Cloud Func, and it would then wait for its resolution.

**Comment by callmehiphop** [comment]
I think I understand now (thanks for sharing your code). Unfortunately I don't think we'll ever be able to return a Promise from `runTransaction`. The function passed to `runTransaction` can be called multiple times in the event of an `ABORTED` error. This makes it tricky to support Promises because we would have to retry all the chained functions until commit is called.

As a work around I would suggest either using `getTransaction` or else creating a function that wraps `runTransaction` and resolves once commit is called successfully.

**Comment by jkoelker** [comment]
Resolving as a side effect of calling `commit()` is the hackery I mentioned above, but I should point out you can't reliably use `getTransaction` either as the promise it returns is immediately resolved to [`undefined`](https://github.com/googleapis/nodejs-spanner/blob/master/src/database.js#L806), instead of being able to chain off the session. Or at least I was unable to coerce it to return a promise.

**Comment by callmehiphop** [comment]
@jkoelker could you share a code example of how you're using `getTransaction`? I just wrote this simple test and it worked fine for me.

```js
it('should resolve with a transaction', function() {
  return database
    .getTransaction()
    .then(data => {
      const transaction = data[0];
      return transaction.end();
    });
});
```

**Comment by jkoelker** [comment]
Unfortunately I don't have it anymore as I was in the midst of troubleshooting when I tried it, I think my problem was that I was passing in the same `(err, transaction)`  callback I was using for `runTransaction` to `getTransaction`, then trying to chain off the return,  instead of calling it with no params.

Thanks for the pointer in the right direction there. Once I get it working reliably, I'll see if I can get some time to put together a sample for using inside a cloud func.

**Comment by callmehiphop** [comment]
No worries, let us know how it goes!

**Comment by dan-j** [comment]
Just jumping on this thread coming from https://github.com/google/google-auth-library-nodejs/issues/320#issuecomment-377348124 and think you should wrap the contents of `objectDelete(file)` in a promise and resolve it after you close the database, i.e.

i.e.

```
return new Promise(resolve => {
  database.runTransaction((err, transaction) => {
    // do stuff
    updateBucket().then(() => {
      // do updateBucket stuff
      resolve()
    })
  })
```
