### ISSUE TITLE
export  `Float` in index.ts

### ISSUE THREAD

**Issue by john-twigg-ck** [googleapis/nodejs-spanner#1720]
https://github.com/googleapis/nodejs-spanner/blob/main/src/codec.ts#L125

I can convert TO `Float` using `Spanner.float` but I cannot easily make an interface to capture ORM being returned from the DB.

Example
```
// ??????
import { Float } from "@google-cloud/spanner/build/src/codec"
// ??????

export interface Trace {
    traceId: string
    flowName: string

    startTime: ISODateString

    endTime: ISODateString

    // Duration in uSeconds
    duration: Float

```

**Comment by surbhigarg92** [comment]
@john-twigg-ck Can you please review the #1726 . Will this resolve your issue ?

**Comment by surbhigarg92** [comment]
@john-twigg-ck Please reopen the issue , if [PR](https://github.com/googleapis/nodejs-spanner/pull/1726) does not address your issue.
