### ISSUE TITLE
Session pool max not respected

### ISSUE THREAD

**Issue by walshie4** [googleapis/nodejs-spanner#177]
#### Environment details

  - OS: CentOS
  - Node.js version: 8.9
  - npm version: 5.6
  - `@google-cloud/spanner` version: v1.4.0

#### Steps to reproduce

 None currently, I will create some if it comes to that.

#### Question

I have a an API which is using this Spanner library with its default pooling settings.  Per those settings [0] the max number of sessions in each pool should be 100.  When deploying another set of services which hit said API I receive a bunch of AlreadyExistsErrors when the API calls `.commit` for an insert transaction which violates a unique index.  The problem however is that as other requests continue to come to this set of API replicas the session pool balloons to the max and I start getting `timeout acquiring session` errors (I have a acquireSession timeout of `30000ms`).  At most I currently have 20 replicas of this API, how is it possible their collective session pools could be consuming the current 30,000 session limit?

[0] https://github.com/googleapis/nodejs-spanner/blob/e404e3999d8c834de19842ea6b8d07796bdbd25a/src/session-pool.js#L58

**Comment by callmehiphop** [comment]
Hi @walshie4, I'm sorry to hear you're having issues! Can I ask how you're verifying that you're hitting the 30,000 session limit? If you're seeing the `Timed out acquiring session.` error, that just means that your pool of `100` sessions has hit its max.

In the event that your commit fails we try not to make any assumptions about how you wish to handle that failure. So we do not release the session for that transaction back into the pool, if you're not explicitly releasing it via `transaction.end()`, then it's very likely you would hit the `max` value and start seeing timeouts.

If you call `database.close()` once you start seeing this behavior, we'll actually supply an error message with a list of possible session leaks that you're able to inspect.

```js
database.close(err => {
  if (err && err.messages) {
    err.messages.forEach(leak => console.log(leak));
  }
});
```

**Comment by walshie4** [comment]
@callmehiphop Thank you for the timely response.  I've been tracking the session count using the stackdriver metric.  I'll take a look around and re-open this if I have more information on this front.

**Comment by walshie4** [comment]
@callmehiphop Is calling `end` needed for read-write transactions which fail at `commit` as well?  The docs mention read-only only.

https://cloud.google.com/nodejs/docs/reference/spanner/1.4.x/Transaction#end

**Comment by callmehiphop** [comment]
Yep! `commit` calls `end` internally after a successful request, however if it fails, we don't want to release the session in case you end up retrying, etc. I'm only speculating, but it sounded like maybe after the commit failure the transaction wasn't being retried and the expectation was that GC cleaned up. Assuming that's the case, I think this is something we can fix with better docs.

**Comment by walshie4** [comment]
Hello 👋 

We've implemented the mentioned missing call to `end` for commit failures however I am still seeing the session pool behave in unexpected ways resulting in many issues.  

I've tried a large number of permutations to the session pool setting to little or no gain.  I am still seeing this issue manifest itself.  I have 120 replicas each with a session pool configured to have a `max` of `1100` sessions.  From what I've been told regarding session count this still sounds absurdly over-done as the request throughput for these services is currently in the ballpark of ~100/s _in total_ across all replicas.

Yet even with a crazy setup of 20 Spanner nodes I am hitting the session max of 200,000 sessions.

I am seeing quite a bit of behavior like this:
![image](https://user-images.githubusercontent.com/945703/39724633-23e83d54-51fe-11e8-84c9-ba23226c1ad0.png)

Where the second larger drop-off is initiated by spinning down 10 replicas, however the jump to (over) the max of 200k is simply from standing those replicas back up.  All while under constant load.

My session pool settings are:
```
max: 1100,
min: 600,
concurrency: 1000,
acquireTimeout: 300,
writes: 0.05,
```

Most of these settings are probably over-kill from what I've heard about how many sessions should be in use at any given moment (as many as concurrent requests to Spanner) yet even with a config like:
```
max: 1000,
```
I still see massive spikes of createSession requests which easily eat up the entire 200k session quota, and this is without our heavy load services even being turned on.  

Am I doing more harm than good with pre-warming the session pools via `min`?  Is there a different way I can avoid `RESOURCE_EXHAUSTED` and `Timed out acquiring session.` errors?

With the way this is currently behaving I do not have the confidence to move forward with moving our already scaled infrastructure onto Spanner.  The session pool behavior and session limit makes simply testing a very slow, painful and confusing experience.

My hunch is that it is not properly using sessions available in the pool.  This is backed by the experience of standing up each of these replicas with an ample `min` size (well above the aggregate requests/sec for the entire replica set) but still seeing the session pool spike in size as load is applied.

If you have any other means of debugging what is going on inside the session pool please let me know, and I will try it.

**Comment by walshie4** [comment]
If it helps the load being applied is mostly reads (indexed or PK)

**Comment by vkedia** [comment]
@walshie4 sorry to hear about the issues you are having. Let me assure you that the problems you are running into are likely bugs in the node.js library and not in the cloud spanner backend. 
@danoscarmike Can we prioritize investigating this issue and making whatever fixes are required. This seems like a pretty severe issue. 
cc @snehashah16

**Comment by danoscarmike** [comment]
@callmehiphop can you have another look at this?  Thanks.

**Comment by callmehiphop** [comment]
I'm going to close this since the original issue seems to have been resolved and this appears to be morphing into a clone of #192.
