### ISSUE TITLE
Utilising `PARSE_JSON` with upsert mutations

### ISSUE THREAD

**Issue by abdel** [googleapis/nodejs-spanner#1770]
**What you're trying to do**
Using the `upsert` mutation to insert JSON objects that may contain double values that cannot be round-tripped from string to double to string.

**What code you've already tried**

The table `operations` has a column `objectValue` which is of data type `JSON`.

Initial code to upsert object, which triggered the error. 

```
await database.table.upsert({
	objectValue: {
		myFloat: 184.909685677713,
	},
	updatedAt: new Date()
});
```

Identified the issue to be related to the double value as other double values worked, and found [similar issue](https://stackoverflow.com/questions/69936781/cant-insert-535-5357055664062-to-json-field-of-google-cloud-spanner) as well as the documentation from Google on [working with JSON data](https://cloud.google.com/spanner/docs/working-with-json). The documentation recommends a workaround using `PARSE_JSON(stringifiedJson, wide_number_mode=>'round')`.

This workaround seems to only work when using DML, and not mutations. I tried it out anyway using the upsert mutation using the following code:

```
const stringifiedObj = JSON.stringify({
myFloat: 184.909685677713,
});

await database.table.upsert({
	objectValue: `PARSE_JSON('${stringifiedObj}', wide_number_mode=>'round')`,
	updatedAt: new Date()
});
```

This results in a similar invalid value error where the value is expected to be JSON.

Are there any similar workarounds (like `PARSE_JSON`) that work with mutations to allow us to continue using upserts?

**Any error messages you're getting**

Error received when upserting a JSON object:	

```
Error: 9 FAILED_PRECONDITION: Invalid value for column objectValue in table operations: Expected JSON.
    at Object.callErrorFromStatus (/node_modules/@grpc/grpc-js/src/call.ts:81:17)
    at Object.onReceiveStatus (/node_modules/@grpc/grpc-js/src/client.ts:358:36)
    at /node_modules/@grpc/grpc-js/src/call-stream.ts:210:27
    at Object.onReceiveStatus (/node_modules/grpc-gcp/src/index.ts:130:15)
    at InterceptingListenerImpl.onReceiveStatus (/node_modules/@grpc/grpc-js/src/call-stream.ts:206:19)
    at Object.onReceiveStatus (/node_modules/@grpc/grpc-js/src/client-interceptors.ts:462:34)
    at Object.onReceiveStatus (/node_modules/@grpc/grpc-js/src/client-interceptors.ts:424:48)
    at /node_modules/@grpc/grpc-js/src/call-stream.ts:334:24
    at processTicksAndRejections (node:internal/process/task_queues:77:11)
 ```

**Comment by surbhigarg92** [comment]
Hi @abdel As you correctly stated `PARSE_JSON` will only work with DML not with mutations but that is the case with any other SQL server function. 

Only workaround at the moment is to make an extra round trip to backend to Parse the Json first using DML and then use it for mutation.

**Comment by abdel** [comment]
@surbhigarg92 Thanks for the quick response.

Making a call to parse the JSON could be a viable workaround. I attempted to do this but noticed some different results between what I get from the SDK and what I get when doing the same query in the GCP console.

If I run the following code:

```
const [rows] = await transaction.run({
	sql: `select PARSE_JSON('{"bob": 184.909685677713}', wide_number_mode=>'round')`
});

console.log(rows[0]);
```

This returns `[ { name: '', value: { bob: 184.909685677713 } } ]`, leaving the float unchanged.

If I run the exact same query in GCP console, using the same instance/database I was connected to above:

```
select PARSE_JSON('{"bob": 184.909685677713}', wide_number_mode=>'round')
```

The result is`{"bob":184.90968567771299}`

Initially thought this may just have been `console.log` shenanigans where the float is automatically rounded up. So I attempted the following:

```
const [rows] = await transaction.run({
	sql: `select PARSE_JSON('{"bob": 184.909685677713}', wide_number_mode=>'round')`
});

const parsedObj = rows[0][0].value;

# my original code
await database.table.upsert({
	objectValue: parsedObj,
	updatedAt: new Date()
});
```

which then still results in the same original error of receiving an unexpected JSON value, due to that float.

Did I miss something obvious with this?

**Comment by surbhigarg92** [comment]
@abdel Looks like this is a problem with rounding in Javascript. 

Try below code. Both will result in same output. 
```
const foo = 184.909685677713;
const bar = 184.90968567771299;

console.log(foo);
console.log(bar);
```

**Comment by abdel** [comment]
Yeah, I realised this after posting. 

It seems that the only pathway to avoid that is to use DML with `PARSE_JSON` to ensure that the values are stored correctly. Since the above workaround method will end up with the same problematic value due to the rounding.

**Comment by surbhigarg92** [comment]
Yes, looks like DML is the way to go. 

I am going to close this ticket now. Please feel free to reopen the ticket if you need any more info.

**Comment by fredvollmer** [comment]
Since DML does not support upserts, it seems like we still have a bit of a problem here. @abdel were you able to come up with a working solution?

**Comment by abdel** [comment]
@fredvollmer 

Yeah, we came up with a working solution but far from ideal. It would be great if the `upsert` mutation just did this in the background, but as far as I can tell, this requires a change in the API itself rather than the particular SDK.

We needed to insert multiple things at a time, so figured out a way to batch `PARSE_JSON` DML to retrieve the parsed objects, then followed by batched upserts in a transaction. Here's a rough outline of the process, you can abstract some stuff away, etc.

assuming Spanner is setup first

```
const spanner = new Spanner();
const instance = spanner.instance(...);
const db = instance.database(..);
```

```
const queries = [];
const params = {};

for (const [index, object] of objects.entries()) {
	// label to be able to bind parameters & refer back to the results
	const label = `obj_${index}`;
	
	// construct query for this problematic object
	const query = `TO_JSON_STRING(PARSE_JSON(@${label}, wide_number_mode=>'round')) AS ${label}`;
	queries.push(query);
	
	// bind it as a stringified object
	params[label] = JSON.stringify(object);
}

// run batched queries in on update
const [rows] = await db.run({
	sql: `SELECT ${queries.join(",")}`,
	params,
	json: true
}

// format of this will be as
// {
//    obj_0: "{...}",
//    obj_1: "{...}",
//    ...
// }
const parsedStringObjects = rows[0];
```

`TO_JSON_STRING` is very important to use here. Otherwise, JavaScript/TypeScript will simply round it to a problematic value again. Fortunately, you are able to upsert using stringified objects into a JSON field, so keeping everything as a string maintains the result of `PARSE_JSON`.

Now that you have an object `parsedStringObjects` of stringified object values, you can perform batched upserts in a transaction.

```
await db.runTransactionAsync((transaction) => {
	// loop over objects
	transaction.upsert('tableName', {
		myObject: parsedStringObjects['obj_0'],
	});
	
	....
	
	await transaction.commit();
})
```
