### ISSUE TITLE
runStream returning incomplete and out of order rows

### ISSUE THREAD

**Issue by bbransteitter** [googleapis/nodejs-spanner#180]
#### Environment details

  - OS: Ubuntu 16.04.4 LTS
  - Node.js version: 6.14.1
  - npm version: 5.8.0
  - `@google-cloud/spanner` version: 1.4.1

#### Steps to reproduce

I have a table with this structure:
```
CREATE TABLE accounts (
    recordId STRING(36) NOT NULL,
    account_CID STRING(255),
    account_created_on STRING(1024),
    account_created_on_unixTimestamp FLOAT64,
    account_dashboard_tabs STRING(255),
    account_ok_tabs STRING(255),
    account_summary_content_tabs STRING(255),
    account_to_creator STRING(36),
    account_to_customer_admin STRING(36),
    account_view_tabs STRING(255),
    Address STRING(1024),
    Address1 STRING(1024),
    Address1_city STRING(255),
    Address1_postalcode STRING(255),
    Address1_provinceterritory STRING(255),
    Address_city STRING(255),
    Address_postalcode STRING(255),
    Address_provinceterritory STRING(255),
    current_document_number FLOAT64,
    customer_content_tabs STRING(255),
    Email STRING(255),
    fund_to_account STRING(36),
    FundsTab_AccountSubNavigation STRING(255),
    Number FLOAT64,
    Number1 FLOAT64,
    Number_of_Payments FLOAT64,
    payment_plan_to_account STRING(36),
    Phone_Number STRING(1024),
    Phone_Number1 STRING(1024),
    requested_payment_plan_to_account STRING(36),
    RequestRelationshipCID STRING(255),
    RequestRelationshipContentTab STRING(255),
    Selection_Field___Static STRING(MAX),
    Short_Text STRING(255),
    Short_Text1 STRING(255),
    Short_Text4 STRING(255),
    upload_customer_csv STRING(1024),
    upload_customer_csv_name STRING(255),
    user_to_accounts STRING(36),
) PRIMARY KEY (recordId)
```
When I run the following query:
```
SELECT `root`.`account_created_on` as `field0`, `root`.`Short_Text` as `field1`, `root`.`Short_Text1` as `field2`, `root`.`account_CID` as `field3`, `root`.`recordId` as `recordId` FROM `accounts` AS root
```
My table has 17349  records

Occasionally (1 in 5) when I run this query using:
```js
database.runStream(query)
	.on('error', function (err) {
		console.error(err);
		return reject(err);
	})
	.on('data', function (row) {
		let rowJSON = row.toJSON();
		if (!rowJSON.recordId || rowJSON.recordId.match(/^\d+$/)) {
			console.log('Worker '+process.pid+' Row: '+JSON.stringify(rowJSON));
			console.log(row);
		}
		records[rowJSON.recordId] = rowJSON;
	})
	.on('end', function () {
		return resolve(records);
	});
```
I will get rows that are missing the recordId and the values will be the wrong labels for example field1 will contain the data for field2

**Comment by vkedia** [comment]
@stephenplusplus @jonparrott Can we please prioritize this and get it fixed asap. This seems pretty critical if this is actually a bug.

**Comment by bbransteitter** [comment]
I am available to do screen shares or hangouts if it will help with seeing the bug in action.

**Comment by stephenplusplus** [comment]
I was able to reproduce, I'll update with any findings.

**Comment by alexander-fenster** [comment]
The customer asks to prioritize #197 (that refers to this issue).

**Comment by danoscarmike** [comment]
Ping @stephenplusplus any updates?

**Comment by stephenplusplus** [comment]
I'm working on getting a consistent reproduction case, then I'll make that available for anyone who wants to take a crack at it (including myself). So far, I have a theory, @crwilcox is looking at something else that could be the issue. At some point, we're probably going to have to involve @callmehiphop, though I'm trying to excuse him from this one as long as possible, given his ongoing work with other Spanner priorities.

I'm hoping to have the reproduction case together tomorrow, and I'll update with any progress after.

**Comment by theacodes** [comment]
Is @callmehiphop currently out of office? If not, let's pull them in. This is a P0 customer issue, it takes priority over feature work.

**Comment by danoscarmike** [comment]
Formally assigning @callmehiphop. @alexander-fenster would appreciate your thoughts too.

**Comment by alexander-fenster** [comment]
I'm risking of providing some irrelevant input as I don't really know this code, but as you asked me, I spent some time looking at `toJSON` and its roots and I see just one place where things could get messed up and it's [this code](https://github.com/googleapis/nodejs-spanner/blob/0090be321617050ea227c97738c84054d328eaf8/src/row-builder.js#L167) which is based on the strong assumption that iterating the values using `values.forEach(function(value, index) { ... })` gives the same amount of fields in the same order as stored in `this.fields`. If it's not the case for whatever reason, the resulting JSON is screwed up exactly like we see in the issue.

**Comment by alexander-fenster** [comment]
Copying the code that makes me thinking it might have a problem:
```js
/**
 * Transforms values into JSON format.
 */
RowBuilder.prototype.toJSON = function() {
  this.build();

  var fields = this.fields;

  return this.rows.map(function(values) {
    var formattedRow = [];
    var serializedRow = {};

    values.forEach(function(value, index) {
      var field = fields[index];  // <-- index is array index from forEach, fields is this.fields. do they always match?

      var column = {
        name: field.name,
        value: RowBuilder.formatValue(field.type, value),
      };
```

**Comment by stephenplusplus** [comment]
I've put together a pretty consistent reproduction script in a PR: #203. I've also added a `console.log` in the source code that will only execute when we are about to crash. If anyone wants to take a look, feel free to contribute any ideas.

**Comment by crwilcox** [comment]
@bbransteitter, after looking at @stephenplusplus repro I think I have discovered the issue. This resolved it in the repro we had. Would you be interested in trying a custom build to see if it fixes your problem? If you install in the following way you can try out my fix: `npm install googleapis/nodejs-spanner#180-crwilcox`

**Comment by walshie4** [comment]
Deployed this to one of our heavier load APIs which was also being affected by this issue and the results seem consistent.

Another encouraging metric, the fairly constant stream of errors for `executeStreamingSql` have dropped down to zero.

![screen shot 2018-05-24 at 11 12 26 am](https://user-images.githubusercontent.com/945703/40503586-6c1eac64-5f43-11e8-8643-7c8dab9fb267.png)

**Comment by walshie4** [comment]
Just had to revert away from this proposed change because we started getting reads which were incorrectly returning no rows.

It's so far been very brief using the library without this change but local testing and runs thus far are showing either a variety of the stream errors I've reported, or the correct values.

This makes me think there is something about the proposed change (https://github.com/googleapis/nodejs-spanner/pull/203/files#diff-5db2ea3ba1d562953569f80f40d1f295R68) which is causing this new issue of `spannerDb.run` reads sometimes returning 0 rows when the query in the console returns data (as it should).

Let me know if you have other variants you'd like me to test, for now I'll be reverting away from this test-build.

**Comment by crwilcox** [comment]
@walshie4  thank you so much for giving this a whirl. I just updated the PR. @stephenplusplus  and I came to a different solution that, after a good deal of testing, seems to return the rows. The previous solution had a side-effect of occasionally returning less rows than requested.

if you retry with `npm install googleapis/nodejs-spanner#180-crwilcox` and could let me know how that works for you it would be awesome.

Thanks again for helping us get to the bottom of this.

**Comment by walshie4** [comment]
Just deployed the updated candidate, will report back in ~an hour.

**Comment by walshie4** [comment]
Generally looks good, not sure if this is truly a blocker for this fix but I'm still getting some of the errors described in #198

**Comment by crwilcox** [comment]
@walshie4 . I think two issues may be conflated here. It seems the fix in #204 does fix this issue (#180) but it doesn't address #198, which was originally believed to be the same root cause. If you think this is correct I would like to reopen your issue and spin it off as to not cross the two things up too much.

@bbransteitter , did this work for you?

**Comment by walshie4** [comment]
@crwilcox That sounds good to me, see you there. 👋

**Comment by crwilcox** [comment]
I have reimplemented the streaming for spanner queries. I still have to rework some of the unit tests since things behave a bit different now, but if you want to try it it is installable via `npm install googleapis/nodejs-spanner#rewrite-partial-result-stream`. This fixes some issues raised in the PR for the targeted fix I provided last week. 

@bbransteitter have you had a chance to try the previous branch? Either way, this is probably the one that will be used moving forward. So if you have a chance to try it that would provide useful info.

**Comment by JustinBeckwith** [comment]
Greetings!   @bbransteitter & @walshie4 have y'all had a chance to try out this branch?  We're pretty sure we have it fixed, but we would love to make sure this works for you first :)

**Comment by walshie4** [comment]
@JustinBeckwith I've been using the suggested fix (#208) in production for almost 10 days now.  Does seem to solve this issue.

However with the recent commits I now have an older version of the PR.  Is that branch in a candidate state I should try pulling in?

**Comment by JustinBeckwith** [comment]
@crwilcox should be able to answer that :)

**Comment by crwilcox** [comment]
Hey @walshie4, the branch is updated but what is pushed is stable/passing. We are at a place now where our existing tests all pass. The team still has to commit a few new tests to cover changes but then we plan to merge/release this.

**Comment by walshie4** [comment]
@crwilcox thank you for the update, I'll update the version I'm using in my services and report back any observations.

**Comment by crwilcox** [comment]
A patch release is published that includes this fix. https://www.npmjs.com/package/@google-cloud/spanner
