### ISSUE TITLE
nightly testing flakyness

### ISSUE THREAD

**Issue by alexander-fenster** [googleapis/nodejs-spanner#190]
We haven't had a clean nightly run for spanner for a long time. The fact that we kind of ignore test failures is a sign that something is going wrong. If tests are bad they should be fixed or at least marked to skip, otherwise there is no need to run them at all.

I suggest that we spend some time the following week on our engineering debt and make sure we have several green nightly runs.

Red page that makes me sad: https://circleci.com/gh/googleapis/workflows/nodejs-spanner/tree/master

cc: @crwilcox

**Comment by stephenplusplus** [comment]
@callmehiphop did we have a theory for why sample tests fail so frequently? I recall that we did some investigating, but I can't remember if we ever figured anything out?

**Comment by alexander-fenster** [comment]
My only theory for now is that the 'instance does not exist' error may be caused by system and samples tests running at the same time if the cleanup in any test is implemented incorrectly. I cannot prove it though.

**Comment by callmehiphop** [comment]
Truthfully I have no idea! I remember we caught a bug with system test failures, but I don't recall ever looking into the sample tests.

**Comment by stephenplusplus** [comment]
I think we're good: #193

**Comment by stephenplusplus** [comment]
After #193, the sample tests seem to be fixed, but there's still an issue with system tests: https://circleci.com/gh/googleapis/nodejs-spanner/4195

**Comment by stephenplusplus** [comment]
Here's a potential fix that I originally tried last year for the same CI failures: https://github.com/googleapis/nodejs-spanner/pull/16

**Comment by stephenplusplus** [comment]
Just need some Spanner-y input on this PR: https://github.com/googleapis/nodejs-spanner/pull/16

**Comment by stephenplusplus** [comment]
Does Circle have a `GCLOUD_PROJECT` env var set to `long-door-651`?

**Comment by JustinBeckwith** [comment]
It looks like they don't.  @kinwa91 I thought this was a change you made all up in the Circle CI config?

**Comment by kinwa91** [comment]
After fixing the GCLOUD_PROJECT env var, we still have a system-test failure:

https://circleci.com/gh/googleapis/nodejs-spanner/7498

**Comment by kinwa91** [comment]
<img width="1298" alt="screen shot 2018-09-17 at 12 28 20 pm" src="https://user-images.githubusercontent.com/4001432/45645466-5f714980-ba75-11e8-9b02-d513978a1e9e.png">

**Comment by kinwa91** [comment]
cc @stephenplusplus
