### ISSUE TITLE
Getting Spanner working with Vite

### ISSUE THREAD

**Issue by Timmwardion** [googleapis/nodejs-spanner#1931]
I've spent hours today trying to get the Spanner/Node.js module working with a new app with no luck.

Seems the issue is that the app is built in Vite which doesn't automatically polyfill Node.js modules.

https://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility

At any rate - a day trialling countless ways around it and I'm stuck. Tried various methods for polyfilling but they all seem to fail. Big question is, has anyone else got the spanner module working with Vite or even Vue? Here are some things I've tried:

• https://github.com/grikomsn/vite-plugin-ngmi-polyfill
• https://stackoverflow.com/a/73185225
• https://medium.com/@ftaioli/using-node-js-builtin-modules-with-vite-6194737c2cd2

Also - various solutions to getting `require()` to work in place of `import` have also failed.

**Comment by surbhigarg92** [comment]
Hi @Timmwardion Currently we do not support browser use cases, and they don't make much sense for Spanner. Generally, you won't want to expose your Spanner credentials to any kind of frontend, be it a browser or an app. Probably you should limit the communication with Spanner from the backend
