### ISSUE TITLE
`seqno` parameter is ignored on `transaction.run()` requests

### ISSUE THREAD

**Issue by nickcampbell18** [googleapis/nodejs-spanner#1940]
#### Environment details

  - OS: Linux
  - Node.js version: 20.2
  - npm version: 
  - `@google-cloud/spanner` version: 6.9.0

#### Steps to reproduce

We were investigating whether it's possible to do parallel reads inside a read-write transaction, by sending a set of reads all with the same sequence number (we have since realised this is impossible, per the documentation: "A per-transaction sequence number used to identify this request. This field makes each request idempotent such that if the request is received multiple times, at most one will succeed.")

Anyway, the `transaction.run()` interface will ignore any given `seqno` parameter, e.g.:

```js
transaction.run({query: "SELECT * FROM table", seqno: 42})
// But it uses the `transaction._seqno` property instead
```

Because of this code:

https://github.com/googleapis/nodejs-spanner/blob/cb66474e995a90c1288e70842f723c51f1ffd37d/src/transaction.ts#L1089-L1092

It might be worth updating the types to make it clear that the user is unable to specify this - I wouldn't have spent 30 minutes scratching my head :)

**Comment by surbhigarg92** [comment]
@nickcampbell18 Thanks for reaching out. We will update our documentation.
