### ISSUE TITLE
Out of Bounds for non-existent value

### ISSUE THREAD

**Issue by walshie4** [googleapis/nodejs-spanner#197]
#### Environment details

  - OS: CoreOS
  - Node.js version: v8.9.4
  - npm version: v6.0.1
  - `@google-cloud/spanner` version: v1.4.1

#### Steps to reproduce

  1. ???
  2. ???

Not sure how to reproduce as this is quite odd.  I'm paging data out of an interleaved table using a standard `SELECT * FROM <TABLE> ORDER BY id LIMIT X OFFSET Y` query.  When querying this certain table I get the below error with an out of bounds value.  However when I query the database for that record none exists (when querying for that value in the mentioned column).

```
 "Error: Serializing column "created" encountered an error: Integer 149745544472341487 is out of bounds. Call row.toJSON({ wrapNumbers: true }) to receive a custom type."     
    1: "at Int.valueOf (/opt/app/node_modules/@google-cloud/spanner/src/codec.js:64:11)"     
    2: "at /opt/app/node_modules/@google-cloud/spanner/src/codec.js:96:25"     
    3: "at Array.reduce (<anonymous>)"     
    4: "at Array.<anonymous> (/opt/app/node_modules/@google-cloud/spanner/src/codec.js:85:16)"     
    5: "at rows.map.row (/opt/app/cache-warmers/batch.js:37:30)"     
    6: "at Array.map (<anonymous>)"     
    7: "at fetchBatch (/opt/app/cache-warmers/batch.js:37:15)"     
    8: "at <anonymous>"     
    9: "at process._tickCallback (internal/process/next_tick.js:188:7)"     
```

Interestingly over time I see the two same values consistently reported.  `149745544472341487` & `7394089836914076784`.

**Comment by walshie4** [comment]
I'm starting to think this may be related to this https://github.com/googleapis/nodejs-spanner/issues/180 issue.

I added some extra logging and printed out the trouble rows which are causing the error.  They have values swapped around (enumerated values in ID fields), some are `null`,  and my `created` and `updated` timestamps are massive values.

**Comment by walshie4** [comment]
The code which produces this issue for me is:
```javascript
const [rows] = await spannerDb.run({
  sql: 'SELECT * FROM <table> ORDER BY id LIMIT @limit OFFSET @offset',
  params: {
    limit: 10000,
    offset: 0,
  },
}, { readTimestamp: timestampBound });
return rows.map(row => row.toJSON()); // Causes error from scrambled data
```

**Comment by stephenplusplus** [comment]
Yes, this sounds like the same issue. I'll leave #180 open to track.
