### ISSUE TITLE
Uncaught exception with concurrent queries and inline begin

### ISSUE THREAD

**Issue by grosto** [googleapis/nodejs-spanner#1972]
The client throws an unhandled exception if the initial queries in the transaction are called concurrently and one of the queries fails(except for the first one). You can see the example below. The issue is resolved if `transaction.begin()` is called explicitly before the concurrent queries. 

#### Environment details

  - OS: macOS 14.2 (23C64)
  - Node.js version: v20.1.0
  - npm version: 9.6.4
  - `@google-cloud/spanner` version: reproducible on master 

#### Steps to reproduce

Minimal repro

```ts
// We discovered this issue with ABORTED errors, but
// it's easier to reproduce with this non-existent table query.
const nonExistantTableQuery = 'SELECT * FROM nonExistingTable';
await database.runTransactionAsync(async tx => {
  try {
    await Promise.all([
      tx!.run(selectSql),
      tx!.run(nonExistantTableQuery),
    ]);
    await tx.commit();
  } catch (err) {
    await tx.rollback();
  }
});

```

This code will result in an uncaught exception and it will crash node process.

I think the issue is a missing error handler in this code. 

https://github.com/googleapis/nodejs-spanner/blob/6c0eef16d85e6da4993b246337483a818a4521b5/src/transaction.ts#L1336-L1338

Adding this handler fixes the issue
```TS
.on('error', err => streamProxy.emit('error', err))
```

Happy to open PR with test if this seems correct

**Comment by surbhigarg92** [comment]
Hi @grosto Thanks for raising this bug and identifying the root cause. This looks correct to me. Please feel free to raise the PR if you wish. Else I will take this up in new year 1st week.

**Comment by mrichardEA** [comment]
Just following up on this ticket.  Has there been any progress with getting the proposed fix in?
