### ISSUE TITLE
Query does not return

### ISSUE THREAD

**Issue by walshie4** [googleapis/nodejs-spanner#205]
#### Environment details

  - OS: CoreOS
  - Node.js version: v8.9.4
  - npm version: v6.0.1
  - `@google-cloud/spanner` version: v1.4.1

#### Steps to reproduce

  1. Setup table with mutli-part primary key
  2. query said table with a query which references and groups two of the three parts of the tables primary key (see example)
  3. result or error never arrive

We have a table where the primary key is something like 
```
PRIMARY KEY (storeShardId, storeId, dealId)
```

Didn't realize the query I was running was invalid but either way the library seems to return a promise which never resolves.

query:
```
select * from <table> group by storeId, dealId ORDER BY storeId LIMIT 500 OFFSET 0
```

The query fails in the console with the following error in the console (rightfully so):
```
Star expansion expression references column storeShardId which is neither grouped nor aggregated at line 1, column 8 
```

**Comment by walshie4** [comment]
Possibly related to https://github.com/googleapis/nodejs-spanner/issues/116

**Comment by crwilcox** [comment]
Just noting this is on the radar. We are currently handling some of the other issues which were prioritized over this.

**Comment by walshie4** [comment]
Seeing this happen with a valid query as well, occasionally hangs seemingly returns a promise which never resolves.

The query is paging data out of an interleaved table 10,000 rows at a time.

I'm lowering the page size to see if this mitigates the issue.

**Comment by crwilcox** [comment]
Thanks for more information @walshie4. I am trying to reproduce this. With the star expression it is very repeatable. 

```
const query = {
      sql: 'select * from issuetable group by Short_Text, account_created_on ORDER BY recordId LIMIT 500 OFFSET 0',
      json: true,
    }

    let numRowsReceived = 0
    let rows = []
    var promise = database.run(query)
    promise.then(data => {
      console.log("SUCCESS")
    }, error => {
      /*
       * fails each time with message:"3 INVALID_ARGUMENT: Star expansion 
       * expression references column recordId which is neither grouped nor 
       * aggregated [at 1:8]\nselect * from issuetable group by Short_Text, 
       * account_created_on ORDER BY rec...
       */
      console.log(error.message)
    })
```

Further, I tried this with runSteam. it also called on('error' similar to run()
```
 database.runStream(query)
      .on('error', (error) => {
        console.log(error.message);
      })
      .on('data', (data) => {
        numRowsReceived++
      })
      .on('end', () => {
        assert.strictEqual(numRowsReceived, 500)
        callback()
      })
```

Can you provide further details on which function you are calling and which callback/promise you aren't seeing called?

**Comment by walshie4** [comment]
I'm doing a `db.run` call like your example above without providing a callback (as to receive a Promise).  The `.then` and `.catch` are never executed and the service stops in its tracks.

**Comment by walshie4** [comment]
To clarify, by this do you mean you _were_ able to reproduce?

>With the star expression it is very repeatable.

**Comment by crwilcox** [comment]
RE: 'able to reproduce: I mean that I also get it to tell me that is invalid for my spanner table. 

thanks for letting me know how you are using the API. I can focus in a bit now on to the codepath that may be causing issues. I edited my comment to remove irrelevant details (the runstream example) and make my sample more closely reflect the way you are doing things.

I have also been trying a query with no group by and with specified selections. I haven't seen it fail in any way. :(
```
const query = {
      sql: 'SELECT `root`.`account_created_on` as `field0`, ' + 
           '       `root`.`Short_Text` as `field1`, ' + 
           '       `root`.`Short_Text1` as `field2`, ' +
           '       `root`.`account_CID` as `field3`, ' + 
           '       `root`.`recordId` as `recordId` ' + 
           'FROM `issuetable` AS root ' + 
           'ORDER BY recordId ' + 
           'LIMIT 500 OFFSET 0',
      json: true,
    }
```

**Comment by walshie4** [comment]
I'm currently seeing this with the same query, but without the `GROUP BY` clause.  See below:

```
SELECT * FROM <table> ORDER BY storeId, dealId LIMIT 200 OFFSET 0
```

The `LIMIT` was previously 10k, lowered it to 2k but the issue is still happening occasionally.  I'm going to bring it down to 500 to see if that gets around it.

**Comment by walshie4** [comment]
More details which could help: the table is interleaved on an interleaved table.
```
top parent table
|-- first interleaved table
|---- table I'm querying
```

**Comment by walshie4** [comment]
Still happening with a limit of 500, lowering to 100.

**Comment by crwilcox** [comment]
maybe it has to do with the interleaving. since for me I can't make it fail, have made the table rather large (a large number of reasonably sized rows) and limiting at 10k rows)

**Comment by crwilcox** [comment]
I am running 400 copies of this (leveraging async.times). I am seeing 0 errors, and it is has been looping for a bit. Below is the code I am running. Basically I have it query a bunch of times and log errors. The table is interleaved in another table. It has a 4 part PK. 

```

async function repro_205() {
  let startTime = new Date()
  var callback = err => {
    if (err) throw err
    console.log('Query was successful  EndTime:' + new Date() + 
                ' Elapsed: ' + Math.abs(new Date() - startTime))
    repro_205();
  }
  
  async.times(NUM_ATTEMPTS, runQueryBatches, callback);
  
  function runQueryBatches(_, callback) {
    async.times(NUM_ATTEMPTS, runQuery, callback)
  }

  function runQuery(_, callback) {
    const query = {
      sql: `SELECT account_created_on, Short_Text1, account_CID, recordId
            FROM interleave_issuetable AS root
            ORDER BY Short_Text1  
            LIMIT 10000 OFFSET 0`,
      json: true,
    }

    database.run(query).then(data => {
      callback();
    }).catch(error => {
      console.log(error.message)
      callback(error)
    })
  }
}
```

**Comment by crwilcox** [comment]
Just checking in on this. I don't have a repro for this at this time so this issue is pending more information.

**Comment by danoscarmike** [comment]
Hi @walshie4, are you still experiencing this issue? Looks like last update was that we needed more info to reproduce. Can you help with that?
