### ISSUE TITLE
.toJSON() sometimes doesn't convert values

### ISSUE THREAD

**Issue by walshie4** [googleapis/nodejs-spanner#207]
#### Environment details

  - OS: CoreOS
  - Node.js version: v8.9.4
  - npm version: v6.1.0
  - `@google-cloud/spanner` version: v1.4.1

#### Steps to reproduce

  1. Setup db with table which contains a field with a definition as follows: 
```sql
fieldName ARRAY<STRING(32)>
```
  2. Query said table (I'm doing this in queries with a `LIMIT 1000` on them), and call `.toJSON()` on each returned row
  3. Use some validation code like such to detect fields not being converted
```javascript
if (arrayField && arrayField.length > 0 && arrayField.some(each => typeof each === 'object')) {
  console.log('Object in arrayField');
}

```

I've added the aforementioned logs to a task and API I suspected was being impacted by this issue and get rows which look like the following next to converted fields:
```
{
  fieldName: {
    kind: "stringValue",
    stringValue: "value",
  },
}
```

However a fair amount of requests are still succeeding so this issue does not appear to be constant.

**Comment by walshie4** [comment]
Not 100% sure this is related but I have a millisecond unix timestamp value which when read from the db sometimes comes out as a string and sometimes as an int (same value).  Feels like it could be related here possibly.

**Comment by walshie4** [comment]
^ those values seem to only have this issue on objects which also suffer from the `ARRAY<>` is an object issue

**Comment by walshie4** [comment]
Currently seeing this cause the above style issue with `ARRAY<>` types, and leaving integers as strings.  Happening about 10-15 times per second in one of our APIs.

**Comment by crwilcox** [comment]
Quick Update: I believe this may have been to do with the old implementation. We had more than one value formatter depending on branching. Once we merge the other fixes I am going to dig into this one.

**Comment by crwilcox** [comment]
No status change on this, still in the queue.

**Comment by crwilcox** [comment]
Hi @walshie4 , the newest version is released now. In doing the rework some duplicate codepaths were removed/simplified. Can you still reproduce this issue on the latest package on npm (1.4.2)?

**Comment by crwilcox** [comment]
Since you have logging for this, can you report back if  `@google-cloud/spanner >= 1.4.2` fixes the issue?

**Comment by walshie4** [comment]
Looks like `v1.4.2` solves the issue 👍
