### ISSUE TITLE
Database.getDatabaseDialect's "cb" argument is never used

### ISSUE THREAD

**Issue by odeke-em** [googleapis/nodejs-spanner#2075]
If we examine the method "getDatabaseDialect" https://github.com/googleapis/nodejs-spanner/blob/30151cad2723d6a9f2c70342c81f1a578ee02f6a/src/database.ts#L1530-L1553
we can see that the callback passed in is never used. I found this while working on trace instrumentation for these libraries.

**Comment by alkatrivedi** [comment]
Hi @odeke-em, thanks for pointing it out. I have raised a PR to fix this issue
