### ISSUE TITLE
Error 8: CountFinalAggregator ran out of memory during aggregation

### ISSUE THREAD

**Issue by walshie4** [googleapis/nodejs-spanner#215]
### Environment details

  - OS: CentOS
  - Node.js version: v8.9.4
  - npm version: v5.10.0
  - `@google-cloud/spanner` version: v1.4.3

#### Steps to reproduce

  1. ???
  2. ???

When running the following query
```
      SELECT stores.*, COALESCE(couponCount, 0) AS couponCount
      FROM coupons LEFT JOIN@{JOIN_TYPE=HASH_JOIN} (
        SELECT storeId, COUNT(*) AS couponCount FROM storeDeal GROUP BY storeId
      ) USING (storeId)
      ORDER BY stores.storeId
      LIMIT @queryLimit
      OFFSET @queryOffset

```
with a limit of 5000 paging though a table I sometimes get the following error:

```
   code: 8    
   details: "CountFinalAggregator ran out of memory during aggregation."    
   message: "8 RESOURCE_EXHAUSTED: CountFinalAggregator ran out of memory during aggregation."    
   metadata: {
    _internal_repr: {
    }
   }
   stack: [
    0: "Error: 8 RESOURCE_EXHAUSTED: CountFinalAggregator ran out of memory during aggregation."     
    1: "at Object.exports.createStatusError (/opt/app/node_modules/grpc/src/common.js:87:15)"     
    2: "at ClientReadableStream._emitStatusIfDone (/opt/app/node_modules/grpc/src/client.js:235:26)"     
    3: "at ClientReadableStream._receiveStatus (/opt/app/node_modules/grpc/src/client.js:213:8)"     
    4: "at Object.onReceiveStatus (/opt/app/node_modules/grpc/src/client_interceptors.js:1282:15)"     
    5: "at InterceptingListener._callNext (/opt/app/node_modules/grpc/src/client_interceptors.js:590:42)"     
    6: "at InterceptingListener.onReceiveStatus (/opt/app/node_modules/grpc/src/client_interceptors.js:640:8)"     
    7: "at /opt/app/node_modules/grpc/src/client_interceptors.js:1045:24"     
   ] 
```

The query works after a few retries.

**Comment by crwilcox** [comment]
can you provided an idea of the size of some of these variables?
- queryLimit
- queryOffset
- size of table before limits? 
- what is a row sizewise?

Have you tried running this same query from console.cloud.google.com? Does it succeed there?

**Comment by walshie4** [comment]
The queryLimit is consistently 5,000.

The queryOffset starts at 0 and then walks up in increments of 5,000 with the max value being ~40,000.

> size of table before limits
Not sure what you mean here.

The stores table schema is made of the following types
```sql
STRING(64)
STRING(32)
BOOL
STRING(MAX)
ARRAY<STRING(32)>
STRING(512)
INT64
INT64
INT64
INT64
STRING(2)
INT64
BOOL
BOOL
BOOL
BOOL
STRING(64)
STRING(MAX)
STRING(128)
STRING(MAX)
STRING(MAX)
STRING(MAX)
INT64
INT64
INT64
INT64
ARRAY<STRING(255)>
STRING(32)
INT64
INT64
INT64
INT64
BOOL
STRING(128)
INT64
STRING(256)
```
and the coupons table...
```sql
STRING(64)
STRING(32)
STRING(64)
INT64
INT64
INT64
STRING(64)
INT64
STRING(256)
BOOL
INT64
BOOL
BOOL
STRING(256)
INT64
INT64
STRING(MAX)
INT64
STRING(16)
STRING(16)
INT64
STRING(MAX)
```

**Comment by snehashah16** [comment]
@walshie4 - have u used tried Profiling the query & finding possible optimizations for the query ?

**Comment by snehashah16** [comment]
My first impression is:
- if u run this query multiple times (with different offsets), the server is scanning the full table to compute this (`SELECT storeId, COUNT(*) AS couponCount FROM storeDeal GROUP BY storeId`) and eventually running out of memory.

I would recommend saving this result and avoid re-computation.

**Comment by walshie4** [comment]
We do save this result.  The task which runs this query does so as a kubernetes cron job so that the production APIs don't need to make this query at request time.  We make this query once every 10 minutes.

**Comment by walshie4** [comment]
Oh my bad I just realized I mis-read what you had said.  We can refactor to avoid re-computing the inner query.

**Comment by crwilcox** [comment]
@walshie4 , just checking in to see if any progress has been made on this.
