### ISSUE TITLE
all: review usage examples in docs for actuality in Typescript

### ISSUE THREAD

**Issue by odeke-em** [googleapis/nodejs-spanner#2164]
If we look at https://github.com/googleapis/nodejs-spanner/blob/2a19ef1af4f6fd1b81d08afc15db76007859a0b9/src/database.ts#L3590 and try to implement it, we get back
```shell
error TS2493: Tuple type 'CommitResponse' of length '1' has no element at index '1'.

           const [resp, rerr] = await this.writeAtLeastOnce(mutations, options);
```

I've found other spots where in Typescript usage, that didn't match actual usage.

Kindly pinging @surbhigarg92 @alkatrivedi

**Comment by alkatrivedi** [comment]
Thanks @odeke-em for pointing this out. I have raised a PR for this
