### ISSUE TITLE
Cloud Spanner documentation should talk about supported types

### ISSUE THREAD

**Issue by lukesneeringer** [googleapis/nodejs-spanner#22]
_From @vkedia on October 4, 2017 22:33_

On the cloud spanner documentation, I could not find any mention of what data types are supported and how are these to be specified in the client library. For eg how would I specify a date or a timestamp or a float or bytes. I have seen customers specifying bytes as Base64 encoded since the rpc protocol talks about that. But the client library does Base64 encoding on their behalf.

_Copied from original issue: GoogleCloudPlatform/google-cloud-node#2654_

**Comment by lukesneeringer** [comment]
Hey @jmdobry, did your recent docs update happen to address this? :-)

**Comment by jmdobry** [comment]
no

**Comment by JustinBeckwith** [comment]
👋 @jsimonweb is this something you could take a look at?

**Comment by sduskis** [comment]
👋 @jsimonweb is this something you could take a look at?

**Comment by JCIV-SE** [comment]
@lukesneeringer sent you an email

**Comment by jasonlittle0** [comment]
Hi

**Comment by stephenplusplus** [comment]
@JustinBeckwith is this issue still with the right assignee?

**Comment by skuruppu** [comment]
> @JustinBeckwith is this issue still with the right assignee?

I updated the assignee since the Cloud Spanner documentation is now owned by a different set of people.

**Comment by mmmarklu** [comment]
I'm not sure what to do with this one, so I'm closing it and providing some rationale. Please feel free to reopen and specify the change you'd like to see.

On the node.js reference home page, I found a link to https://github.com/googleapis/nodejs-spanner/blob/master/samples/datatypes.js which has an example of how to insert bytes. 

The node reference docs don't indicate that you need to perform base64 conversion, which I think is convention for node. Users shouldn't be looking at gRPC docs when using node.js libraries.
