### ISSUE TITLE
Error 13 INTERNAL: GOAWAY received

### ISSUE THREAD

**Issue by walshie4** [googleapis/nodejs-spanner#234]
#### Environment details

  - OS: CentOS
  - Node.js version: v8.9.4
  - npm version: v5.10.0
  - `@google-cloud/spanner` version: v1.4.3

#### Steps to reproduce

  1. ???
  2. ???

Have an API which is using this library a lot for both read and write usage.  Not sure what is currently causing this but will dig in more if needed.  Getting a few hundred of these per day, seem to come in bursts.

Stack trace:
```
0: "Error: 13 INTERNAL: GOAWAY received"     
    1: "at Object.exports.createStatusError (/opt/app/node_modules/grpc/src/common.js:87:15)"     
    2: "at ClientReadableStream._emitStatusIfDone (/opt/app/node_modules/grpc/src/client.js:235:26)"     
    3: "at ClientReadableStream._receiveStatus (/opt/app/node_modules/grpc/src/client.js:213:8)"     
    4: "at Object.onReceiveStatus (/opt/app/node_modules/grpc/src/client_interceptors.js:1282:15)"     
    5: "at InterceptingListener._callNext (/opt/app/node_modules/grpc/src/client_interceptors.js:590:42)"     
    6: "at InterceptingListener.onReceiveStatus (/opt/app/node_modules/grpc/src/client_interceptors.js:640:8)"     
    7: "at /opt/app/node_modules/grpc/src/client_interceptors.js:1045:24"     
```

**Comment by stephenplusplus** [comment]
Have you been using this copy of Spanner? https://github.com/googleapis/nodejs-spanner/issues/183#issuecomment-396320012

**Comment by stephenplusplus** [comment]
I believe that should retry on this type of error-- when you have the chance, can you give it a try?

**Comment by crwilcox** [comment]
@walshie4 , have you had a chance to try @stephenplusplus change?

**Comment by Duncan00** [comment]
We start getting more of this errors currently, after upgrading to use **@google-cloud/spanner** client **2.0.0**.

**Environment details**
- OS: COS
- Node.js version: 8.11.1
- yarn version: 1.9.4
- @google-cloud/spanner version: 2.0.0

**Comment by stephenplusplus** [comment]
I'm going to close this issue, as it's still not clear if it is one. I will happily open it back up if anyone can provide more details on how we can reproduce.

**Comment by Duncan00** [comment]
Hello, we don't have code that can easily reproduce the error directly. We are getting the error occasionally. 

One clue is that we are getting the same error in two different services separately (1 high throughput, 1 low throughput). Two services are accessing the same spanner cluster, but different DB. 
In both of the services, we insert record to two tables in respective DB (Insert a parent record to parent table, and then insert the corresponding child record to the child table.) within a read-write transaction.

We didn't do any read inside the read-write transaction. We just want to ensure the two write action can be succeeded together.

**Comment by nodegin** [comment]
Getting the same error here after running the script 1 day.

**Comment by nodegin** [comment]
```
(node:42345) UnhandledPromiseRejectionWarning: Error: 13 INTERNAL: GOAWAY received
    at Object.exports.createStatusError (/tmp/spanner/node_modules/grpc/src/common.js:87:15)
    at Object.onReceiveStatus (/tmp/spanner/node_modules/grpc/src/client_interceptors.js:1188:28)
    at InterceptingListener._callNext (/tmp/spanner/node_modules/grpc/src/client_interceptors.js:564:42)
    at InterceptingListener.onReceiveStatus (/tmp/spanner/node_modules/grpc/src/client_interceptors.js:614:8)
    at callback (/tmp/spanner/node_modules/grpc/src/client_interceptors.js:841:24)
(node:42345) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:42345) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by nodegin** [comment]
Can `@google-cloud/common-grpc` be updated to retry failed request and handle uncaught exceptions / rejections?

**Comment by stephenplusplus** [comment]
@nodegin can you share the script that is causing hte error?

**Comment by nodegin** [comment]
@stephenplusplus 

```js
for (let i = 0; i < 10000000; i++) {
  const random = getRandomOffset()
  const result = await database.run({
      sql: 'SELECT * FROM user LIMIT 1 OFFSET @random',
      params: { random },
      json: true,
  })
  await someTable.insert([
      { id: result[0].id, random },
  ])
}
```

**Comment by trevyn** [comment]
I also have been seeing this error again, please reopen.

**Comment by JustinBeckwith** [comment]
@trevyn greetings, and apologies for the trouble.  Can you please open a new issue, including the code snippet if you're having issues?  Thanks!

**Comment by Duncan00** [comment]
Thanks for checking this out~ 
Seems we don't get this problem in version `2.1.0`, but we are this error much more frequently when upgraded to `2.2.1`.

**Comment by JustinBeckwith** [comment]
@druman55  greetings, and apologies for the trouble. Can you please open a new issue, including the code snippet if you're having issues? Thanks!

**Comment by WaldoJeffers** [comment]
This error still happens with node-spanner v3.1.0 :/
