### ISSUE TITLE
Spanner has an uncaught exception in an async function

### ISSUE THREAD

**Issue by gcochard** [googleapis/nodejs-spanner#237]
#### Environment details

  - OS: Debian 9
  - Node.js version: 10.5.0
  - npm version: 6.1.0
  - `@google-cloud/spanner` version: 1.5.0

#### Steps to reproduce

  1. Call insert with an undefined value somewhere in the row data
  2. Try to insert it
  3. Expect error to be passed to callback, but it is thrown and uncaught instead

```
/opt/pinger/node_modules/@google-cloud/common-grpc/src/service.js:953
      throw new Error('Value of type ' + typeof value + ' not recognized.');
      ^
Error: Value of type undefined not recognized.
    at ObjectToStructConverter.encodeValue_ (/opt/pinger/node_modules/@google-cloud/common-grpc/src/service.js:953:13)
    at Function.GrpcService.encodeValue_ (/opt/pinger/node_modules/@google-cloud/common-grpc/src/service.js:528:52)
    at Object.encode (/opt/pinger/node_modules/@google-cloud/spanner/src/codec.js:307:29)
    at /opt/pinger/node_modules/@google-cloud/spanner/src/transaction-request.js:800:22
    at Array.map (<anonymous>)
    at /opt/pinger/node_modules/@google-cloud/spanner/src/transaction-request.js:798:23
    at Array.map (<anonymous>)
    at Table.TransactionRequest.mutate_ (/opt/pinger/node_modules/@google-cloud/spanner/src/transaction-request.js:783:24)
    at Table.insert (/opt/pinger/node_modules/@google-cloud/spanner/src/table.js:378:15)
    at Table.wrapper [as insert] (/opt/pinger/node_modules/@google-cloud/spanner/node_modules/@google-cloud/common/src/util.js:749:29)
```

Sample code could look like this:

```js
table.insert({val: [1, undefined]})
```

Resolution requests
1. The spanner lib should call the callback with the error (I have a PR in progress for this, but tests specify it should throw)
2. codec should probably to convert undefined to null instead

**Comment by stephenplusplus** [comment]
@JustinBeckwith @snehashah16 and @gcochard seem like the best to make these calls.

**Comment by callmehiphop** [comment]
@JustinBeckwith @snehashah16 any input here?

**Comment by JustinBeckwith** [comment]
I can really see this one both ways.  Throwing on invalid input feels like the appropriate action, but I can also see that being hard to predict, especially when the method call is nested deep in a bunch of callbacks and you're expecting the errback to be called 🤷‍♂️ 

In the absence of a strong preference one way or the other, I trend towards leaving it the way it is. 

Curious about others thoughts here too!  @googleapis/node-team @ofrobots @fhinkel

**Comment by snehashah16** [comment]
> codec should probably to convert undefined to null instead

I agree, we should not convert undefined to null for several reasons:
- hard to debug
- un-intended in some cases
- backend may still throw an error for null values when columns don't support it

**Comment by callmehiphop** [comment]
SGTM! I'm going to close this because it sounds like we agree the current functionality is correct.
