### ISSUE TITLE
Support or documentation for transaction commit timestamp

### ISSUE THREAD

**Issue by majelbstoat** [googleapis/nodejs-spanner#241]
Because Spanner doesn't support `RETURNING` (I wish it did!), when creating a record using `Spanner.COMMIT_TIMESTAMP`, I want to replace that placeholder with the timestamp of the commit before returning my created object to the client.

In the golang library, the commited timestamp is returned as the result of the transaction:

```go
user := &User{
  CreatedAt: spanner.COMMIT_TIMESTAMP,
}
ts, err := s.db.ReadWriteTransaction(ctx, func(ctx context.Context, txn *spanner.ReadWriteTransaction) error {
  // ... Insert
})
if err != nil {
  return err, nil
}
user.CreatedAt = ts
return nil, user
```

However, there is currently either no way to do this in the node library, or the documentation does not make it clear how.

If it's not in the library yet, one possible option would be making it the return result of the `commit()` method.

  - `@google-cloud/spanner` version: 1.5

**Comment by callmehiphop** [comment]
I believe this is actually possible, but I agree we could be doing a better job of documenting it.

```js
database.runTransaction((err, transaction) => {
  // ... insert/etc.
  transaction.commit((err, response) => {
    const ts = response.commitTimestamp;
  });
});
```

**Comment by majelbstoat** [comment]
oh, cool. let me check that out, thanks :)

**Comment by majelbstoat** [comment]
Can confirm that this works both for callback, and promise-style. Thanks!
