### ISSUE TITLE
deep-extend@0.4.2 security vulnerability

### ISSUE THREAD

**Issue by lmnz** [googleapis/nodejs-spanner#268]
#### Environment details

  - OS: macOS High Sierra v10.13.3
  - Node.js version: v8.9.4
  - npm version: v5.6.0
  - `@google-cloud/spanner` version: 1.5.0

#### Steps to reproduce

https://nodesecurity.io/advisories/612

path to package:
`@google-cloud/spanner@1.5.0 > google-gax@0.16.1 > grpc@1.12.4 > node-pre-gyp@0.10.0 > rc@1.2.6 > deep-extend@0.4.2`

#### Suggested fix

  - upgrade to deep-extend@0.5.1 (rc@1.2.8 seems to have upgraded deep-extend to 0.6.0)
  - use nsp to proactively stub security vulnerabilities out

**Comment by JustinBeckwith** [comment]
This is fixed in master, we just need to ship 2.0.  Blocked on #245.

**Comment by JustinBeckwith** [comment]
This was fixed in the 2.0 release :)
