### ISSUE TITLE
table.delete may be confusing for users

### ISSUE THREAD

**Issue by crwilcox** [googleapis/nodejs-spanner#296]
`Table.prototype.delete` results in a `DROP TABLE` operation on the database. 
Here is a quick overview of the surface:
```
db.table('blah').insert //Inserts a Row
db.table('blah').update //Updates a Row
db.table('blah').upsert //Upsert a Row
db.table('blah').delete //Deletes the table
db.table('blah').deleteRows //Deletes a Row
```

It may be worth considering moving the functionality of `delete` to a new name, such as `deleteTable`, `drop`, or `dropTable` to make it clear this isn't an operation to delete rows but the table. Other non qualified operations (`insert`, `update`, etc) are on the row so it is odd to have `delete` be table level.

**Comment by crwilcox** [comment]
Also, `Database.prototype.delete` will delete the database, so we are consistent with this. On `Database`, `createTable` is the operation to make a table.

I propose the following

`Table.delete` => `Table.drop`
`Database.delete` => `Database.drop`

Another client, Python uses the terminology `drop` as it matches the underlying operation. This would avoid confusion with row deletion methods.

**Comment by wyardley** [comment]
> Could we introduce a rows argument to delete that would alter the meaning?
> 
>     table.delete(rows) = "delete rows in this table"

What if the rows array is empty - would that evaluate differently from `table.delete()`? Either way, this seems kind of confusing and risky.

I can see the point about it being consistent with other libraries / services, but on the other hand, from the standpoint of most people who work with databases, I think `drop()` is a little more conventional? The risk of deleting a table when you're trying to delete a row seems important, while it's a mistake one would probably only make once, it could be a pretty unpleasant mistake to make.

Personally, I'd rather see `deleteTable` to match `deleteRows()` than to have `delete()` work both ways....

**Comment by stephenplusplus** [comment]
> What if the rows array is empty - would that evaluate differently from table.delete()? Either way, this seems kind of confusing and risky.

My first thought would be, that should throw an error.

> but on the other hand, from the standpoint of most people who work with databases, I think `drop()` is a little more conventional? 

Agree-- we should first be conventional with these types of users, rather than general users of our other libraries. I think we could still add the `drop()` method to support the familiar language.

> Personally, I'd rather see `deleteTable` to match `deleteRows()` than to have `delete()` work both ways....

My issue here is the backwards hierarchy:

```
database -> table -> deleteTable()
```

On the other hand, `deleteTable()` could exist on the database instance:

```
database -> deleteTable()
```

> The risk of deleting a table when you're trying to delete a row seems important

I believe this can be solved by reading the input. But before I'm sure, I want to make sure I understand-- if a user doesn't provide an argument to `table.delete()`, what would they expect to happen?

**Comment by dsquier** [comment]
I agree with adding a `.drop` method. 

This is the standard vocabulary used in other relational databases and provides a clear delineation between the DML `DELETE` statements and DDL `DROP` statements.

Additionally, this has been part of the [SQL standard](http://web.cecs.pdx.edu/~len/sql1999.pdf) for several decades. 

Is there a reason Google is not modeling Spanner SQL syntax from this?

**Comment by crwilcox** [comment]
One reason to incorporate @stephenplusplus recommendation is it would allow for the existing code to continue to function as intended, while guarding against people who call `delete(rows)` meaning to call `deleteRows(rows)`. 

If this work is done it will involve deprecating a method and adding a new one and in a future release removing that method. So there could be value in guarding the `delete` call in the meantime.

**Comment by JustinBeckwith** [comment]
Just to document the outcomes of this discussion clearly - we are going to:
- Throw an exception if you pass any arguments to the `table.delete` method.  This means that if a user got confused and tried to use this method to delete rows, we will set them straight.
- Add a `table.drop` method that aliases the `table.delete` method.

**Comment by WaldoJeffers** [comment]
Good idea, on multiple occasions I was just an inch away from deleting an entire table when I was actually trying to delete rows 😅
