### ISSUE TITLE
spanner SDK is mixing the callback(err) and throw error will cause unhandled promise rejection

### ISSUE THREAD

**Issue by eric4545** [googleapis/nodejs-spanner#325]
#### Environment details

  - OS: COS
  - Node.js version: 8.11.1
  - yarn version: 1.9.4
  - `@google-cloud/spanner` version: 2.0.0

#### Steps to reproduce

  1. `transaction.end` called
  2. `SessionPool.release` throw `ReleaseError`
https://github.com/googleapis/nodejs-spanner/blob/c5500c7fb2d063bff80fe38589f7adcaad1b3645/src/session-pool.js#L339-L342
  3. `transaction.end` didn't wrap with try catch and didn't passed to callback, causing unhandled promise rejection.
https://github.com/googleapis/nodejs-spanner/blob/c5500c7fb2d063bff80fe38589f7adcaad1b3645/src/database.js#L496-L498

We toke a look into the source code and found that spanner SDK is mixing the callback(err) and throw error. error handling in the underneath spanner sdk is broken and encapsulated. as API user, we could not handle those errors on the public API provided by spanner sdk.

https://github.com/googleapis/nodejs-spanner/blob/c5500c7fb2d063bff80fe38589f7adcaad1b3645/src/transaction.js#L454-L458

this line, it should use callback(new Error) which could be handled by the promisified try catch block, but they use throw new Error which could not be properly handled by promisify utils and yields this unhandled promise rejection error

**Comment by stephenplusplus** [comment]
I'd like to see if @callmehiphop could chime in on this one.

**Comment by callmehiphop** [comment]
@stephenplusplus @JustinBeckwith usually I would say throwing off the bat is the way to go, however I think maybe we want to make an exception for the Transaction object. Transactions will almost certainly have a fair amount of nesting going on

```js
database.runTransaction((err, txn) => {
  txn.run('SELECT * FROM MyTable', (err, rows) => {
    txn.runUpdate('UPDATE MyTable (thing) VALUES ("yas")', (err, rowCount) => {
      txn.commit(err => {});
    });
  });
});
```

IMO it doesn't feel practical to throw here, because then a ton of try/catch nesting would be needed and that sounds annoying/painful to work with. Any thoughts/opinions here?

**Comment by JustinBeckwith** [comment]
I'm entirely supportive of using the errback instead of throwing. I generally find most people are surprised by throws in callback based async functions 🤷‍♂️

**Comment by eric4545** [comment]
If the SDK is callback based, need to follow [Error-first callbacks](https://nodejs.org/api/errors.html#errors_error_first_callbacks),  otherwise it will be so painful to handle the error

```js
database.runTransaction((err, txn) => {
    try {
        txn.runUpdate('UPDATE MyTable (thing) VALUES ("yas")', (err, rowCount) => {
            if (err) {
                // Handle Error
            }
            txn.commit(err => {});
        });
    } catch (e) {
            // Handle Error
    }
});
```
