### ISSUE TITLE
Access field types in query response

### ISSUE THREAD

**Issue by dsteiner-broadsoft** [googleapis/nodejs-spanner#332]
It seems as all the query responses are wrapped with the PartialResultStream and formatting of the response is being done there while making the field with their types inaccessible

https://github.com/googleapis/nodejs-spanner/blob/master/src/partial-result-stream.js#L79

Though it would be helpful to be able to get access to the metadata for each column's type. The only way I can see right now to access the metadata of a table would be using the Database.getSchema()

https://github.com/googleapis/nodejs-spanner/blob/master/src/database.js#L719

and parsing the string to be able to get a column's type which does not seem very practical.

Any reason for not making the full response data available in the query response?

**Comment by stephenplusplus** [comment]
Good catch. Streaming methods are difficult to return the raw response from, for a couple of reasons:

1) A stream involves more than one API response arguments
2) A stream passes through one "thing" to the user

For a query response stream, the user wants the formatted result emitted on each data event. To add on the `apiResponse` argument, we'd have to do something creative, maybe:

```js
queryStream()
  .on('data', result => {
    result.myCustomProperty = true
    const apiResponse = result[spanner.API_RESPONSE_SYMBOL]
  })
```

Better ideas welcome!

(cc @callmehiphop)

**Comment by callmehiphop** [comment]
@stephenplusplus that could work. Alternatively, what are your feelings on emitting a `response` event *before* we start formatting/pushing rows to the user.

```js
queryStream()
  .on('response', response => {})
  .on('data', row => {});
```

**Comment by stephenplusplus** [comment]
That's perfect!
