### ISSUE TITLE
Outside of Transactions, always use single-use transactions

### ISSUE THREAD

**Issue by stephenplusplus** [googleapis/nodejs-spanner#347]
RE: https://github.com/googleapis/nodejs-spanner/pull/16#issuecomment-399130367

And default `strong: true` to enable strong reads.

@snehashah16 -- correct?

**Comment by snehashah16** [comment]
i am not sure what is covered within "always use single-use transactions".. could u provide more information

**Comment by stephenplusplus** [comment]
This refers back to https://github.com/googleapis/nodejs-spanner/pull/16#issuecomment-399130367

**Comment by snehashah16** [comment]
reading through another bug, i noticed there is a heavy usage of singleUse within node library. 
for all writes (insert|update|delete), it would best performed within an explicit txn ( begin txn -> modify data -> commit). This guarantees idempotency due to replays etc. [docs here](https://github.com/googleapis/googleapis/blob/8bec26a931a0d0247ca8f7e915629ec70c27010f/google/spanner/v1/spanner.proto#L614)

**Comment by stephenplusplus** [comment]
For the write methods, I think that should be fine (@callmehiphop ?)

Regarding this question: https://github.com/googleapis/nodejs-spanner/pull/16#issuecomment-399130367 -- what do you think? `database.run` uses `executeStreamingSql` underneath.

**Comment by callmehiphop** [comment]
@snehashah16 we could probably use a refactor to make the code clearer, but only the Table object makes heavy use of single use transactions. All writes done via Transactions actually use the begin -> commit workflow.

As for `Database#run`, I was always under the impression that the backend created a single use transaction object for us. The ExecuteSqlRequest proto docs say

> The transaction to use. If none is provided, the default is a temporary read-only transaction with strong concurrency.

**Comment by snehashah16** [comment]
@callmehiphop  @crwilcox 
Lets discuss this and have a design agreed upon.

**Comment by stephenplusplus** [comment]
@snehashah16 I reviewed our methods to determine the ones that read and the ones that write:


## Database

- `run()` / `runStream()`
  - Spanner > executeStreamingSql

## Table

- `createReadStream()` / `read()`
  - Spanner > streamingRead

- `deleteRows()`
  - Spanner > commit

- `insert()`
  - Spanner > commit

- `replace()`
  - Spanner > commit

- `update()`
  - Spanner > commit

- `upsert()`
  - Spanner > commit

I've sent a PR that will do 2 things when complete:

1) Change all of the methods that call `commit` outside of a transaction, to instead create and commit the mutation inside of a transaction
2) Change the read methods that call `executeStreamingSql` and `streamingRead` to use a single use, strong read (by default) transaction

That PR is in progress here: #361. Please let me know if the above plan is correct.

**Comment by stephenplusplus** [comment]
The work is done: #361 

Step 2 wasn't necessary. By default, single-use, read-only, strong-concurrency transactions are used for `executeStreamingSql` and `streamingRead`.
