### ISSUE TITLE
Get the table schema with column names and types

### ISSUE THREAD

**Issue by chaitanya9186** [googleapis/nodejs-spanner#368]

**Comment by JustinBeckwith** [comment]
Greetings, and thanks for the issue!  We can't quite figure out if this is a question, a bug report, or a feature request :) If there's something we can do for you - we'd be happy to help! Just make sure to  fill out a complete bug report.

**Comment by chaitanya9186** [comment]
I have posted our use-case here: https://github.com/googleapis/google-cloud-node/issues/2873
