### ISSUE TITLE
Expose a method to get the schema from a Table

### ISSUE THREAD

**Issue by JustinBeckwith** [googleapis/nodejs-spanner#388]
_From @chaitanya9186 on October 15, 2018 23:55_

#### Environment details

  - OS: linux
  - Node.js version: v8.12.0
  - npm version: 6.4.1
  - google-cloud-node version: 2.1.0

#### Steps to reproduce

  1. require `google-cloud`
  2. Create a spanner table in a database with a FLOAT64 data type.
  3. try to insert/update with 1.00 or 1 through nodejs.

Use-case: User sends us data to insert as a JSON message, we do not have any knowledge of the table schema, we try to insert the same data as-it-is, so we are facing this error when the user is trying to insert/update the FLOAT64 cloumn with either an integer or value ends with .00 spanner is throwing following error: 
`Error: 9 FAILED_PRECONDITION: Invalid value for column score in table test1: Expected FLOAT64.`

I have gone through the suggestion here: https://github.com/GoogleCloudPlatform/google-cloud-node/issues/2307

But our problem is that we have no context of table schema, there is no Spanner API available to check the column types (as of my knowledge), I have created a FR: https://github.com/googleapis/nodejs-spanner/issues/368, but it was closed due to insufficient info. 

Please suggest a way to over come this. As you are accepting JSON data please fix this accordingly.

Making sure to follow these steps will guarantee the quickest resolution possible.
 
Thanks!

_Copied from original issue: googleapis/google-cloud-node#2873_

**Comment by stephenplusplus** [comment]
@callmehiphop I've been trying to figure this one out, and every step I've made seems unbelievable that something doesn't already exist. For example, you can get the DDL from a Database, then dig through the statements for a query that contains `CREATE TABLE {the name you're looking for}`. Then, you'll have the *original* schema, but it wouldn't contain any updates.

Is there anything I'm overlooking?

**Comment by crwilcox** [comment]
As best I can tell, there is likely an issue in how we convert/serialize these values in Node.js.

**Comment by stephenplusplus** [comment]
As far as I can tell, there is nothing we can do to resolve this. @callmehiphop could you take a quick look to see if any ideas strike you?

**Comment by callmehiphop** [comment]
I think in this situation I would suggest using a DML over `insert` and `update`. Those methods, which are conveniences for a Transaction commit, do not (currently?) accept types. We've always expected the user to provide the correct values so that we're able to infer the type. DML would be a good alternative since it currently accepts a `types` map, which when set, skips the clients type inference.

**Comment by callmehiphop** [comment]
@stephenplusplus as far as getting the schema goes, I managed to get the necessary information by querying against the [`INFORMATION_SCHEMA`](https://cloud.google.com/spanner/docs/information-schema).

Here's my query

```sql
SELECT column_name, spanner_type
FROM information_schema.columns
WHERE table_name="MyTable"
```

**Comment by crwilcox** [comment]
Schema information is in a schema table as specified by @callmehiphop. Closing this as resolved.
