### ISSUE TITLE
TypeError: rows.toJSON is not a function

### ISSUE THREAD

**Issue by nodegin** [googleapis/nodejs-spanner#409]
It looks the rows.toJSON is only available if using `database.run`. In my case I need to query for some data within a transaction, but the response is differ from database.run one

#### Environment details

  - OS: mac
  - Node.js version: v9.4.0
  - npm version: 6.4.1
  - `@google-cloud/spanner` version: 2.1.0

#### Steps to reproduce

  1. Start a transaction
  2. SELECT data with `transaction.run`
  3. call `rows.toJSON`

**Comment by nodegin** [comment]
@stephenplusplus I think this issue is still not resolved so shouldn't be closed.

This probably the same issue as #374, have you ever tried passing `json: true` to `transaction.run` query? It will not work as expected.

Also, the toJSON method is for rows not individual row. At least for `database.run`. I think your suggestion will not help to this issue, thanks.

**Comment by stephenplusplus** [comment]
Sure, I'll re-open so we can be sure this is solved!

I did try both code snippets I shared above to confirm they worked before I suggested. Would you mind showing code I can run that doesn't work as expected?

**Comment by stephenplusplus** [comment]
Sorry, I mistook the output from my `json: true` example for being correct JSON. Indeed, it looks like `json: true` isn't having an affect. We can let #374 track that issue.

> Also, the toJSON method is for rows not individual row. At least for `database.run`. I think your suggestion will not help to this issue, thanks.

This is actually designed to be used on the individual row. Did we have a slip in the code or docs somewhere that shows it being used on all of the rows at once? Any more information or samples here will help me understand. Thanks!

**Comment by nodegin** [comment]
Closing this as possibly duplicate with #374
