### ISSUE TITLE
.toJSON() does not convert Datetimes/Timestamp

### ISSUE THREAD

**Issue by BudickDa** [googleapis/nodejs-spanner#431]
When running toJSON on the response of a query in a cloud function, it does not serialises Datetimes (Timestamp in GC Spanner).

This is a problem, when I run my query in a Google Cloud Function (that I call in a webapp with firebase), the Datetime is not serialised and thus not returned to the client.

Cloud Function:
```
        return database.run(query).then(results => {
            const rows = results[0];
            const json = [];
            rows.forEach(row => {
                json.push(row.toJSON());                
            });
            console.log(json); // [ ...,  { name: 'received_at', value: 2018-10-23T22:21:22.000Z }, ...]
            return json;
        });
```

On the client:
```
            const cloudFunction = firebase.functions().httpsCallable('cloudFunction');
            const response = await cloudFunction();
            console.log(response); // {   data: [ ...,  { name: 'received_at', value: {}, ...] }
```

#### Environment details

  - OS: Google Cloud Function
  - Node.js version: 8
  - npm version: 6.4.1
  - `@google-cloud/spanner` version: 2.1

#### Steps to reproduce

  1. Run query on database with Timestamps and call .toJSON() on each row in cloud function
  2. return rows to client
  3. rows with Timestamp have an emtpy object ({}) as value

#### Possible Solution:
https://github.com/googleapis/nodejs-spanner/pull/432

**Comment by callmehiphop** [comment]
I've been thinking about this for a bit and I'm not actually sure if I think this is an issue for the client to fix. IIRC `row.toJSON()` isn't actually meant to serialize the row, but rather format the row data into an easier to use format.

@stephenplusplus @JustinBeckwith do you have any thoughts to add here?

**Comment by JustinBeckwith** [comment]
I defer to @crwilcox

**Comment by crwilcox** [comment]
@BudickDa I read through your initial post. I am going to repeat what I think it is going on and my conclusion. The short version is I believe this issue isn't in `@google-cloud/spanner`. It is possible cloud functions expects the returned object to already be serialized or there is an issue in the serialization of cloud functions.

I used v2.1.0 as you did and ran the following code

```
const query = {
  sql: 'SELECT * from date_test',
};

database.run(query).then(results => {
    const rows = results[0];
    const json = [];
    rows.forEach(row => {
        json.push(row.toJSON());
    });
    console.log(json);

    console.log("date:" + json[0].date)
    console.log("getTime:" + json[0].date.getTime())
    console.log("typeof date is Date:" + (json[0].date instanceof Date))
});
```

My table has two rows: 

| number (int64) | date | timestamp
----------|-----|-----------|
| NULL | 2018-11-25 | 2018-11-25T00:00:01Z
| 1 | 2018-11-26 | 2018-11-26T00:00:01Z

Running the code returns:
```
[ { date: 2018-11-25T00:00:00.000Z,
    timestamp: 2018-11-25T00:00:01.000Z,
    number: null },
  { date: 2018-11-26T00:00:00.000Z,
    timestamp: 2018-11-26T00:00:01.000Z,
    number: 1 } ]

date:Sat Nov 24 2018 16:00:00 GMT-0800 (Pacific Standard Time)
getTime:1543104000000
typeof date is Date:true
```

As best I can tell, the library is properly returning JSON with date objects having a type of Date. `toJSON` doesn't create a serializable format, it converts the list of `name, value` objects to a JSON accessible format to allow more idiomatic node use. 

is the source of the problem that you expected `.toJSON()` to output a serialized version of rows? If so, have you considered using `JSON.stringify(rows)`?

**Comment by crwilcox** [comment]
Closing this as I don't believe this is an issue. We intend to keep times as a typed date, not a string.
