### ISSUE TITLE
timestamps returned by the lib lose microsecond precision

### ISSUE THREAD

**Issue by pascaldelange** [googleapis/nodejs-spanner#494]
Hi,

When querying values from Spanner with the nodejs lib, all timestamps lose microsecond precision (they are truncated to milliseconds).
This makes pagination really painful on fields with commit timestamps, since truncating can create lots of cases where entries are missed/duplicate depending on the order.
Other languages (I tried python) properly keep microsecond precision.
Is this a know issue ?

  - OS: all
  - Node.js version: 10
  - `@google-cloud/spanner` version: 2.0

**Comment by JustinBeckwith** [comment]
FYI @crwilcox

**Comment by callmehiphop** [comment]
> Is this a know issue ?

It is now!

JavaScript dates only keep up to millisecond precision, so it looks like we are probably going to want to create a custom wrapper for timestamps.

I imagine it'll probably resemble the `SpannerDate` class

```ts
class SpannerTimestamp {
  value: string; // '2019-01-11T22:13:22.620145Z'
  toDate(): Date; // not recommended if precision is needed
}
```

Thoughts?

/cc @stephenplusplus

**Comment by crwilcox** [comment]
Python has a similar issue regarding precision. So all datetimes need to be handled using custom classes.

**Comment by pascaldelange** [comment]
> 
> Thoughts?
> 

This would do the job for me :)

> 
> Python has a similar issue regarding precision. So all datetimes need to be handled using custom classes.
> 
I'm pretty sure the problem is not there in python. The sdk returns python datetime objects that have precision up to microseconds (though they are not json serializable, which is another problem)
