### ISSUE TITLE
has no exported member 'GetMetadataCallback'

### ISSUE THREAD

**Issue by raphrmx** [googleapis/nodejs-spanner#537]
Multiple files imports the GetMetadataCallback class instead of MetadataCallback class.

- session.d.ts:20:36
- database.d.ts:17:42

#### Environment details

  - OS: All OS
  - Node.js version: 8.0
  - npm version: 6.8.0
  - `@google-cloud/spanner` version: 2.2.1
  - `@google-cloud/common` version: 0.31.0

#### Steps to reproduce

  1. npm i @google-cloud/spanner
  2. npm i @google-cloud/common
  2. tsc

```
> tsc

node_modules/@google-cloud/spanner/build/src/database.d.ts(17,42): error TS2305: Module '"../../../common/build/src"' has no exported member 'GetMetadataCallback'.
node_modules/@google-cloud/spanner/build/src/session.d.ts(20,36): error TS2305: Module '"../../../common/build/src"' has no exported member 'GetMetadataCallback'.
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! functions@ build: `tsc`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the functions@ build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-02-21T10_00_54_990Z-debug.log

Error: functions predeploy error: Command terminated with non-zero exit code2
ERROR: Job failed: exit code 1
```

To fix this issue, i change `GetMetadataCallback` imports to `MetadataCallback` on @google-cloud/spanner module.

Thanks!

**Comment by callmehiphop** [comment]
Looks like the change you suggested was already implemented in `master`, just need to cut a new release. Thanks!
