### ISSUE TITLE
Transaction.insert generates unhandled promise rejections

### ISSUE THREAD

**Issue by WaldoJeffers** [googleapis/nodejs-spanner#55]
#### Environment details

  - OS: hmm... Google Cloud Platform?
  - Node.js version: 8.9.x
  - npm version: yarn 1.1
  - @google-cloud/spanner version: 0.8.1

#### Steps to reproduce

  1. Create a read-write transaction
  2. Use transaction.insert, but insert data which do not match the destination table's schema
  3. Run transaction.commit()

This will generate an unhandled promise rejection, which does **not** come from `commit()`.

My code (simplified) looks like this:
```js
try {
   transaction.insert('tableName', {fakeData: 'rejected!'});
   await transaction.commit();
} catch(error){
  ...
}
```

[According to the docs](https://cloud.google.com/nodejs/docs/reference/spanner/0.8.x/Transaction#insert), `insert` does not seem to accept a callback. However, it [looks like it accepts a callback parameter in the source code](https://github.com/googleapis/nodejs-spanner/blob/master/src/transaction-request.js#L450).

So I tried adding a `catch` after the insert:
```js
transaction.insert('tableName', {fakeDate: 'rejected!'}).catch(...); // No unhandled promise rejection
```
This does seem to catch the error. However, the rest of the code is still executed synchronously.
So I tried this:
```js
try {
   await transaction.insert('tableName', {fakeData: 'rejected!'}); // Use await instead of catch
   await transaction.commit();
} catch(error){
  ...
}
```

The error is caught, but if there's no error, await (or the associated promise) never resolves!
```js
try {
   await transaction.insert('tableName', {validData: 'should be good!'}); // hangs forever
   await transaction.commit();
} catch(error){
  ...
}
// Unhandled promise rejection
```

It seems like:
- `insert()` in fact accepts a callback
- A `resolve` is missing somewhere if the insert is a success

Thanks for your help!

**Comment by callmehiphop** [comment]
@WaldoJeffers I'm sorry to hear you're running into this issue! While other objects that inherit Transaction methods do allow for one to supply a callback, when using an actual Transaction object they are not required (and I believe the client will ignore them).

Looking through your samples, I think the issue is that you're forgetting to specify a table name:

```js
try {
   transaction.insert('MyTable', {validData: 'should be good!'});
   await transaction.commit();
} catch(error){
  ...
}
```

**Comment by WaldoJeffers** [comment]
@callmehiphop Thanks for your quick reply. I oversimplified my code 😨 But my actual does use a table name :) I edited my examples

**Comment by callmehiphop** [comment]
@WaldoJeffers Oh! I just meant that it ignores callbacks for CRUD methods, commit is definitely async.

**Comment by WaldoJeffers** [comment]
My bad again, I meant to say `transaction.insert()`.

**Comment by callmehiphop** [comment]
@WaldoJeffers that's a good point, I would expect that to throw an error as well! I'm going to open a PR with a fix shortly.

**Comment by callmehiphop** [comment]
@WaldoJeffers I've opened #56, if you have the bandwidth the test the changes and see if your issue is resolved, I would be very grateful!

**Comment by WaldoJeffers** [comment]
@callmehiphop will do, thanks

**Comment by WaldoJeffers** [comment]
@callmehiphop This does indeed seem to fix this issue.
To be clear, this is a very important fix. It does a lot more than making `transaction.insert(...).then/catch` now properly throw `Cannot read property then/catch of undefined`. Prior to your fix, insertion errors were caught by `transaction.insert` but not thrown anywhere, resulting in a `Unhandled promise rejection` error.
I recommend merging this fix as fast as possible, as it is a critical bug.

Thanks a **lot** for your reactivity 👏

**Comment by vkedia** [comment]
I do not understand how were insertion errors caught by `transaction.insert` previously? `transaction.insert` just buffers mutation in  memory and it does not know whether anything is incorrect. It is only `transaction.commit` that would fail. Can someone please explain what was going on?

**Comment by callmehiphop** [comment]
@vkedia I think @stephenplusplus will have a better idea why we do it, but when we buffer the mutation if there's a mismatched number of columns [we throw an error](https://github.com/googleapis/nodejs-spanner/blob/master/src/transaction-request.js#L754).

So I assume if you give bad data that contains a non-existing column, a mistmatch error would occur and then the promise would swallow it.

**Comment by stephenplusplus** [comment]
That comes from https://github.com/GoogleCloudPlatform/google-cloud-node/pull/2426#issuecomment-312392124. Since it's a thrown error, you would wrap it in a `try {} catch(e) {}` if you were uncertain about the data being fed to the mutation method.

**Comment by WaldoJeffers** [comment]
To be more specific, the error thrown looks like this:
`Column not found in table TABLE_NAME: UNKNOWN_COLUMN`.

**Comment by vkedia** [comment]
@stephenplusplus @callmehiphop that makes sense.
But the error message given by @WaldoJeffers looks different. This is thrown by the server and would be thrown on commit.

**Comment by stephenplusplus** [comment]
For the immediate future, we should release #56, as that is an unquestionable fix brought up during this bug report.

@WaldoJeffers, thanks for helping us out. Would you mind throwing together a clone-and-runnable snippet, so we can get a wider context of where this problem is introducing itself? Please base it off of #56 (`npm install callmehiphop/nodejs-spanner#dg--55` to make that easier).

**Comment by vkedia** [comment]
I agree releasing #56 is non controversial.

**Comment by WaldoJeffers** [comment]
Ok, I think I might have a better reproducible case here. Some information I reported earlier were erreneous/incomplete, apologies.
Trying to insert into a **non-existing** column with a **defined** value works, both with & without @callmehiphop 's fix. The server correctly returns `Column not found in table TABLE_NAME: UNKNOWN_COLUMN` and there is **no** `Unhandled promise rejection` notice.
```js
transaction.insert('existingTable', {nonExistingColumn: undefined}) // works!
``` 


However, trying to insert into a **non-existing** column with an **undefined** value does **not** work without the fix.
```js
transaction.insert('existingTable', {nonExistingColumn: undefined}) // doesnt work!
``` 
will result in:
```
(node:2866) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Value of type undefined not recognized.
(node:2866) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Using the fix, the error is correctly thrown by `transaction.commit()`: `Value of type undefined not recognized.` The error is thrown by the `common-grpc` module [here](https://github.com/GoogleCloudPlatform/google-cloud-node/blob/master/packages/common-grpc/src/service.js#L934)

**Comment by vkedia** [comment]
Thanks. I think this explains why the error was being thrown by `insert` and not `commit`.
