### ISSUE TITLE
table.upsert occasionally fails with mysterious error.

### ISSUE THREAD

**Issue by peter-fingo** [googleapis/nodejs-spanner#579]
#### Environment details

  - OS: Firebase cloud functions
  - Node.js version: 8
  - npm version: 6.7.0
  - `@google-cloud/spanner` version: 3.1.0

```
    const db = instance.database(db_id);
    const table = db.table(table_id);
    try {
        await table.upsert(rows);
    } catch (err) {
...
```

Occasionally this produces `Cannot find affinity value from proto message using affinity_key: name.` , which is a very mysterious error.

**Comment by callmehiphop** [comment]
@crwilcox is there anyone on the Spanner team we could ask about this?

**Comment by peter-fingo** [comment]
This is probably related to kicking off the process without waiting for the result, possibly leading to environment during the upsert. After waiting for completion, we don't see these errors; it's still very mysterious how they're produced.

**Comment by praveenqlogic01** [comment]
@peter-fingo Hi, are you still facing this issue?

**Comment by peter-fingo** [comment]
We have changed our code to avoid this; I don't know if it still occurs without that.

**Comment by stephenplusplus** [comment]
Since this is a tricky one to reproduce, and we haven't had more reports, it could be safe to close. If I'm mistaken, please let us know so we can re-open and investigate.
