### ISSUE TITLE
process hangs

### ISSUE THREAD

**Issue by Chipintoza** [googleapis/nodejs-spanner#61]
OS: Mac OSX 10.13.1
Node.js version: 8.9.1
npm version: 5.6.0
version: 0.9.0

test.js
```
var instance = spannerClient.instance('my-instance');
var database = instance.database('my-database');

database.run("SELECT 'test`", () => {});
```

if you run: 

> node test.js

process hangs

**Comment by callmehiphop** [comment]
@Chipintoza we made some big changes under the hood for 0.9.0, so now when you're done with a `database` object you'll need to call `close` or else it will hang until all the sessions die.

**Comment by callmehiphop** [comment]
I'm going to close this, but if closing the database doesn't resolve your issue let me know and I'll re-open and investigate.

**Comment by vkedia** [comment]
I am not sure this is ideal. Why should the process hang? I agree that not calling `database.close` is bad since it will cause sessions to leak but penalty for that should not be hung process.

**Comment by callmehiphop** [comment]
@vkedia `setInterval`/`setTimeout` cause node processes to stay open, this is what we are using to perform keep alives.

**Comment by vkedia** [comment]
I see. Is there some way to be notified that the process is trying to shutdown and then cancel the Timers in that notification?

**Comment by vkedia** [comment]
Would this work:
https://nodejs.org/en/docs/guides/timers-in-node/#leaving-timeouts-behind

**Comment by callmehiphop** [comment]
Actually yes! I'll add that in right now.

**Comment by vkedia** [comment]
Thanks!

**Comment by Chipintoza** [comment]
@callmehiphop thank you
