### ISSUE TITLE
14 UNAVAILABLE: GOAWAY received

### ISSUE THREAD

**Issue by WaldoJeffers** [googleapis/nodejs-spanner#620]
#### Environment details

  - OS: Linux
  - Node.js version: 10
  - yarn version: 1.15
  - `@google-cloud/spanner` version: 3.1.0

#### Steps to reproduce

  1. Run a web service using nodejs-spanner
  2. Observe random 14 UNAVAILABLE: GOAWAY errors

It happens 1-5 times a day

The full stacktrace is 
```
14 UNAVAILABLE: GOAWAY received Error: 14 UNAVAILABLE: GOAWAY received
    at Object.exports.createStatusError (/app/node_modules/grpc/src/common.js:91:15)
    at ClientReadableStream._emitStatusIfDone (/app/node_modules/grpc/src/client.js:233:26)
    at ClientReadableStream._receiveStatus (/app/node_modules/grpc/src/client.js:211:8)
    at Object.onReceiveStatus (/app/node_modules/grpc/src/client_interceptors.js:1272:15)
    at InterceptingListener._callNext (/app/node_modules/grpc/src/client_interceptors.js:568:42)
    at InterceptingListener.onReceiveStatus (/app/node_modules/grpc/src/client_interceptors.js:618:8)
    at Object.onReceiveStatus (/app/node_modules/grpc-gcp/build/src/index.js:93:25)
    at InterceptingListener._callNext (/app/node_modules/grpc/src/client_interceptors.js:568:42)
    at InterceptingListener.onReceiveStatus (/app/node_modules/grpc/src/client_interceptors.js:618:8)
    at /app/node_modules/grpc/src/client_interceptors.js:1029:24
```

Interestingly, we had a very similar error (`13 INTERNAL: GOAWAY`) when using node-spanner v2.x. We were hoping to see this error disappear by upgrading, which it did, but it apparently got replaced by this one ^^

It might be related to https://github.com/googleapis/nodejs-spanner/issues/234 or to any of these issues https://github.com/grpc/grpc-node/issues?utf8=%E2%9C%93&q=is%3Aissue+GOAWAY+

**Comment by WaldoJeffers** [comment]
Hello, any news on this? It's still happening every day. Is there anything I can do which would help understanding the issue?

**Comment by bcoe** [comment]
@AVaksman any thoughts on this one?

**Comment by AVaksman** [comment]
It is a transient error [gRPC - 14](https://developers.google.com/maps-booking/reference/grpc-api-v2/status_codes).
This error is auto retryable by default (if `autoRetry` is not manually disabled on the client, [link](https://cloud.google.com/nodejs/docs/reference/spanner/1.5.x/global#ClientConfig))
Recommendation would be to try increasing `maxRetries` value on the client or to implement a retry logic in your application.

**Comment by AVaksman** [comment]
The GOAWAY could be caused by the keepalive settings. If add `GRPC_TRACE=all` and `GRPC_VERBOSITY=ERROR` environment variable, you may get more information about the error that can help determine the root cause.

**Comment by WaldoJeffers** [comment]
Hello @AVaksman , thanks for the suggestion, I'll add those env variables right away. I'm not sure when I'll be able to post an update on this, as we get those errors really erratically.

Here's a screenshot for the last 30 days:
![image](https://user-images.githubusercontent.com/7644970/60967732-a0479100-a31b-11e9-8dc6-eacdf323115c.png)

**Comment by WaldoJeffers** [comment]
Hello again @AVaksman , sorry if that's a stupid question, but where would the extra logs appear?
We had the error again today, and I can't seem to find any new information :/

This is from StackDriver:
![image](https://user-images.githubusercontent.com/7644970/61153889-e6a01a00-a4ec-11e9-969d-948ad194cb76.png)

**Comment by Duncan00** [comment]
We got similar problem, will try to increase `maxRetries` to see whether can resolve.
https://googleapis.dev/nodejs/spanner/latest/global.html#ClientConfig

**Comment by bcoe** [comment]
@WaldoJeffers :wave: I would expect the detailed logging to show up as `console.info` level logs in your stackdriver logging.

Have you been continuing to see these issues over the past couple months?

**Comment by rzeng95** [comment]
Hi! If `14 UNAVAILABLE: GOAWAY` is considered transient, should it be added to the list of retryable status codes here? 
https://github.com/googleapis/nodejs-spanner/blob/v4.2.0/src/transaction-runner.ts#L29

And if it isn't considered retryable, how can we best handle these errors within `runTransactionAsync`? Thanks!

**Comment by WaldoJeffers** [comment]
@bcoe Sorry for the late reply. Yes I can confirm we are still seeing very regularly across all our services, which use different versions of the `nodejs-spanner` library. Could this error be linked to specific versions of the library, or is it unrelated?

**Comment by bcoe** [comment]
looping in @olavloite as well, who's been doing a lot of work on the library recently.

@WaldoJeffers I would definitely suggest you try to get on the latest version of Node.js spanner, if possible, there have been a variety of fixes to `gRPC` over the past two months, so the version can definitely have an impact.

**Comment by olavloite** [comment]
@WaldoJeffers After some digging and debugging I think I've found the reason for this. It occurs if the backend returns an `UNAVAILABLE` error for a streaming RPC before that streaming RPC has returned a resume token. The Node client only retries a streaming RPC if it has already received a resume token, but it is also possible to retry the streaming RPC before it has received a resume token by restarting the entire stream. I'll submit a fix in the coming days.

Note: A streaming RPC in this case basically means any call that executes a SQL statement, as the Spanner client uses the RPC executeStreamingSql for both queries and DML statements. The only exception is the execution of batched DML statements, which uses a separate RPC.
