### ISSUE TITLE
Docs build is failing

### ISSUE THREAD

**Issue by hegemonic** [googleapis/nodejs-spanner#621]
It appears that documentation builds are failing at the moment. See #618 for an example.

I maintain JSDoc and `jsdoc-baseline`, so I can take a look at this later today or early tomorrow. If someone else wants to dig into this sooner, please ping this issue so I don't duplicate your efforts.

**Comment by JustinBeckwith** [comment]
Huh, on my local machine, against master, this appears to be working fine.  It also appears to be passing on master:
https://source.cloud.google.com/results/invocations/f5a617b7-c497-4e7b-b223-32f8cd40a8f1/targets/cloud-devrel%2Fclient-libraries%2Fnodejs%2Fcontinuous%2Fgoogleapis%2Fnodejs-spanner%2Fnode10%2Fdocs/log

Can you try running `npm run docs` locally on master?  Is it possible there's a problem with the PR?

**Comment by bcoe** [comment]
I believe the underlying issue is [this](https://github.com/hegemonic/jsdoc-baseline/pull/195): If we could get this landed it would unblock quite a few builds.

**Comment by JustinBeckwith** [comment]
This should be addressed 🙌
