### ISSUE TITLE
Spanner response degrades every one hour seemingly caused b all sessions in the pool being deleted at once

### ISSUE THREAD

**Issue by voltrue2** [googleapis/nodejs-spanner#649]
#### Environment details

  - OS: Alpine (GKE)
  - Node.js version: 10.15.1
  - npm version: 6.4.1
  - `@google-cloud/spanner` version: 3.1.0

#### Steps to reproduce

  1. Establish some connections to Spanner using the library with credential.json file.
  2. Keep executing queries (type of queries and frequencies do not matter)
  3. Wait for an hour or so until see see the response time of Spanner server increases greatly for a few seconds.

The following is the code that we suspect not working correctly:

```javascript
_isValidSession(session) {
    // unpinged sessions only stay good for 1 hour
    const MAX_DURATION = 60000 * 60;

    return Date.now() - session.lastUsed < MAX_DURATION;
  }
```

We believe that the sessions in the pool are deleted every hour regardless of their `lastUsed` value, and that is causing all sessions to be re-created at the same time resulting in the response slow down.

Cheers!

**Comment by callmehiphop** [comment]
Have you checked the cloud console to see if there's a spike in create session requests on the hour? I wonder if you're getting held up by ping/keep alive requests.

**Comment by voltrue2** [comment]
@callmehiphop 
Thank you for the response. We did indeed look at the number of sessions on the hour.
The number of sessions do not spike at all as far as we could, which, means that the response latency spikes may not be caused by session creation after all...

You mentioned that we might be help up by ping/keep alive requests, is there a way for us to see if that is the case?

Cheers!

**Comment by callmehiphop** [comment]
@voltrue2 yep! We ping the sessions by making an `ExecuteSql` call with the query `SELECT 1`. As far as I know this is the only place in Spanner we make this kind of request, for everything else we use the `ExecuteStreamingSql` rpc.

**Comment by sduskis** [comment]
Doesn't the gRPC connection shut down every hour?

**Comment by callmehiphop** [comment]
@sduskis that is the first I've ever heard of gRPC doing that, but if that is the case it would make a lot of sense.

**Comment by sduskis** [comment]
@callmehiphop, it's a server-side "feature" for all Google Cloud products.

**Comment by callmehiphop** [comment]
@sduskis good to know! Unfortunately that means there is probably nothing we can do here if that is the root cause.

**Comment by voltrue2** [comment]
@sduskis Thanks for the info. Is there some documentation on that I can read?
Cheers!

**Comment by voltrue2** [comment]
It seems there is really nothing to do on the client-side.
Cheers guys. I am closing this issue now.

**Comment by callmehiphop** [comment]
Thanks @voltrue2, let us know if there's anything else we can do!
