### ISSUE TITLE
Spanner: Adjust timeouts for CreateDatabase and retries for other methods

### ISSUE THREAD

**Issue by crwilcox** [googleapis/nodejs-spanner#652]
As part of a recent change to GAPIC Configuration, timeouts and retries need to be updated. 

Ensure that the timeouts and retries specified in https://github.com/googleapis/googleapis/commit/cc233544aa39b8947c9b929819aeb08e2cb71feb#diff-4501db3e3507bcce8496c9aea2017d96 are reflected in this client library.

**Comment by skuruppu** [comment]
We've adjusted the timeouts and retries in [spanner_gapic.yaml](https://github.com/googleapis/googleapis/blob/master/google/spanner/v1/spanner_gapic.yaml) and the client libraries should all be using those consistently. Will close this bug and open a new issue if Node.js client library needs to be configured differently.
