### ISSUE TITLE
Lots of public methods are missing from the Table API docs

### ISSUE THREAD

**Issue by hegemonic** [googleapis/nodejs-spanner#664]
The API docs on `googleapis.dev` omit many public methods from the `Table` class, both in [4.0.0](https://googleapis.dev/nodejs/spanner/4.0.0/Table.html) and in [3.1.0](https://googleapis.dev/nodejs/spanner/3.1.0/Table.html). In contrast, the [2.2.x docs](https://cloud.google.com/nodejs/docs/reference/spanner/2.2.x/Table) included the missing methods.

It looks like the source file that gets fed to JSDoc doesn't have any block comments for lots of methods that should be commented. [Here's an example](https://googleapis.dev/nodejs/spanner/4.0.0/table.js.html#source-line-139).

I don't know whether this issue affects multiple classes, or just `Table`. (I only noticed the issues with `Table` because the `cloud.google.com` link checker told me about them.)

**Comment by bcoe** [comment]
see: https://github.com/microsoft/TypeScript/issues/10385 I believe this is related; I see the comments being removed from generated docs even though they shouldn't be.

**Comment by bcoe** [comment]
@hegemonic we figured out the issue in our weekly chat today; overridden methods need to live above the main function entry point, or else they're dropped during compilation. The solution is shuffling the comment around accordingly.

It might be worth opening an issue on TypeScript still, but it's a different issue than 10385

**Comment by hegemonic** [comment]
Good times! If you can share an example that demonstrates the workaround, I can do the legwork of filing the TypeScript bug. (Or someone on your team who actually understands TypeScript can file it. 😄 Up to you.)

**Comment by bcoe** [comment]
@hegemonic here's an example:

https://github.com/googleapis/nodejs-pubsub/blob/master/src/pubsub.ts#L286

see how `createSubscription`'s method overrides are all listed above the `createSubscription` with the brunt of the function body?

**Comment by bcoe** [comment]
@hegemonic I'll let you and @callmehiphop coordinate in this thread; but if you get to this before anyone else, and have the cycles, I will happily land your patch.

Dave describes it as the sort of thing where we periodically forget we need to do this, and break things; so the more folks that know how to fix it the better.
