### ISSUE TITLE
no matching version found for @google-cloud/spanner@0.9.1

### ISSUE THREAD

**Issue by Chipintoza** [googleapis/nodejs-spanner#70]
OS: Mac OSX 10.13.1
Node.js version: 8.9.1
npm version: 5.6.0
version: 0.9.0

0.9.1 is not published on npm

**Comment by callmehiphop** [comment]
@Chipintoza we've been having some CI troubles, which is supposed to publish the releases for us. I've just manually published 0.10.0 if you want to try upgrading to that.

**Comment by Chipintoza** [comment]
@callmehiphop thanks
