### ISSUE TITLE
Error querying Spanner: Error: Stream removed

### ISSUE THREAD

**Issue by bricktownseo** [googleapis/nodejs-spanner#76]
#### Environment details

  - OS: Cloud Function
  - @google-cloud/spanner version: 0.10.0

#### Steps to reproduce

  1. Downloaded the example spanner cloud function code
  2. Modify the package.json to use version 0.10.0 of spanner
  3. Deploy to cloud function and test
  4. After >5 minutes at idle, running the cloud function on the first request causes the "Error: Stream removed" to fire. All subsequent requests execute perfectly normal.

Code from sample with modifications below.

```js
'use strict';

const Spanner = require('@google-cloud/spanner');
const spanner = Spanner();
const instanceId = 'OUR_INSTANCE_ID';
const databaseId = 'OUR_DATABASE_ID';

exports.get = (req, res) => {
  const instance = spanner.instance(instanceId);
  const database = instance.database(databaseId);
  const query = {
    sql: 'SELECT * FROM Phones'
  };

  return database.run(query)
    .then((results) => {
      const rows = results[0].map((row) => row.toJSON());
      rows.forEach((row) => {
        res.write(`Row: ${JSON.stringify(row)}\n`);
      });
      res
        .status(200)
        .end();
    })
    .catch((err) => {
      res
        .status(500)
        .send(`Error querying Spanner: ${err}`)
        .end();
    });
};
```

Update: Issue also occurs on App Engine

Related to https://github.com/grpc/grpc-node/issues/130

**Comment by bricktownseo** [comment]
This issue also happened with version 0.9 as well.

**Comment by stephenplusplus** [comment]
The issue is with 1.8.x of grpc. Until it is resolved, we are in the process of locking it down to 1.7.x.

(Duplicate: https://github.com/googleapis/nodejs-datastore/issues/35) I'm going to close and lock, just to keep any additional reports/comments on a single issue. I'll tag your name in the other issue so you're subscribed and can track the progress.
