### ISSUE TITLE
SessionPool acquireQueue concurrency limit causes sessions to pile up under load

### ISSUE THREAD

**Issue by PacciniBruno** [googleapis/nodejs-spanner#78]
#### Environment details

  - OS: MacOS
  - Node.js version: 9.2.0
  - @google-cloud/spanner version: 0.10.0

#### Steps to reproduce

1. Run a simple load test at a rate that fills up the pool of available sessions (40 req/s was enough for me, with current session pool settings)
2. After a little while you'll start to see requests taking a disproportionate amount of time (dozens of seconds) to respond, or even timeouts.

Not sure I have the right analysis of what is happening but here's what I understand:

- With the current session pool option defaults, the pool starts with 0 (min) open sessions, so it fills up pretty quickly and the session pool starts acquiring new sessions (https://github.com/googleapis/nodejs-spanner/blob/master/src/session-pool.js#L660)

- `requestQueue_` has a configurable rate limit with a sensible default, which is fine, but calls to `createSession` are queued in `acquireQueue_` (https://github.com/googleapis/nodejs-spanner/blob/master/src/session-pool.js#L778), which has a limit of 1 concurrent operation.

- So in effect, at load, `acquireQueue_` seems to become a bottleneck, where requests to create new sessions pile up. 

What's worrying is that queued `createSession` calls stay there piling up, even when previously busy sessions are now available. (Can even become a memory leak problem)

The session pool will wait and resolve each session creation one at a time, and because creating a new session takes time, clearing the queue takes a very long time (assuming request load has dropped, otherwise it will never get cleared), causing a good amount of requests to timeout. 

When I tested, I couldn't get over **30 req/s**, after which I started seing connection timeouts and requests responding after several dozen seconds

After setting `concurrency` for the `acquireQueue_` to 10, I could get the load to about **80 req/s**.
I suspect increasing `min` and `acquireQueue_` concurrency would allow to go even higher.

Hope it helps !

**Comment by vkedia** [comment]
@PacciniBruno  Thanks for the detailed analysis.
@callmehiphop Ideally this is the kind of thing the benchmark would catch. Why did we not run into this while running the benchmark in #54 ? Also we should run that benchmark with and without your fix to see how much it changes the performance.

**Comment by callmehiphop** [comment]
@vkedia truthfully I wasn't sure what kind of metrics I should be looking for from the benchmark. But yeah, I think testing against that is a great idea!

**Comment by danoscarmike** [comment]
@callmehiphop what's the next action here?  Can we merge #79 ?

**Comment by callmehiphop** [comment]
@danoscarmike yes, it should be safe to merge.
