### ISSUE TITLE
RowBuilder.toJSON should return un-wrapped Floats and Ints

### ISSUE THREAD

**Issue by WaldoJeffers** [googleapis/nodejs-spanner#80]
#### Environment details

  - OS: MacOS
  - Node.js version: 9.2.0
  - npm version: 5.6.0
  - @google-cloud/spanner version: 0.10.0

#### Steps to reproduce

  1. Make a query which returns rows containing numeric values
  2. Run `rows.map(row => row.toJSON())`
  3. The results should look something like that (field names do not matter, this is just an example):

```json
{
  "markedAsPaid": false,
  "note": "Hello",
  "paid": false,
  "paidAt": {
    "value": "0"
   },
   "startAt": {
      "value": "1513013430444"
   },
}
``` 
As you can see, the `toJSON` method correctly formats all types, except for numeric values. It instead returns an object with a `value` property containing the desired output value. This issue might have links with #27.

Also, every [`RowBuilder` method's documentation page is a 404](https://cloud.google.com/nodejs/docs/reference/spanner/0.10.x/RowBuilder#toJSON) 😢.

Thanks for your help 😄 

 

PS: This issue template asks for the`@google-cloud/spanner version`, but GitHub tries to search a `google-cloud/spanner` user, and dismisses this string as it can not find one. The `@` symbol should be escaped or removed 😄

**Comment by stephenplusplus** [comment]
Numbers stored in Spanner can go outside the boundaries of what a JavaScript Number can hold. To support this, we use custom types [Spanner.int](https://cloud.google.com/nodejs/docs/reference/spanner/0.10.x/Spanner#.int) and [Spanner.float](https://cloud.google.com/nodejs/docs/reference/spanner/0.10.x/Spanner#.float).

You can see how values are treated here: https://github.com/googleapis/nodejs-spanner/blob/dbf026e7645f54ca5191b9009c2dc91723b5b716/src/codec.js#L44-L66

Regarding the docs, another team is still working on the kinks.

Thanks for the tip on the issue template.

**Comment by WaldoJeffers** [comment]
Thanks for your quick answer @stephenplusplus . But is this the way you want toJSON to work? I mean, it's not what you expect from a toJSON method. I'd rather expect this:
```json
{
  "markedAsPaid": false,
  "note": "Hello",
  "paid": false,
  "paidAt": 0,
   "startAt":  1513013430444",
}
```

In my team, we had to implement our custom toJSON method to deal with this. Is it intended?

**Comment by WaldoJeffers** [comment]
To be more specific, the `valueOf` methods on `Int` and `Float` do *not* get called when `toJSON` is called. The `toString` method is called instead, and returns a JSON serialization, which looks like:
```
{
  "value": xxxxx
}
```

**Comment by stephenplusplus** [comment]
Unfortunately, yes. If we only return a string, the JS Number characteristics are lost:

```js
var values = row.toJSON()

values.numUsers
// { value: "100" }

++values.numUsers
// 101
```

We could rename the method to "row.toObject()" if using the name "toJSON()" is misleading. Although, the value types we return from the method is compliant with this interpretation/definition of how a `toJSON()` method is to be defined: https://derickbailey.com/2015/10/26/dont-return-a-json-document-from-the-tojson-method/

If we called `valueOf()` early on a row with an invalid number, this would throw:

```js
var values = row.toJSON()
// throws number is out of bounds error
```

I think it's more valuable to return the values in their custom type objects, and if you need to stringify them, using your own toJSON() method is perfectly reasonable.

**Comment by WaldoJeffers** [comment]
I understand, thanks again for your detailed explanation @stephenplusplus.

In my opinion (and I completely understand if you and your team have a different view on this), the (vast) majority of users will handle numeric values which are not out bounds, and will have to use to write a custom toJSON implementation. If you are expecting out of bounds values from your DB, you know you'll need to take care of them down the pipe anyway and write custom handlers, so I think I would encourage users facing this issue to roll out their own implementation. 

Basically, with the current implementation, I feel it will be useless to every user, because you can't code the rest of your app to try to read a `value` property on every JSON object it receives. On the contrary, using the implementation I suggest, only a small percentage would have to write a custom implementation.

Or maybe there could 2 different helper functions? Or an option passed to `toJSON` to handle out of bounds values?

In our case, we use this utility function in almost all our micro-services, and have to use our custom implementation every time, which we feel sad about. I really think there will be other people facing the same problem in the future.

I hope my explanation is clear, and again, I understand if you have a different view on this, at least we can understand the reasoning behind this 👍

**Comment by vkedia** [comment]
I think @WaldoJeffers has raised a valid concern. Can we discuss what are the options here and if we can somehow make things easier for users.

**Comment by stephenplusplus** [comment]
toJSON taking an option to treat all numbers as JS Numbers seems brilliant. I would suggest we default to that behavior, and the option would disable it and return the custom type.

**Comment by vkedia** [comment]
Why not add a different method for this purpose (which behaves the same as current toJson) and change toJson to treat numbers as JS numbers? That seems clearer to me than adding an option.

As an aside, we should also document clearly how does toJson handle missing field names and duplicate field names.

**Comment by stephenplusplus** [comment]
That seems like a matter of preference; I’m not sure I have a strong enough reason for either way. Take it to a vote? Unless there’s a clear reason a separate method is better.

**Comment by alexander-fenster** [comment]
Can we try to make it easy to use for the majority of users (those who never meets large integers), but still leave the possibility to deal with large integers (e.g. via the apiResponse).

**Comment by stephenplusplus** [comment]
`row.toJSON({ wrapNumbers: true })` (better names welcome) or a new method, name TBD (ideas @vkedia?), would be much easier for the users than trying to parse through the API response. As long as `toJSON()` without any arguments returns JS Numbers, and not our custom type, the majority of users will be in for a better experience.

**Comment by WaldoJeffers** [comment]
Couldn't agree more @stephenplusplus 😄 Maybe `wrapNumbers` could also accept a function? It could save users handing out of bounds numbers the trouble of rewriting the entire `toJSON` serialization just to handle large numbers with a custom helper function. 
But maybe this would add too much complexity.

Regarding names, a few suggestions if you need them:
- protectNumbers
- stringifyNumbers (if all numbers are returned as strings)
- safeMode

wrapNumbers is also fine.

**Comment by stephenplusplus** [comment]
```js
var values = row.toJSON({ stringifyNumbers: true })
values.numUsers // '8'
```

That SGTM. @callmehiphop ?

**Comment by vkedia** [comment]
Yeah I think taking an option is fine. It also allows us to take more options if needed in future. For eg currently if there are multiple fields with the same name, we just pick the last one. In future we can take an option to instead return a list.
To be clear the default for `stringifyNumbers` would be `true` which means we would return JS numbers and not spanner.Int. Is that correct?

**Comment by stephenplusplus** [comment]
`stringifyNumbers: true` would return a string for all numbers. By default, it would be false, so that we return `8` instead of `"8"`. We wouldn't return the custom type from `toJSON()` at all.

```js
var values = row.toJSON({ stringifyNumbers: true })
row.numUsers // '---oversized integer---' (a string)

// Save as part of a new row
var numUsersInt = spanner.int(row.numUsers)
table.insert({ numUsers: numUsersInt })
```

We could go back to something like `wrapNumbers` which would default to false. If enabled, it would return the `spanner.int`:

```js
var values = row.toJSON({ wrapNumbers: true })
row.numUsers instanceof spanner.int // true
row.numUsers // { value: '---oversized integer---' }

// Save as part of a new row (no conversion to `spanner.int` necessary)
table.insert({ numUsers: row.numUsers })
```

**Comment by vkedia** [comment]
I see and if `stringifyNumbers` is false and the number is oversized what would happen?

**Comment by stephenplusplus** [comment]
The number would simply be incorrect:

```sh
$ node
> 10765432100123458001
10765432100123458000
> 10765432100123459999
10765432100123460000
```

**Comment by vkedia** [comment]
That sounds dangerous. Why can be not throw an error in this case?

**Comment by stephenplusplus** [comment]
We could throw an error during the `toJSON()` call:

```js
try {
  row.toJSON()
} catch(e) {
  // e.message = 'The value of "numUsers" was out of bounds. Use the `stringifyNumbers` option to receive this value as a string.'
}
```

I don't think we would want to show the `try/catch` behavior in our documentation, for example. A user would only want to do that if they're concerned a row may have an out of bounds integer.

**Comment by WaldoJeffers** [comment]
Throwing an error sounds like a good idea. Otherwise, it could lead to bugs which would be very hard to detect. If you choose not show this example in the docs (sounds reasonable), I think it could be interesting to at least mention that  `toJSON` can throw (and why).

**Comment by alexander-fenster** [comment]
So let me clarify here that when we are discussing things like 'to throw or not to throw', we are talking about something that will affect 1% of users or less, those who meet the large integers. Let's state some points:

- We don't want 99% of users to do any extra work with their numbers
- Returning spanner.int is better than returning just a string because it kind of gives a little bit more information (like, that's still an integer, not some random string)
- This kind of errors are very difficult to debug, so if it's possible to notify the users when something goes wrong with the numbers, we should do so.

So the solution I would vote for is:

- make the default behavior convert numbers to regular JavaScript Numbers (8 in the example above)
- have an option that would wrap all numbers to `spanner.int` (`wrapNumbers` above), making this `{ value: '8' }`
- throwing an exception if an integer greater than `Number.MAX_SAFE_INTEGER` is converted to a Number
- clearly documenting this behavior, something like this:

> Note that due to Javascript limitation the large integers cannot be represented as Number object without losing precision. If such an integer is received, conversion to Number will throw an exception `WhateverException`. To avoid that, if you expect to see large integers, use the `wrapNumbers` option to convert all integers to `spanner.int`.

Does it sound reasonable?

**Comment by alexander-fenster** [comment]
@lukesneeringer could also comment if he wants :)

**Comment by vkedia** [comment]
Sounds reasonable to me. Would we treat Floats in a similar way? For floats the reason we created a separate type was because spanner float can also contain these special values "+Infinity", "-Infinity", "NaN" while as I understand JS numbers cannot.

**Comment by alexander-fenster** [comment]
@stephenplusplus / @callmehiphop correct me if I'm wrong, but my understanding is that JavaScript Number is IEEE 754 compliant, hence could be plus or minus infinity or NaN:

```
> 1/0
Infinity
> -1/0
-Infinity
> Number("fourty two")
NaN
```

**Comment by vkedia** [comment]
I see. In that case why do we have a separate spanner.Float type?

**Comment by stephenplusplus** [comment]
@alexander-fenster that all sounds good to me.

RE: the Float type, we do have that for parity with `Int`, but also because if the user provides us a value of `8.0`, and it is meant to be saved as a FLOAT64, there is no type detection we could do that will tell us they meant to use `8` as a float, outside of making them wrap it in a `Float` type. Here's how we tell between INT64 and FLOAT64: https://github.com/googleapis/nodejs-spanner/blob/dbf026e7645f54ca5191b9009c2dc91723b5b716/src/codec.js#L209-L218

**Comment by WaldoJeffers** [comment]
@alexander-fenster sounds good 👍 
Having a way to tell how numbers should be stored (in Spanner) makes sense, but I am unsure as to whether it makes sense when converting back to JS, since JS does not distinguish floats from ints.

**Comment by callmehiphop** [comment]
I'm a little late to the party, but in other APIs that have similar issues I've seen the presence of both strings and numbers like so

```js
{
  value: 10765432100123460000,
  valueStr: '10765432100123459999'
}
```

**Comment by vkedia** [comment]
@stephenplusplus Ok, I understand why we need a spanner.Float. But I agree with @WaldoJeffers that when converting to JSON we should just emit it as a number.

**Comment by stephenplusplus** [comment]
PR in progress: #84.
