### ISSUE TITLE
Windows test still running in Kokoro

### ISSUE THREAD

**Issue by JustinBeckwith** [googleapis/nodejs-spanner#832]
I noticed over in https://github.com/googleapis/nodejs-spanner/pull/825 that the Windows tests on GitHub Actions are passing, but we're still running Windows tests in Kokoro.  What's up with that?

**Comment by bcoe** [comment]
I appear to have addressed this at some point, see latest test runs:

https://github.com/googleapis/nodejs-spanner/pull/889
