### ISSUE TITLE
spanner: unable to run samples tests locally

### ISSUE THREAD

**Issue by skuruppu** [googleapis/nodejs-spanner#866]
#### Environment details

  - OS: Linux
  - Node.js version: v10.17.0
  - npm version: 5.8.0
  - `@google-cloud/spanner` version: 4.8.0

#### Steps to reproduce

  1. Checkout the master branch of the repo.
  2. `npm install`
  3. `npm run samples-test`

#### Expected output

The samples tests to run.

#### Actual output

```
  Spanner
    1) "before all" hook for "should create an example database"


  0 passing (12s)
  1 failing

  1) Spanner
       "before all" hook for "should create an example database":
     TypeError: Cannot read property 'filter' of undefined
      at Promise.all.instances.map (system-test/spanner.test.js:82:14)
      at process._tickCallback (internal/process/next_tick.js:68:7)
```

This doesn't seem to be a problem on Kokoro since I see that the tests pass there ([example run](https://source.cloud.google.com/results/invocations/338ce8f7-0863-4f5c-abfd-63c280462582/targets)).

**Comment by skuruppu** [comment]
I tried the proposed fix but it still didn't help :( I still get the same error.

**Comment by laljikanjareeya** [comment]
@skuruppu could provide the full stack trace it would helpful for digging more into it as it works fine locally for me.
If you are testing with backup and restore than we need to delete the backups first before deleting the instance on below:

https://github.com/googleapis/nodejs-spanner/blob/e6b4af6576cc642bcc066768ce6975d09405f431/samples/system-test/spanner.test.js#L48-L52

**Comment by skuruppu** [comment]
@laljikanjareeya, unfortunately the stack trace is still the same as the one I posted in the issue description. With console logs, I've narrowed it down to this line:

https://github.com/googleapis/nodejs-spanner/blob/e6b4af6576cc642bcc066768ce6975d09405f431/samples/system-test/spanner.test.js#L82

I hope that helps.

I get the issue even if I check out a clean branch.

**Comment by AVaksman** [comment]
@skuruppu could you print the content of the `res` variable,
https://github.com/googleapis/nodejs-spanner/blob/e6b4af6576cc642bcc066768ce6975d09405f431/samples/system-test/spanner.test.js#L76
 mainly 
`status`/`statusText` and `data` properties.

**Comment by skuruppu** [comment]
console.log(res);
```
  ...
  data: { operations: [ [Object] ] },
  status: 200,
  statusText: 'OK',
  ...
```
console.log(res.data.operation);
```
  [ { name:
     'projects/<project>/instances/test-instance-1587179923472/operations/080e2287b66c70e7',
    metadata:
     { '@type':
        'type.googleapis.com/google.spanner.admin.instance.v1.CreateInstanceMetadata',
       instance: [Object],
       startTime: '2020-04-18T03:18:46.339160Z',
       endTime: '2020-04-18T03:18:46.653449Z' },
    done: true,
    response:
     { '@type':
        'type.googleapis.com/google.spanner.admin.instance.v1.Instance',
       name:
        'projects/<project>/instances/test-instance-1587179923472',
       config:
        'projects/<project>/instanceConfigs/regional-us-central1',
       displayName: 'test-instance-1587179923472',
       nodeCount: 1,
       state: 'READY',
       labels: [Object] } } ]

**Comment by skuruppu** [comment]
I also can't reproduce this after #961 which refactored all the instance/database setup/teardown. Closing.
