### ISSUE TITLE
Incorrect type for ReadRequest `keys` parameter

### ISSUE THREAD

**Issue by geekflyer** [googleapis/nodejs-spanner#869]
#### Environment details

  - `@google-cloud/spanner` version: 4.8.0

#### Description

The typings of ReadRequest contain an incorrect type for the `keys` attribute. https://github.com/googleapis/nodejs-spanner/blob/c1098c5f4509918cacd3942b8f09354c88a85bb9/src/transaction.ts#L89 .

The current type is: `string[]` but the correct one should be `string[]|string[][]` 

The [docs](https://googleapis.dev/nodejs/spanner/latest/global.html#ReadRequest) also explicitly mention that arrays of arrays are allowed:
> The primary keys of the rows in this table to be yielded. If using a composite key, provide an array within this array. See the example below.

**Comment by laljikanjareeya** [comment]
@geekflyer  Thanks for catching it!
