### ISSUE TITLE
db.close() function does not kill sessions

### ISSUE THREAD

**Issue by zubeyiro** [googleapis/nodejs-spanner#89]
#### Environment details

  - OS: MacOS, Linux etc
  - Node.js version: 8.9.3
  - npm version: 5.6.0
  - @google-cloud/spanner version: 0.9.0

#### Steps to reproduce

  1. I have created a REST endpoint and made a read call then I have closed the connection with db.close(), I have called that endpoint couple of times
  2. I have listed all sessions with command 'gcloud spanner databases sessions list --database= --instance=
  3- New sessions added everytime I made a request, none of them ever been closed
  4- I did same procedure with C#, it worked as well, all obsolete sessions are got closed

Conclusion:
db.close() function does not working on NodeJS environment :)

**Comment by kriptontr** [comment]
my experinces with this is issue : 
i added some console output to  session-pool.js:488;
```
   console.log("newSession", session.id)
        self.getSessionGroup_(session).push(session);
        console.log(self.reads_.length);
        console.log(self.writes_.length)

```
which prints 
```
newSession projects/xx/instances/xx/databases/ovis_live/sessions/ABuzUfEEqoc9diyzMa14OXhCRoK4w9qrQwrIZeD8rEeTp8n3naVnfn8KEuWA
1
0
newSession projects/xx/instances/xx/databases/xx/sessions/ABuzUfFlqu7BHbMZNrCo7B9off4ZeBIKyYXTo-7PAeBaAjhDn1lbsSVYwNPF
2
0
newSession projects/ovis-fs/instances/xx/databases/xx/sessions/ABuzUfGDDqgcaEhJBZ4YLMrvoSOsFpFsZewu3YgU-RNXEYqcfh5LsFnhOHgU
2
0
newSession projects/xxinstancesxx/databases/xx/sessions/ABuzUfHXmWHcLxz3Cy3l745akpK6KiE49C_8YJrnOmLt0LlW_1LW_sWDs5__
2
0

```
value of self.reads_.length doesn rise at all. but when i scope active sessions with 
`gcloud spanner databases sessions list`
and count with sth like
` var count = (stdout.match(/---/g) || []).length;`
it rises continuously until it throws 
`Too many active sessions in database, limit is 10000. Increase the node count to allow more sessions.`
Error

**Comment by callmehiphop** [comment]
@zubeyiro I'm sorry you're running into this issue. If you don't mind could you put together some code to reproduce the issue you are describing? I made a very simple test case, however in my testing it seems like `database.close()` is deleting all of the sessions it creates.

@kriptontr Is it possible you're re-using the same database in multiple processes? Sessions aren't shared across processes, so if you're not calling `database.close()` once you're done with an object the number of sessions will climb very high.

**Comment by zubeyiro** [comment]
Well after we had a look at it with @kriptontr (he is also my colleague) we have noticed something different and sent a pull request about that. At NodeJS library, there is a problem with session handling, which causes @google-cloud/spanner to create new session for every single call. It wasnt about database.close() actually.

**Comment by callmehiphop** [comment]
@zubeyiro I see. Would it be possible to create a gist of that scenario then?

**Comment by kriptontr** [comment]
@callmehiphop  nope. there is a leak in session pool.Please take a look at this [commit](https://github.com/googleapis/nodejs-spanner/pull/90/files) 
1 - shift method removes session from array and resolves promise with this session right ? 
2- Then getSession_ returns this session to acquireSession_  , but at session-pool.js:398  it  runs self.borrowSession_(session) at callback:
3- borrowSession runs spliceSession_ and its tries to get index of shifted session with 
  var index = group.indexOf(session); at line 861
but session removed from array already  so index is -1 
so   group.splice(index, 1) runs with (-1,1) and removes an innocent (last) session from array :)  
its irrevelant with db.close. it is a leakage

**Comment by zubeyiro** [comment]
Yeah sure, I'm declaring Spanner and database instance as below, out of listener scope;

`const Spanner = require('./nodeSpanner');

global.db = {
    live: Spanner({
            projectId: 'project'
        })
        .instance('cs-instance')
        .database('db')
};`

then I'm making a read request in one of my get/post listeners;

`global.db.live
            .run({
                sql: "select query"
            })
            .then(results => {
                // do stuff
            });
`

Its a REST endpoint so basically it creates only one instance for all incoming requests.

I'm starting to call that endpoint several times and at the same time I'm running this command on terminal;

gcloud spanner databases session list --database= --instance=

Session count increases constantly even though I'm declaring only one db instance.

I also tried to declare database instance in listener and close it after code done with global.db.live.close(); but nothing changed, session count still increases.

**Comment by callmehiphop** [comment]
@kriptontr oh! I see now, thanks for clarifying

**Comment by zubeyiro** [comment]
Well quick fix would be great :) Because we are now using our fixed version and dont wanna miss any update
